// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GrantResponse struct {
	_tab flatbuffers.Table
}

const GrantResponseIdentifier = "SDGS"

func GetRootAsGrantResponse(buf []byte, offset flatbuffers.UOffsetT) *GrantResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GrantResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishGrantResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(GrantResponseIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func GrantResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, GrantResponseIdentifier)
}

func GetSizePrefixedRootAsGrantResponse(buf []byte, offset flatbuffers.UOffsetT) *GrantResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GrantResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGrantResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(GrantResponseIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedGrantResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, GrantResponseIdentifier)
}

func (rcv *GrantResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GrantResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GrantResponse) SchemaVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *GrantResponse) MutateSchemaVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *GrantResponse) ReqId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) EntitlementStatus() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) CapabilityToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) ExpiresAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GrantResponse) MutateExpiresAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *GrantResponse) GrantedDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) GrantedTimeoutMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GrantResponse) MutateGrantedTimeoutMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *GrantResponse) GrantSignature(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GrantResponse) GrantSignatureLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GrantResponse) GrantSignatureBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) MutateGrantSignature(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GrantResponse) GrantVerifierPublicKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GrantResponse) GrantVerifierPublicKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GrantResponse) GrantVerifierPublicKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantResponse) MutateGrantVerifierPublicKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GrantResponse) BundleDescriptor(obj *BundleDescriptor) *BundleDescriptor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BundleDescriptor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *GrantResponse) WrappedContentKey(obj *WrappedContentKey) *WrappedContentKey {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WrappedContentKey)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func GrantResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func GrantResponseAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint32) {
	builder.PrependUint32Slot(0, schemaVersion, 1)
}
func GrantResponseAddReqId(builder *flatbuffers.Builder, reqId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reqId), 0)
}
func GrantResponseAddEntitlementStatus(builder *flatbuffers.Builder, entitlementStatus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(entitlementStatus), 0)
}
func GrantResponseAddCapabilityToken(builder *flatbuffers.Builder, capabilityToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(capabilityToken), 0)
}
func GrantResponseAddExpiresAtMs(builder *flatbuffers.Builder, expiresAtMs uint64) {
	builder.PrependUint64Slot(4, expiresAtMs, 0)
}
func GrantResponseAddGrantedDomain(builder *flatbuffers.Builder, grantedDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(grantedDomain), 0)
}
func GrantResponseAddGrantedTimeoutMs(builder *flatbuffers.Builder, grantedTimeoutMs uint64) {
	builder.PrependUint64Slot(6, grantedTimeoutMs, 0)
}
func GrantResponseAddGrantSignature(builder *flatbuffers.Builder, grantSignature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(grantSignature), 0)
}
func GrantResponseStartGrantSignatureVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GrantResponseAddGrantVerifierPublicKey(builder *flatbuffers.Builder, grantVerifierPublicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(grantVerifierPublicKey), 0)
}
func GrantResponseStartGrantVerifierPublicKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GrantResponseAddBundleDescriptor(builder *flatbuffers.Builder, bundleDescriptor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(bundleDescriptor), 0)
}
func GrantResponseAddWrappedContentKey(builder *flatbuffers.Builder, wrappedContentKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(wrappedContentKey), 0)
}
func GrantResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
