// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import "strconv"

type ModuleDeliveryMessageType byte

const (
	ModuleDeliveryMessageTypeNONE            ModuleDeliveryMessageType = 0
	ModuleDeliveryMessageTypeGRANT_REQUEST   ModuleDeliveryMessageType = 1
	ModuleDeliveryMessageTypeGRANT_CHALLENGE ModuleDeliveryMessageType = 2
	ModuleDeliveryMessageTypeGRANT_PROOF     ModuleDeliveryMessageType = 3
	ModuleDeliveryMessageTypeGRANT_RESPONSE  ModuleDeliveryMessageType = 4
	ModuleDeliveryMessageTypeERROR_RESPONSE  ModuleDeliveryMessageType = 5
)

var EnumNamesModuleDeliveryMessageType = map[ModuleDeliveryMessageType]string{
	ModuleDeliveryMessageTypeNONE:            "NONE",
	ModuleDeliveryMessageTypeGRANT_REQUEST:   "GRANT_REQUEST",
	ModuleDeliveryMessageTypeGRANT_CHALLENGE: "GRANT_CHALLENGE",
	ModuleDeliveryMessageTypeGRANT_PROOF:     "GRANT_PROOF",
	ModuleDeliveryMessageTypeGRANT_RESPONSE:  "GRANT_RESPONSE",
	ModuleDeliveryMessageTypeERROR_RESPONSE:  "ERROR_RESPONSE",
}

var EnumValuesModuleDeliveryMessageType = map[string]ModuleDeliveryMessageType{
	"NONE":            ModuleDeliveryMessageTypeNONE,
	"GRANT_REQUEST":   ModuleDeliveryMessageTypeGRANT_REQUEST,
	"GRANT_CHALLENGE": ModuleDeliveryMessageTypeGRANT_CHALLENGE,
	"GRANT_PROOF":     ModuleDeliveryMessageTypeGRANT_PROOF,
	"GRANT_RESPONSE":  ModuleDeliveryMessageTypeGRANT_RESPONSE,
	"ERROR_RESPONSE":  ModuleDeliveryMessageTypeERROR_RESPONSE,
}

func (v ModuleDeliveryMessageType) String() string {
	if s, ok := EnumNamesModuleDeliveryMessageType[v]; ok {
		return s
	}
	return "ModuleDeliveryMessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
