// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ModuleDeliveryMessage struct {
	_tab flatbuffers.Table
}

const ModuleDeliveryMessageIdentifier = "SDMD"

func GetRootAsModuleDeliveryMessage(buf []byte, offset flatbuffers.UOffsetT) *ModuleDeliveryMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ModuleDeliveryMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishModuleDeliveryMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ModuleDeliveryMessageIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func ModuleDeliveryMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, ModuleDeliveryMessageIdentifier)
}

func GetSizePrefixedRootAsModuleDeliveryMessage(buf []byte, offset flatbuffers.UOffsetT) *ModuleDeliveryMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ModuleDeliveryMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedModuleDeliveryMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ModuleDeliveryMessageIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedModuleDeliveryMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, ModuleDeliveryMessageIdentifier)
}

func (rcv *ModuleDeliveryMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ModuleDeliveryMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ModuleDeliveryMessage) SchemaVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *ModuleDeliveryMessage) MutateSchemaVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ModuleDeliveryMessage) MessageType() ModuleDeliveryMessageType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ModuleDeliveryMessageType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ModuleDeliveryMessage) MutateMessageType(n ModuleDeliveryMessageType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ModuleDeliveryMessage) GrantRequest(obj *GrantRequest) *GrantRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GrantRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModuleDeliveryMessage) GrantChallenge(obj *GrantChallenge) *GrantChallenge {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GrantChallenge)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModuleDeliveryMessage) GrantProof(obj *GrantProof) *GrantProof {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GrantProof)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModuleDeliveryMessage) GrantResponse(obj *GrantResponse) *GrantResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GrantResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModuleDeliveryMessage) ErrorResponse(obj *ErrorResponse) *ErrorResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ErrorResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ModuleDeliveryMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ModuleDeliveryMessageAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint32) {
	builder.PrependUint32Slot(0, schemaVersion, 1)
}
func ModuleDeliveryMessageAddMessageType(builder *flatbuffers.Builder, messageType ModuleDeliveryMessageType) {
	builder.PrependByteSlot(1, byte(messageType), 0)
}
func ModuleDeliveryMessageAddGrantRequest(builder *flatbuffers.Builder, grantRequest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(grantRequest), 0)
}
func ModuleDeliveryMessageAddGrantChallenge(builder *flatbuffers.Builder, grantChallenge flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(grantChallenge), 0)
}
func ModuleDeliveryMessageAddGrantProof(builder *flatbuffers.Builder, grantProof flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(grantProof), 0)
}
func ModuleDeliveryMessageAddGrantResponse(builder *flatbuffers.Builder, grantResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(grantResponse), 0)
}
func ModuleDeliveryMessageAddErrorResponse(builder *flatbuffers.Builder, errorResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(errorResponse), 0)
}
func ModuleDeliveryMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
