// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

/// Ownership mode for an arena-backed frame.
type BufferOwnership byte

const (
	BufferOwnershipBORROWED       BufferOwnership = 0
	BufferOwnershipPRODUCER_OWNED BufferOwnership = 1
	BufferOwnershipHOST_OWNED     BufferOwnership = 2
	BufferOwnershipSHARED         BufferOwnership = 3
)

var EnumNamesBufferOwnership = map[BufferOwnership]string{
	BufferOwnershipBORROWED:       "BORROWED",
	BufferOwnershipPRODUCER_OWNED: "PRODUCER_OWNED",
	BufferOwnershipHOST_OWNED:     "HOST_OWNED",
	BufferOwnershipSHARED:         "SHARED",
}

var EnumValuesBufferOwnership = map[string]BufferOwnership{
	"BORROWED":       BufferOwnershipBORROWED,
	"PRODUCER_OWNED": BufferOwnershipPRODUCER_OWNED,
	"HOST_OWNED":     BufferOwnershipHOST_OWNED,
	"SHARED":         BufferOwnershipSHARED,
}

func (v BufferOwnership) String() string {
	if s, ok := EnumNamesBufferOwnership[v]; ok {
		return s
	}
	return "BufferOwnership(" + strconv.FormatInt(int64(v), 10) + ")"
}
