// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

/// Mutability contract for an arena-backed frame.
type BufferMutability byte

const (
	BufferMutabilityIMMUTABLE   BufferMutability = 0
	BufferMutabilityAPPEND_ONLY BufferMutability = 1
	BufferMutabilityMUTABLE     BufferMutability = 2
)

var EnumNamesBufferMutability = map[BufferMutability]string{
	BufferMutabilityIMMUTABLE:   "IMMUTABLE",
	BufferMutabilityAPPEND_ONLY: "APPEND_ONLY",
	BufferMutabilityMUTABLE:     "MUTABLE",
}

var EnumValuesBufferMutability = map[string]BufferMutability{
	"IMMUTABLE":   BufferMutabilityIMMUTABLE,
	"APPEND_ONLY": BufferMutabilityAPPEND_ONLY,
	"MUTABLE":     BufferMutabilityMUTABLE,
}

func (v BufferMutability) String() string {
	if s, ok := EnumNamesBufferMutability[v]; ok {
		return s
	}
	return "BufferMutability(" + strconv.FormatInt(int64(v), 10) + ")"
}
