// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Payload schema identity for a stream frame or accepted port type.
type FlatBufferTypeRef struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatBufferTypeRef(buf []byte, offset flatbuffers.UOffsetT) *FlatBufferTypeRef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatBufferTypeRef{}
	x.Init(buf, n+offset)
	return x
}

func FinishFlatBufferTypeRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFlatBufferTypeRef(buf []byte, offset flatbuffers.UOffsetT) *FlatBufferTypeRef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlatBufferTypeRef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFlatBufferTypeRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FlatBufferTypeRef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatBufferTypeRef) Table() flatbuffers.Table {
	return rcv._tab
}

/// Logical schema name, for example `OMM.fbs`.
func (rcv *FlatBufferTypeRef) SchemaName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Logical schema name, for example `OMM.fbs`.
/// Optional 4-byte FlatBuffer file identifier.
func (rcv *FlatBufferTypeRef) FileIdentifier() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Optional 4-byte FlatBuffer file identifier.
/// Optional schema hash bytes for stronger compatibility checks.
func (rcv *FlatBufferTypeRef) SchemaHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlatBufferTypeRef) SchemaHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlatBufferTypeRef) SchemaHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Optional schema hash bytes for stronger compatibility checks.
func (rcv *FlatBufferTypeRef) MutateSchemaHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

/// True when this port/type set accepts any FlatBuffer frame.
func (rcv *FlatBufferTypeRef) AcceptsAnyFlatbuffer() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// True when this port/type set accepts any FlatBuffer frame.
func (rcv *FlatBufferTypeRef) MutateAcceptsAnyFlatbuffer(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

/// Payload wire format. Defaults to regular FlatBuffer framing.
func (rcv *FlatBufferTypeRef) WireFormat() PayloadWireFormat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return PayloadWireFormat(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

/// Payload wire format. Defaults to regular FlatBuffer framing.
func (rcv *FlatBufferTypeRef) MutateWireFormat(n PayloadWireFormat) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

/// Root or layout type name for aligned-binary payloads.
func (rcv *FlatBufferTypeRef) RootTypeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Root or layout type name for aligned-binary payloads.
/// Fixed string length for aligned-binary schemas when required.
func (rcv *FlatBufferTypeRef) FixedStringLength() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Fixed string length for aligned-binary schemas when required.
func (rcv *FlatBufferTypeRef) MutateFixedStringLength(n uint16) bool {
	return rcv._tab.MutateUint16Slot(16, n)
}

/// Fixed byte length for aligned-binary payloads.
func (rcv *FlatBufferTypeRef) ByteLength() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Fixed byte length for aligned-binary payloads.
func (rcv *FlatBufferTypeRef) MutateByteLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

/// Required byte alignment for aligned-binary payloads.
func (rcv *FlatBufferTypeRef) RequiredAlignment() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Required byte alignment for aligned-binary payloads.
func (rcv *FlatBufferTypeRef) MutateRequiredAlignment(n uint16) bool {
	return rcv._tab.MutateUint16Slot(20, n)
}

func FlatBufferTypeRefStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func FlatBufferTypeRefAddSchemaName(builder *flatbuffers.Builder, schemaName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(schemaName), 0)
}
func FlatBufferTypeRefAddFileIdentifier(builder *flatbuffers.Builder, fileIdentifier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fileIdentifier), 0)
}
func FlatBufferTypeRefAddSchemaHash(builder *flatbuffers.Builder, schemaHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(schemaHash), 0)
}
func FlatBufferTypeRefStartSchemaHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FlatBufferTypeRefAddAcceptsAnyFlatbuffer(builder *flatbuffers.Builder, acceptsAnyFlatbuffer bool) {
	builder.PrependBoolSlot(3, acceptsAnyFlatbuffer, false)
}
func FlatBufferTypeRefAddWireFormat(builder *flatbuffers.Builder, wireFormat PayloadWireFormat) {
	builder.PrependByteSlot(4, byte(wireFormat), 0)
}
func FlatBufferTypeRefAddRootTypeName(builder *flatbuffers.Builder, rootTypeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(rootTypeName), 0)
}
func FlatBufferTypeRefAddFixedStringLength(builder *flatbuffers.Builder, fixedStringLength uint16) {
	builder.PrependUint16Slot(6, fixedStringLength, 0)
}
func FlatBufferTypeRefAddByteLength(builder *flatbuffers.Builder, byteLength uint32) {
	builder.PrependUint32Slot(7, byteLength, 0)
}
func FlatBufferTypeRefAddRequiredAlignment(builder *flatbuffers.Builder, requiredAlignment uint16) {
	builder.PrependUint16Slot(8, requiredAlignment, 0)
}
func FlatBufferTypeRefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
