// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

/// Logical payload wire format for a stream frame or accepted port type.
type PayloadWireFormat byte

const (
	PayloadWireFormatFlatbuffer    PayloadWireFormat = 0
	PayloadWireFormatAlignedBinary PayloadWireFormat = 1
)

var EnumNamesPayloadWireFormat = map[PayloadWireFormat]string{
	PayloadWireFormatFlatbuffer:    "Flatbuffer",
	PayloadWireFormatAlignedBinary: "AlignedBinary",
}

var EnumValuesPayloadWireFormat = map[string]PayloadWireFormat{
	"Flatbuffer":    PayloadWireFormatFlatbuffer,
	"AlignedBinary": PayloadWireFormatAlignedBinary,
}

func (v PayloadWireFormat) String() string {
	if s, ok := EnumNamesPayloadWireFormat[v]; ok {
		return s
	}
	return "PayloadWireFormat(" + strconv.FormatInt(int64(v), 10) + ")"
}
