// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Runtime descriptor for one FlatBuffer frame stored in an arena.
type TypedArenaBuffer struct {
	_tab flatbuffers.Table
}

const TypedArenaBufferIdentifier = "TABF"

func GetRootAsTypedArenaBuffer(buf []byte, offset flatbuffers.UOffsetT) *TypedArenaBuffer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypedArenaBuffer{}
	x.Init(buf, n+offset)
	return x
}

func FinishTypedArenaBufferBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TypedArenaBufferIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func TypedArenaBufferBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, TypedArenaBufferIdentifier)
}

func GetSizePrefixedRootAsTypedArenaBuffer(buf []byte, offset flatbuffers.UOffsetT) *TypedArenaBuffer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypedArenaBuffer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTypedArenaBufferBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TypedArenaBufferIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedTypedArenaBufferBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, TypedArenaBufferIdentifier)
}

func (rcv *TypedArenaBuffer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypedArenaBuffer) Table() flatbuffers.Table {
	return rcv._tab
}

/// Runtime schema identity for this frame.
func (rcv *TypedArenaBuffer) TypeRef(obj *FlatBufferTypeRef) *FlatBufferTypeRef {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FlatBufferTypeRef)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// Runtime schema identity for this frame.
/// Port that produced or will consume this frame.
func (rcv *TypedArenaBuffer) PortId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Port that produced or will consume this frame.
/// Required alignment of the underlying frame bytes.
func (rcv *TypedArenaBuffer) Alignment() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 8
}

/// Required alignment of the underlying frame bytes.
func (rcv *TypedArenaBuffer) MutateAlignment(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

/// Frame byte offset from the arena base.
func (rcv *TypedArenaBuffer) Offset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Frame byte offset from the arena base.
func (rcv *TypedArenaBuffer) MutateOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

/// Frame size in bytes.
func (rcv *TypedArenaBuffer) Size() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Frame size in bytes.
func (rcv *TypedArenaBuffer) MutateSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

/// Ownership contract for the buffer.
func (rcv *TypedArenaBuffer) Ownership() BufferOwnership {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return BufferOwnership(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

/// Ownership contract for the buffer.
func (rcv *TypedArenaBuffer) MutateOwnership(n BufferOwnership) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

/// Generation counter for stale-reference detection.
func (rcv *TypedArenaBuffer) Generation() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Generation counter for stale-reference detection.
func (rcv *TypedArenaBuffer) MutateGeneration(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

/// Mutability contract for downstream consumers.
func (rcv *TypedArenaBuffer) Mutability() BufferMutability {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return BufferMutability(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

/// Mutability contract for downstream consumers.
func (rcv *TypedArenaBuffer) MutateMutability(n BufferMutability) bool {
	return rcv._tab.MutateByteSlot(18, byte(n))
}

/// Flow/runtime trace identifier.
func (rcv *TypedArenaBuffer) TraceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// Flow/runtime trace identifier.
func (rcv *TypedArenaBuffer) MutateTraceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

/// Logical stream identifier.
func (rcv *TypedArenaBuffer) StreamId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Logical stream identifier.
func (rcv *TypedArenaBuffer) MutateStreamId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

/// Monotonic frame sequence number within a stream.
func (rcv *TypedArenaBuffer) Sequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// Monotonic frame sequence number within a stream.
func (rcv *TypedArenaBuffer) MutateSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

/// True if this frame closes the stream.
func (rcv *TypedArenaBuffer) EndOfStream() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// True if this frame closes the stream.
func (rcv *TypedArenaBuffer) MutateEndOfStream(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func TypedArenaBufferStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func TypedArenaBufferAddTypeRef(builder *flatbuffers.Builder, typeRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(typeRef), 0)
}
func TypedArenaBufferAddPortId(builder *flatbuffers.Builder, portId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(portId), 0)
}
func TypedArenaBufferAddAlignment(builder *flatbuffers.Builder, alignment uint16) {
	builder.PrependUint16Slot(2, alignment, 8)
}
func TypedArenaBufferAddOffset(builder *flatbuffers.Builder, offset uint32) {
	builder.PrependUint32Slot(3, offset, 0)
}
func TypedArenaBufferAddSize(builder *flatbuffers.Builder, size uint32) {
	builder.PrependUint32Slot(4, size, 0)
}
func TypedArenaBufferAddOwnership(builder *flatbuffers.Builder, ownership BufferOwnership) {
	builder.PrependByteSlot(5, byte(ownership), 0)
}
func TypedArenaBufferAddGeneration(builder *flatbuffers.Builder, generation uint32) {
	builder.PrependUint32Slot(6, generation, 0)
}
func TypedArenaBufferAddMutability(builder *flatbuffers.Builder, mutability BufferMutability) {
	builder.PrependByteSlot(7, byte(mutability), 0)
}
func TypedArenaBufferAddTraceId(builder *flatbuffers.Builder, traceId uint64) {
	builder.PrependUint64Slot(8, traceId, 0)
}
func TypedArenaBufferAddStreamId(builder *flatbuffers.Builder, streamId uint32) {
	builder.PrependUint32Slot(9, streamId, 0)
}
func TypedArenaBufferAddSequence(builder *flatbuffers.Builder, sequence uint64) {
	builder.PrependUint64Slot(10, sequence, 0)
}
func TypedArenaBufferAddEndOfStream(builder *flatbuffers.Builder, endOfStream bool) {
	builder.PrependBoolSlot(11, endOfStream, false)
}
func TypedArenaBufferEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
