// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BundleDescriptor struct {
	_tab flatbuffers.Table
}

const BundleDescriptorIdentifier = "SDBD"

func GetRootAsBundleDescriptor(buf []byte, offset flatbuffers.UOffsetT) *BundleDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BundleDescriptor{}
	x.Init(buf, n+offset)
	return x
}

func FinishBundleDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(BundleDescriptorIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func BundleDescriptorBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, BundleDescriptorIdentifier)
}

func GetSizePrefixedRootAsBundleDescriptor(buf []byte, offset flatbuffers.UOffsetT) *BundleDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BundleDescriptor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBundleDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(BundleDescriptorIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedBundleDescriptorBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, BundleDescriptorIdentifier)
}

func (rcv *BundleDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BundleDescriptor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BundleDescriptor) SchemaVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *BundleDescriptor) MutateSchemaVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *BundleDescriptor) Cid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) ContentHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BundleDescriptor) ContentHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BundleDescriptor) ContentHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) MutateContentHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BundleDescriptor) SizeBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BundleDescriptor) MutateSizeBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *BundleDescriptor) ModuleId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) ModuleVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) Runtime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) Abi() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) Entrypoint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) PublicationCid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) ContentCodec() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BundleDescriptor) EncryptionCodec() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BundleDescriptorStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func BundleDescriptorAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint32) {
	builder.PrependUint32Slot(0, schemaVersion, 1)
}
func BundleDescriptorAddCid(builder *flatbuffers.Builder, cid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cid), 0)
}
func BundleDescriptorAddContentHash(builder *flatbuffers.Builder, contentHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(contentHash), 0)
}
func BundleDescriptorStartContentHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BundleDescriptorAddSizeBytes(builder *flatbuffers.Builder, sizeBytes uint64) {
	builder.PrependUint64Slot(3, sizeBytes, 0)
}
func BundleDescriptorAddModuleId(builder *flatbuffers.Builder, moduleId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(moduleId), 0)
}
func BundleDescriptorAddModuleVersion(builder *flatbuffers.Builder, moduleVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(moduleVersion), 0)
}
func BundleDescriptorAddRuntime(builder *flatbuffers.Builder, runtime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(runtime), 0)
}
func BundleDescriptorAddAbi(builder *flatbuffers.Builder, abi flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(abi), 0)
}
func BundleDescriptorAddEntrypoint(builder *flatbuffers.Builder, entrypoint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(entrypoint), 0)
}
func BundleDescriptorAddPublicationCid(builder *flatbuffers.Builder, publicationCid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(publicationCid), 0)
}
func BundleDescriptorAddContentCodec(builder *flatbuffers.Builder, contentCodec flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(contentCodec), 0)
}
func BundleDescriptorAddEncryptionCodec(builder *flatbuffers.Builder, encryptionCodec flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(encryptionCodec), 0)
}
func BundleDescriptorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
