// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ErrorResponse struct {
	_tab flatbuffers.Table
}

const ErrorResponseIdentifier = "SDER"

func GetRootAsErrorResponse(buf []byte, offset flatbuffers.UOffsetT) *ErrorResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ErrorResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishErrorResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ErrorResponseIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func ErrorResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, ErrorResponseIdentifier)
}

func GetSizePrefixedRootAsErrorResponse(buf []byte, offset flatbuffers.UOffsetT) *ErrorResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ErrorResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedErrorResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ErrorResponseIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedErrorResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, ErrorResponseIdentifier)
}

func (rcv *ErrorResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ErrorResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ErrorResponse) SchemaVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *ErrorResponse) MutateSchemaVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ErrorResponse) ReqId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorResponse) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorResponse) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorResponse) Retryable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ErrorResponse) MutateRetryable(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func ErrorResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ErrorResponseAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint32) {
	builder.PrependUint32Slot(0, schemaVersion, 1)
}
func ErrorResponseAddReqId(builder *flatbuffers.Builder, reqId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reqId), 0)
}
func ErrorResponseAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(code), 0)
}
func ErrorResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(message), 0)
}
func ErrorResponseAddRetryable(builder *flatbuffers.Builder, retryable bool) {
	builder.PrependBoolSlot(4, retryable, false)
}
func ErrorResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
