/**
 * Node status view model.
 *
 * Decodes a size-prefixed `NodeStatusSet` FlatBuffer (file identifier `$NST`,
 * emitted by the node's `/ws/status` feed) into a plain, JSON-friendly view
 * model. The wire schema uses UPPER_SNAKE_CASE field accessors (generated by
 * the FlatBuffers compiler); this module normalizes them to camelCase for
 * consumption by the status dashboard UI.
 *
 * The generated code under `./generated` is produced by the schema task and is
 * never edited here.
 */

import * as flatbuffers from 'flatbuffers';

import { NodeStatus, NodeStatusSet } from './generated/nst.js';

/** A single node in the status view. */
export interface NodeStatusView {
  /** libp2p peer ID (base58). */
  peerId: string;
  /** Distinguished name from the node's EPM. */
  dn: string;
  /** Organization / legal name from the node's EPM. */
  org: string;
  /** Full vCard 4.0 text derived from the peer's EPM (empty if unresolved). */
  vcard: string;
  /** GeoIP-resolved latitude (0 = unresolved). */
  lat: number;
  /** GeoIP-resolved longitude (0 = unresolved). */
  lon: number;
  /** Human-readable "City, Country" label (empty if unresolved). */
  geoLabel: string;
  /** True when the peer currently has a live connection. */
  online: boolean;
  /** True on the node emitting this set. */
  isSelf: boolean;
  /** Agent version string reported by the peer. */
  agent: string;
  /** Seconds since the emitting process started (self only; 0 otherwise). */
  uptimeS: number;
  /** Unix seconds of last observation (0 = never). */
  lastSeen: number;
  /** Multiaddrs the peer is known by. */
  addrs: string[];
  /** Trust level from the node's EPM. */
  trustLevel: string;
  /** Role the node advertises (e.g. bootstrap, relay). */
  role: string;
  /** Round-trip latency to the peer, milliseconds (0 = unknown). */
  latencyMs: number;
  /** SDN suite version reported by the peer. */
  suiteVersion: string;
  /** spacedatastandards.org version reported by the peer. */
  standardsVersion: string;
}

/** The decoded status set as a plain view model. */
export interface NodeStatusSetView {
  /** All nodes known to the emitting node (self first by convention). */
  nodes: NodeStatusView[];
  /** Unix milliseconds when this set was generated. */
  generatedAt: number;
  /** Peer ID of the emitting node. */
  sourcePeerId: string;
}

/** Build a "City, Country" label, omitting empty parts. */
function geoLabelFrom(city: string | null, country: string | null): string {
  return [city ?? '', country ?? ''].filter((part) => part.length > 0).join(', ');
}

/**
 * Map a single decoded `NodeStatus` FlatBuffer table to the plain view model.
 */
export function nodeStatusToView(node: NodeStatus): NodeStatusView {
  const addrs: string[] = [];
  const addrCount = node.multiformatAddressLength();
  for (let i = 0; i < addrCount; i += 1) {
    const addr = node.MULTIFORMAT_ADDRESS(i);
    if (typeof addr === 'string' && addr.length > 0) addrs.push(addr);
  }

  return {
    peerId: node.PEER_ID() ?? '',
    dn: node.DN() ?? '',
    org: node.ORGANIZATION() ?? '',
    vcard: node.VCARD() ?? '',
    lat: node.LAT(),
    lon: node.LON(),
    geoLabel: geoLabelFrom(node.GEO_CITY(), node.GEO_COUNTRY()),
    online: node.IS_ONLINE(),
    isSelf: node.IS_SELF(),
    agent: node.AGENT_VERSION() ?? '',
    uptimeS: Number(node.UPTIME_S()),
    lastSeen: Number(node.LAST_SEEN()),
    addrs,
    trustLevel: node.TRUST_LEVEL() ?? '',
    role: node.ROLE() ?? '',
    latencyMs: node.LATENCY_MS(),
    suiteVersion: node.SUITE_VERSION() ?? '',
    standardsVersion: node.STANDARDS_VERSION() ?? '',
  };
}

/**
 * Map a decoded `NodeStatusSet` FlatBuffer table to the plain view model.
 */
export function nodeStatusSetToView(set: NodeStatusSet): NodeStatusSetView {
  const nodes: NodeStatusView[] = [];
  const count = set.nodesLength();
  for (let i = 0; i < count; i += 1) {
    const node = set.NODES(i);
    if (node) nodes.push(nodeStatusToView(node));
  }

  return {
    nodes,
    generatedAt: Number(set.GENERATED_AT()),
    sourcePeerId: set.SOURCE_PEER_ID() ?? '',
  };
}

/**
 * Decode size-prefixed `NodeStatusSet` bytes (as delivered over `/ws/status`)
 * into the plain view model.
 *
 * @throws if the bytes are not a valid size-prefixed `$NST` buffer.
 */
export function decodeNodeStatusSet(bytes: Uint8Array): NodeStatusSetView {
  const buffer = new flatbuffers.ByteBuffer(bytes);
  const set = NodeStatusSet.getSizePrefixedRootAsNodeStatusSet(buffer);
  return nodeStatusSetToView(set);
}

/**
 * Decode a non-size-prefixed `NodeStatusSet` buffer into the view model. Used
 * when the caller has already stripped the 4-byte size prefix.
 */
export function decodeNodeStatusSetRoot(bytes: Uint8Array): NodeStatusSetView {
  const buffer = new flatbuffers.ByteBuffer(bytes);
  const set = NodeStatusSet.getRootAsNodeStatusSet(buffer);
  return nodeStatusSetToView(set);
}
