// Typesets math.mjs to SVG paths with MathJax and writes math.gen.js, so the
// reels draw crisp equations without loading a math library at render time.
//   MATHJAX_DIR=<dir holding node_modules/mathjax-full> node tools/paper-reels/typeset.mjs
// Pinned to mathjax-full 3.2.2; the output is deterministic for that version.

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { TEX } from "./math.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(join(process.env.MATHJAX_DIR ?? process.cwd(), "package.json"));
const { mathjax } = require("mathjax-full/js/mathjax.js");
const { TeX } = require("mathjax-full/js/input/tex.js");
const { SVG } = require("mathjax-full/js/output/svg.js");
const { liteAdaptor } = require("mathjax-full/js/adaptors/liteAdaptor.js");
const { RegisterHTMLHandler } = require("mathjax-full/js/handlers/html.js");
const { AllPackages } = require("mathjax-full/js/input/tex/AllPackages.js");

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document("", {
  InputJax: new TeX({ packages: AllPackages }),
  OutputJax: new SVG({ fontCache: "none" }),
});

const out = {};
for (const [key, tex] of Object.entries(TEX)) {
  const node = doc.convert(tex, { display: true });
  const svg = adaptor.firstChild(node);
  const html = adaptor.outerHTML(svg);
  if (/data-mjx-error|merror/.test(html)) throw new Error(`TeX error in ${key}`);
  // Keep only what drawing needs: the viewBox and the glyph paths.
  // Nested svg and rect elements (stretchy delimiters, fraction bars) keep
  // their sizes; only the root loses its ex-unit size.
  out[key] = html
    .replace(/^<svg[^>]*>/, (tag) => tag.replace(/ (?:style|role|focusable|aria-hidden|xmlns:xlink|width|height)="[^"]*"/g, ""))
    .replace(/ data-[a-z-]+="[^"]*"/g, "");
}
const body = Object.entries(out).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join("\n");
writeFileSync(join(here, "math.gen.js"), `// Generated by typeset.mjs from math.mjs (mathjax-full 3.2.2). Do not edit.\nexport const SVG = {\n${body}\n};\n`);
process.stdout.write(`typeset ${Object.keys(out).length} equations\n`);
