// Code generated by scripts/generate-suite-version-info.js. DO NOT EDIT.

export const SUITE_VERSION = "1.0.4";
export const SPACEDATASTANDARDS_VERSION = "1.155.0";
export const FLATSQL_VERSION = "1.1.0";
export const HD_WALLET_WASM_VERSION = "2.0.29";
export const HD_WALLET_UI_VERSION = "2.0.29";
export const IPFS_WEBUI_VERSION = "4.12.0";
export const DEFAULT_UPDATE_CHANNEL = "stable";
export const CURRENT_ADVERTISEMENT_FLAG = "spacedatanetwork/1.0.0";
export const SUPPORTED_ADVERTISEMENT_FLAGS = [
  "spacedatanetwork/1.0.0",
] as const;

export const SUITE_VERSION_INFO = Object.freeze({
  suiteVersion: SUITE_VERSION,
  spacedatastandardsVersion: SPACEDATASTANDARDS_VERSION,
  flatsqlVersion: FLATSQL_VERSION,
  hdWalletWasmVersion: HD_WALLET_WASM_VERSION,
  hdWalletUIVersion: HD_WALLET_UI_VERSION,
  ipfsWebUIVersion: IPFS_WEBUI_VERSION,
  defaultUpdateChannel: DEFAULT_UPDATE_CHANNEL,
  currentAdvertisementFlag: CURRENT_ADVERTISEMENT_FLAG,
  supportedAdvertisementFlags: [...SUPPORTED_ADVERTISEMENT_FLAGS],
});
