package storage

// engine_records_parity_test.go (loop D.2) — the STORE-level half of the A.2
// isomorphism gate: the Go server's real store (StoreBatch[WithSourceTags]
// write path -> engine mirror -> QueryEpochRawStream / QueryRawStream) must
// reproduce the epoch-profile aligned streams recorded in
// shared-test-vectors/flatsql-parity.json byte-for-byte. The JS twin drives
// the sdn-js engine record store's public API over the SAME corpus
// (sdn-js/src/flatsql-parity.test.ts); expectations are generated by the
// reference JS engine (sdn-js/scripts/generate-flatsql-parity-vectors.mjs).
//
// It also pins SQL identity: the shared fixture's engineEpochSql strings are
// asserted to equal this package's engine_records.go constants VERBATIM (the
// sdn-js builder is asserted against the same fixture on the JS side), and
// re-verifies the D.1 finding — the OR-form `_source` predicate and the
// direct-equality pushdown form return identical bytes.

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/spacedatanetwork/sdn-server/internal/flatsqlrt"
)

type epochParityParam struct {
	T string          `json:"t"`
	V json.RawMessage `json:"v"`
}

type epochParityExpectation struct {
	SHA256     string `json:"sha256"`
	ByteLength int    `json:"byteLength"`
	FrameCount int    `json:"frameCount"`
}

type epochParityVectors struct {
	Schema         string `json:"schema"`
	FileID         string `json:"fileId"`
	Table          string `json:"table"`
	EngineEpochSQL struct {
		Nearest string `json:"nearest"`
		AsOf    string `json:"as_of"`
		Forward string `json:"forward"`
	} `json:"engineEpochSql"`
	EpochStoreCorpus struct {
		SchemaName string `json:"schemaName"`
		StandardID string `json:"standardId"`
		Sources    []struct {
			Name         string `json:"name"`
			Tagged       bool   `json:"tagged"`
			RecordCount  int    `json:"recordCount"`
			StreamBase64 string `json:"streamBase64"`
		} `json:"sources"`
	} `json:"epochStoreCorpus"`
	EpochStoreCases []struct {
		Name    string  `json:"name"`
		Profile string  `json:"profile"`
		Source  string  `json:"source"`
		Epoch   float64 `json:"epoch"`
		Limit   int     `json:"limit"`
	} `json:"epochStoreCases"`
	EpochStoreDirectCases []struct {
		Name       string             `json:"name"`
		SQL        string             `json:"sql"`
		Params     []epochParityParam `json:"params"`
		EqualsCase string             `json:"equalsCase"`
	} `json:"epochStoreDirectCases"`
	Expected struct {
		EpochStoreStreams map[string]epochParityExpectation `json:"epochStoreStreams"`
	} `json:"expected"`
}

func loadEpochParityVectors(t *testing.T) *epochParityVectors {
	t.Helper()
	path := filepath.Join("..", "..", "..", "shared-test-vectors", "flatsql-parity.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read parity vectors: %v", err)
	}
	var v epochParityVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("parse parity vectors: %v", err)
	}
	if len(v.Expected.EpochStoreStreams) == 0 {
		t.Fatal("parity vectors have no epoch store expectations — run sdn-js/scripts/generate-flatsql-parity-vectors.mjs")
	}
	return &v
}

func decodeEpochParityParams(t *testing.T, params []epochParityParam) []interface{} {
	t.Helper()
	out := make([]interface{}, 0, len(params))
	for _, p := range params {
		switch p.T {
		case "null":
			out = append(out, nil)
		case "bool":
			var v bool
			if err := json.Unmarshal(p.V, &v); err != nil {
				t.Fatalf("bool param: %v", err)
			}
			out = append(out, v)
		case "i64":
			var v int64
			if err := json.Unmarshal(p.V, &v); err != nil {
				t.Fatalf("i64 param: %v", err)
			}
			out = append(out, v)
		case "f64":
			var v float64
			if err := json.Unmarshal(p.V, &v); err != nil {
				t.Fatalf("f64 param: %v", err)
			}
			out = append(out, v)
		case "str":
			var v string
			if err := json.Unmarshal(p.V, &v); err != nil {
				t.Fatalf("str param: %v", err)
			}
			out = append(out, v)
		case "bytes":
			var v string
			if err := json.Unmarshal(p.V, &v); err != nil {
				t.Fatalf("bytes param: %v", err)
			}
			b, err := base64.StdEncoding.DecodeString(v)
			if err != nil {
				t.Fatalf("bytes param base64: %v", err)
			}
			out = append(out, b)
		default:
			t.Fatalf("unknown param tag %q", p.T)
		}
	}
	return out
}

func digestEpochParityStream(t *testing.T, stream *flatsqlrt.RawStream) epochParityExpectation {
	t.Helper()
	frames, err := flatsqlrt.DecodeSizePrefixedStream(stream.Bytes)
	if err != nil {
		t.Fatalf("decode raw stream: %v", err)
	}
	sum := sha256.Sum256(stream.Bytes)
	return epochParityExpectation{
		SHA256:     hex.EncodeToString(sum[:]),
		ByteLength: len(stream.Bytes),
		FrameCount: len(frames),
	}
}

func TestEngineEpochParityWithJSHost(t *testing.T) {
	vectors := loadEpochParityVectors(t)

	// SQL identity: the shared fixture is a verbatim copy of this package's
	// engine constants; the sdn-js epoch SQL builder is asserted against the
	// SAME fixture strings on the JS side — no parallel dialect.
	if vectors.EngineEpochSQL.Nearest != engineEpochNearestSQL {
		t.Fatalf("engineEpochSql.nearest diverged from engine_records.go:\nfixture: %s\nserver:  %s",
			vectors.EngineEpochSQL.Nearest, engineEpochNearestSQL)
	}
	if vectors.EngineEpochSQL.AsOf != engineEpochAsOfSQL {
		t.Fatalf("engineEpochSql.as_of diverged from engine_records.go:\nfixture: %s\nserver:  %s",
			vectors.EngineEpochSQL.AsOf, engineEpochAsOfSQL)
	}
	if vectors.EngineEpochSQL.Forward != engineEpochForwardSQL {
		t.Fatalf("engineEpochSql.forward diverged from engine_records.go:\nfixture: %s\nserver:  %s",
			vectors.EngineEpochSQL.Forward, engineEpochForwardSQL)
	}
	// Both hosts create their engine tables from the same schema text.
	if vectors.Schema != engineRecordSchema {
		t.Fatal("shared parity schema diverged from engineRecordSchema")
	}

	// Ingest the shared corpus through the REAL store write path: tagged
	// sources via StoreBatchWithSourceTags (per-source engine shadow tables),
	// the untagged source via StoreBatch (server-default `local` partition).
	store := newEngineRecordsStore(t, filepath.Join(t.TempDir(), "store"))
	defer store.Close()

	schemaName := vectors.EpochStoreCorpus.SchemaName
	totalRecords := 0
	for _, src := range vectors.EpochStoreCorpus.Sources {
		stream, err := base64.StdEncoding.DecodeString(src.StreamBase64)
		if err != nil {
			t.Fatalf("decode corpus stream %q: %v", src.Name, err)
		}
		frames, err := flatsqlrt.DecodeSizePrefixedStream(stream)
		if err != nil {
			t.Fatalf("decode corpus frames %q: %v", src.Name, err)
		}
		if len(frames) != src.RecordCount {
			t.Fatalf("corpus source %q has %d frames, manifest says %d", src.Name, len(frames), src.RecordCount)
		}
		var inserted int
		if src.Tagged {
			tags := SourceTags{ProviderID: src.Name, SourceName: src.Name, BatchID: "parity"}
			inserted, err = store.StoreBatchWithSourceTags(schemaName, frames, "peer-epoch-parity", nil, tags)
		} else {
			inserted, err = store.StoreBatch(schemaName, frames, "peer-epoch-parity", nil)
		}
		if err != nil {
			t.Fatalf("store corpus source %q: %v", src.Name, err)
		}
		if inserted != src.RecordCount {
			t.Fatalf("stored %d records for source %q, want %d", inserted, src.Name, src.RecordCount)
		}
		totalRecords += inserted
	}
	count, err := store.EngineRecordCount(schemaName)
	if err != nil {
		t.Fatalf("EngineRecordCount: %v", err)
	}
	if count != int64(totalRecords) {
		t.Fatalf("engine resident count = %d, want %d", count, totalRecords)
	}
	t.Logf("corpus: %d records across %d sources (%v)", totalRecords,
		len(vectors.EpochStoreCorpus.Sources),
		func() []string {
			names := make([]string, 0, len(vectors.EpochStoreCorpus.Sources))
			for _, s := range vectors.EpochStoreCorpus.Sources {
				names = append(names, s.Name)
			}
			return names
		}())

	// Profile cases through the server's public epoch query API. Streams
	// must be BYTE-IDENTICAL to the shared expectations the sdn-js store
	// reproduces (same records, same order, same aligned framing).
	for _, c := range vectors.EpochStoreCases {
		res, err := store.QueryEpochRawStream(schemaName, c.Source, c.Profile, c.Epoch, c.Limit)
		if err != nil {
			t.Fatalf("case %q: QueryEpochRawStream: %v", c.Name, err)
		}
		want, ok := vectors.Expected.EpochStoreStreams[c.Name]
		if !ok {
			t.Fatalf("no expected output for epoch case %q", c.Name)
		}
		got := digestEpochParityStream(t, res)
		if got != want {
			t.Errorf("case %q: %+v, JS host produced %+v — HOSTS DIVERGED", c.Name, got, want)
		} else {
			t.Logf("case %-32s sha256=%s bytes=%d frames=%d BYTE-IDENTICAL", c.Name, got.SHA256, got.ByteLength, got.FrameCount)
		}
	}

	// D.1 re-verify through the generic raw-stream passthrough: OR-form vs
	// direct `_source = ?1` pushdown form — identical bytes, and identical
	// to the profile-API result for the same provider filter.
	for _, c := range vectors.EpochStoreDirectCases {
		res, err := store.QueryRawStream(c.SQL, decodeEpochParityParams(t, c.Params)...)
		if err != nil {
			t.Fatalf("direct case %q: QueryRawStream: %v", c.Name, err)
		}
		want, ok := vectors.Expected.EpochStoreStreams[c.Name]
		if !ok {
			t.Fatalf("no expected output for direct case %q", c.Name)
		}
		got := digestEpochParityStream(t, res)
		if got != want {
			t.Errorf("direct case %q: %+v, JS host produced %+v — HOSTS DIVERGED", c.Name, got, want)
		}
		if equals, ok := vectors.Expected.EpochStoreStreams[c.EqualsCase]; ok {
			if got != equals {
				t.Errorf("direct case %q: %+v differs from %q %+v — predicate forms diverged", c.Name, got, c.EqualsCase, equals)
			}
		} else {
			t.Fatalf("direct case %q references unknown case %q", c.Name, c.EqualsCase)
		}
		t.Logf("direct case %-28s sha256=%s == %s", c.Name, got.SHA256, c.EqualsCase)
	}
}
