// Code generated by sdn-server/internal/storage/gen; DO NOT EDIT.
// Regenerate with: go generate ./sdn-server/internal/storage/...
//
// OWNER DIRECTIVE (2026-08-25): "The routing of $IRM just needs to be another
// one of the standards ingested like all the others in the standards engine."
// This file is that directive made structural — every embedded SDS standard
// that declares a file_identifier gets an engine table here, so no standard is
// ever routed (or forgotten) by name.

package storage

// engineStandardCatalogGraph is the engine table graph for every routed
// standard except the two whose text is pinned as a cross-host contract
// (engineRecordSchema for $OMM, engineTBSTableGraph for $TBS). Columns are the
// LEADING RUN of exactly-representable root-table fields in declaration order
// — see internal/storage/enginecatalog for why a leading run and not a filter.
// Everything past the stop point still travels in `_data`, which is the
// whole record.
const engineStandardCatalogGraph = `
  table ACI {
    ACI_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    RFL_ID:string;
  }
  table ACL {
    GRANT_ID:string;
    LISTING_ID:string;
    BUYER_PEER_ID:string;
    BUYER_ENCRYPTION_PUBKEY:[ubyte];
    ACCESS_TYPE:byte;
    TIER_NAME:string;
    GRANTED_AT:uint64;
    EXPIRES_AT:uint64;
    PAYMENT_TX_HASH:string;
    PAYMENT_METHOD:byte;
    PROVIDER_SIGNATURE:[ubyte];
    KEY_ALGORITHM:string;
    RATE_LIMIT:uint32;
    MAX_RECORDS_PER_REQUEST:uint32;
    STATUS:byte;
    PAYMENT_AMOUNT:uint64;
    PAYMENT_CURRENCY:string;
    PAYMENT_CHAIN:string;
    NEXT_RENEWAL:uint64;
    AUTO_RENEW:bool;
    RENEWAL_COUNT:uint32;
    TOTAL_REQUESTS:uint64;
    TOTAL_RECORDS:uint64;
    LAST_ACCESS:uint64;
    DELIVERY_TOPIC:string;
    CREATED_AT:uint64;
    UPDATED_AT:uint64;
    NOTES:string;
    PROVIDER_PEER_ID:string;
    GRANT_RESPONSE_BASE64:string;
  }
  table ACM {
    CCSDS_ACM_VERS:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    CATALOG_NAME:string;
    EPOCH:string;
    TIME_SYSTEM:string;
  }
  table ACR {
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    ATTITUDE_X:double;
    ATTITUDE_Y:double;
    ATTITUDE_Z:double;
    ATTITUDE_W:double;
    OMEGA_X:double;
    OMEGA_Y:double;
    OMEGA_Z:double;
    MASS:double;
    CG_X:float;
    CG_Z:float;
    AERO:string;
    CONTROLS:string;
    ENGINE:string;
    GEAR_STATE:ubyte;
    GEAR_POSITION:ubyte;
    FLAP_POSITION:ubyte;
    SPEEDBRAKE_POS:ubyte;
    FLIGHT_PHASE:ubyte;
    AUTOPILOT_MODE:ubyte;
    WEIGHT_ON_WHEELS:ubyte;
    RESERVED:ubyte;
  }
  table ACW {
    REQUEST:ubyte;
  }
  table AEM {
    CCSDS_AEM_VERS:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
  }
  table ANI {
    ID:string;
    SOURCE_ID:string;
    SOURCE_TYPE:string;
    ANALYTIC_TYPE:byte;
    ALGORITHM:string;
    ALGORITHM_VERSION:string;
    PROCESSING_TIME:string;
    OBS_TIME:string;
    SAT_NO:uint32;
    OBJECT_DESIGNATOR:string;
    RA:double;
    DEC:double;
    FOV:double;
    VISUAL_MAG:double;
    MAG_UNCERTAINTY:double;
    OBJECT_COUNT:uint;
  }
  table AOF {
    VERSION:ubyte;
    SPACECRAFT_ID:ushort;
    VIRTUAL_CHANNEL_ID:ubyte;
    VIRTUAL_FRAME_COUNT:uint;
    REPLAY_FLAG:bool;
    VC_FRAME_COUNT_USAGE:bool;
    VC_FRAME_COUNT_CYCLE:ubyte;
    INSERT_ZONE:[ubyte];
    DATA:[ubyte];
    OCF:[ubyte];
    FECF:ushort;
  }
  table APL {
    APL_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    RFL_ID:string;
    LINK_ID:string;
    WINDOW_START:double;
    WINDOW_STOP:double;
    TIME_SYSTEM:byte;
  }
  table APM {
    CCSDS_APM_VERS:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    EPOCH:string;
    Q1:double;
    Q2:double;
    Q3:double;
    QC:double;
  }
  table APP {
    ID:string;
    NAME:string;
    VERSION:string;
    DESCRIPTION:string;
  }
  table ARM {
    THICKNESS:double;
    ANGLE:double;
    MATERIAL:ubyte;
    HARDNESS:ubyte;
    QUALITY:ubyte;
    ERA_TYPE:ubyte;
    ERA_EFFECTIVENESS:float;
    ERA_VS_KE:float;
    RHA_EQUIVALENT:float;
    NORMAL_X:double;
    NORMAL_Y:double;
    NORMAL_Z:double;
    RESERVED:[ubyte];
  }
  table AST {
    COMMAND:string;
    PROPAGATION_REQUEST:string;
    TLE:string;
    INITIAL_ELEMENTS:string;
    INITIAL_STATE:string;
    EPOCH_MS:long;
    MANEUVER_PLAN:string;
    CONJUNCTION_PRIMARY:string;
    CONJUNCTION_SECONDARY:string;
  }
  table ATD {
    ID:string;
    AS_ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    EPOCH:string;
    REPRESENTATION:byte;
    MOTION_TYPE:byte;
    QC:double;
    Q1:double;
    Q2:double;
    Q3:double;
    QC_DOT:double;
    Q1_DOT:double;
    Q2_DOT:double;
    Q3_DOT:double;
    X_ANGLE:double;
    Y_ANGLE:double;
    Z_ANGLE:double;
    X_RATE:double;
    Y_RATE:double;
    Z_RATE:double;
    RA:double;
    DECLINATION:double;
    CONING_ANGLE:double;
    PREC_PERIOD:double;
    SPIN_PERIOD:double;
    ATTITUDE_UNC:double;
    RATE_UNC:double;
    QUALITY:uint8;
    REF_FRAME:string;
    SENSOR_ID:string;
  }
  table ATM {
    MODEL:byte;
    YEAR:int;
  }
  table AVL {
    ID:string;
    DESIGNATOR:string;
    NAME:string;
    AIRSPACE_CLASS:byte;
    VOLUME_TYPE:byte;
    COUNTRY_CODE:string;
    FLOOR_VALUE:double;
    FLOOR_DATUM:byte;
    CEILING_VALUE:double;
    CEILING_DATUM:byte;
    EFFECTIVE_FROM:string;
    EFFECTIVE_TO:string;
    TIME_OF_ACTIVITY:string;
  }
  table BAL {
    COMMAND:string;
    TRAJECTORY_REQUEST:string;
    TABLE_REQUEST:string;
    FIRE_CONTROL:string;
    PENETRATION_PROJECTILE:string;
    PENETRATION_ARMOR:string;
    IMPACT_VELOCITY_MPS:double;
    IMPACT_ANGLE_DEG:double;
  }
  table BEM {
    ID:string;
    BEAM_NAME:string;
    ID_ENTITY:string;
    ID_ANTENNA:string;
    TYPE:byte;
    POLARIZATION:byte;
    PEAK_GAIN:double;
    EOC_GAIN:double;
    CENTER_LATITUDE:double;
    CENTER_LONGITUDE:double;
    BEAMWIDTH:double;
    FREQUENCY:double;
    EIRP:double;
    G_OVER_T:double;
    FOOTPRINT_AREA:double;
  }
  table BMC {
    ID:string;
    TYPE:string;
    CONTOUR_IDX:int;
    GAIN:double;
    REGION_NAME:string;
    GEOGRAPHY:string;
    GEOGRAPHY_TEXT:string;
    GEOGRAPHY_JSON:string;
    GEOGRAPHY_TYPE:string;
    GEOGRAPHY_NDIMS:int;
    GEOGRAPHY_SRID:int;
  }
  table BOV {
    E_COORDINATE:double;
    F_COORDINATE:double;
    G_COORDINATE:double;
    E_DOT:double;
    F_DOT:double;
    G_DOT:double;
    EPOCH:string;
    TIME_FROM_LAUNCH:double;
  }
  table BSP {
    INTERPOLATION_REQUEST:ubyte;
  }
  table BUS {
    ID:string;
    NAME:string;
    MANUFACTURER:string;
    SIZE:byte;
    DRY_MASS:double;
    WET_MASS:double;
    PAYLOAD_MASS:double;
    DIM_X:double;
    DIM_Y:double;
    DIM_Z:double;
    STOWED_X:double;
    STOWED_Y:double;
    STOWED_Z:double;
    POWER_GENERATION:double;
    PAYLOAD_POWER:double;
    BATTERY_CAPACITY:double;
    STABILIZATION:byte;
    POINTING_ACCURACY:double;
    POINTING_KNOWLEDGE:double;
    DESIGN_LIFE:double;
    DATA_STORAGE:double;
    DOWNLINK_RATE:double;
    PAYLOAD_SLOTS:uint;
    HERITAGE_COUNT:uint;
    NOTES:string;
  }
  table CAQ {
    REQUEST:ubyte;
  }
  table CAT {
    OBJECT_NAME:string;
    OBJECT_ID:string;
    NORAD_CAT_ID:uint;
    OBJECT_TYPE:byte;
    OPS_STATUS_CODE:byte;
    OWNER:byte;
    LAUNCH_DATE:string;
    LAUNCH_SITE:string;
    DECAY_DATE:string;
    PERIOD:double;
    INCLINATION:double;
    APOGEE:double;
    PERIGEE:double;
    RCS:double;
    DATA_STATUS_CODE:byte;
    ORBIT_CENTER:string;
    ORBIT_TYPE:byte;
    DEPLOYMENT_DATE:string;
    MANEUVERABLE:bool;
    SIZE:double;
    MASS:double;
    MASS_TYPE:byte;
  }
  table CCT {
    TAXONOMY_ID:string;
    VERSION:string;
    ISSUED_AT:uint64;
    TITLE:string;
  }
  table CDM {
    CCSDS_CDM_VERS:double;
    CREATION_DATE:string;
    ORIGINATOR:string;
    MESSAGE_FOR:string;
    MESSAGE_ID:string;
    TCA:string;
    MISS_DISTANCE:double;
    RELATIVE_SPEED:double;
    RELATIVE_POSITION_R:double;
    RELATIVE_POSITION_T:double;
    RELATIVE_POSITION_N:double;
    RELATIVE_VELOCITY_R:double;
    RELATIVE_VELOCITY_T:double;
    RELATIVE_VELOCITY_N:double;
    START_SCREEN_PERIOD:string;
    STOP_SCREEN_PERIOD:string;
  }
  table CES {
    DATASET_ID:string;
    UPDATE_ID:string;
    DIMENSIONS:uint32;
    ENCODING:byte;
    NORMALIZATION:byte;
    SIMILARITY:byte;
    MODEL_ID:string;
    MODEL_VERSION:string;
    MODEL_WEIGHTS_SHA256:string;
    POOLING_METHOD:byte;
    TEMPLATE_VERSION:string;
  }
  table CFP {
    VERSION:ubyte;
    PDU_TYPE:byte;
    DIRECTION:ubyte;
    TRANSMISSION_MODE:byte;
    CRC_FLAG:bool;
    LARGE_FILE_FLAG:bool;
    DATA_FIELD_LENGTH:ushort;
    SOURCE_ENTITY_ID:ulong;
    TRANSACTION_SEQ_NUM:ulong;
    DESTINATION_ENTITY_ID:ulong;
    CHECKSUM_TYPE:ubyte;
    FILE_SIZE:ulong;
    SOURCE_FILENAME:string;
    DESTINATION_FILENAME:string;
    DATA:[ubyte];
  }
  table CHN {
    ID:string;
    NAME:string;
    TYPE:string;
    BEAM_NAME:string;
    ID_RFBAND:string;
    ENCRYPTION:string;
    PKG:string;
    RES:string;
    COMPRESSION:string;
    VPID:string;
    APID:string;
    SID:string;
    OWNER:string;
  }
  table CLT {
    PDU_TYPE:byte;
    INITIATOR_ID:string;
    RESPONDER_PORT_ID:string;
    SERVICE_TYPE:ubyte;
    VERSION:ushort;
    INVOKE_ID:uint;
    DATA:[ubyte];
  }
  table CMR {
    MEMBERSHIP_ID:string;
    NORAD_CAT_ID:uint;
    OBJECT_ID:string;
    CONSTELLATION_ID:string;
    CONSTELLATION_NAME:string;
  }
  table CMS {
    ID:string;
    ID_ENTITY:string;
    NAME:string;
    DESCRIPTION:string;
    ENTITY:string;
    SAT_NO:uint32;
    NUM_TRANSPONDERS:uint;
  }
  table CMT {
    TERMS_ID:string;
    SCOPE:byte;
    TARGET_ID:string;
    COMMISSION_BPS:uint16;
  }
  table CNP {
    ID:string;
    CONSTELLATION:string;
    OPERATOR:string;
    ASN:uint32;
    AS_NAME:string;
    SERVICE_TIER:string;
  }
  table COM {
    SYSTEM_ID:uint;
    ENTITY_ID:uint;
    IS_TRANSMITTING:bool;
    IS_RECEIVING:bool;
    CURRENT_FREQUENCY_HZ:double;
    CURRENT_POWER_WATTS:double;
    CURRENT_DATA_RATE_BPS:double;
    MESSAGES_SENT:ulong;
    MESSAGES_RECEIVED:ulong;
    BYTES_SENT:ulong;
    BYTES_RECEIVED:ulong;
  }
  table COT {
    VERSION:string;
    UID:string;
    TYPE:string;
    HOW:byte;
    TIME:string;
    START:string;
    STALE:string;
    ACCESS:string;
    QOS:string;
    OPEX:string;
  }
  table CPS {
    ALGORITHM:ubyte;
    PACKET_LENGTH:ushort;
    PACKET_COUNT:uint32;
    ROBUSTNESS:ubyte;
    MASK_UPDATE_PERIOD:ushort;
    MASK_SEND_PERIOD:ushort;
    REFERENCE_PERIOD:ushort;
    SELF_SYNCHRONIZING:bool;
    STREAM_ID:string;
    SEGMENT_INDEX:uint32;
    APID:ushort;
    SPACECRAFT_ID:ushort;
    START_EPOCH:string;
    STOP_EPOCH:string;
    COMPRESSED_DATA:[ubyte];
    UNCOMPRESSED_LENGTH:uint32;
    UNCOMPRESSED_CRC32:uint32;
  }
  table CRD {
    X:double;
    Y:double;
    Z:double;
    VX:double;
    VY:double;
    VZ:double;
    FRAME:ubyte;
    ELLIPSOID:ubyte;
    RESERVED:[ubyte];
  }
  table CRM {
    ID:string;
    CLASSIFICATION:string;
    TYPE:string;
    ID_PLAN:string;
    PLAN_INDEX:int;
    TASK_ID:string;
    DWELL_ID:string;
    EXTERNAL_ID:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    OB_TYPE:string;
    PRIORITY:string;
    TASK_CATEGORY:int;
    SUFFIX:string;
    UCT_FOLLOW_UP:bool;
    START_TIME:string;
    END_TIME:string;
    NORAD_CAT_ID:uint32;
    ORIG_OBJECT_ID:string;
    TASK_GROUP:string;
    IRON:int;
    ORBIT_REGIME:string;
    TARGET_SIZE:double;
    RCS_MIN:double;
    RCS:double;
    RCS_MAX:double;
    FREQ_MIN:double;
    FREQ:double;
    FREQ_MAX:double;
    POLARIZATION:string;
    VIS_MAG_MIN:double;
    VIS_MAG:double;
    VIS_MAG_MAX:double;
    SPECTRAL_MODEL:string;
    REFLECTANCE:double;
    IRRADIANCE:double;
    NUM_FRAMES:int;
    FRAME_RATE:double;
    INTEGRATION_TIME:double;
    NUM_TRACKS:int;
    NUM_OBS:int;
    DURATION:int;
    SRCH_PATTERN:string;
    SCENARIO:string;
    ID_ELSET:string;
    ID_MANIFOLD:string;
    ID_STATE_VECTOR:string;
    ES_ID:string;
    EPOCH:string;
    SEMI_MAJOR_AXIS:double;
    ECCENTRICITY:double;
    INCLINATION:double;
    RAAN:double;
    ARG_OF_PERIGEE:double;
    MEAN_ANOMALY:double;
    RA:double;
    DEC:double;
    AZ:double;
    EL:double;
    RANGE:double;
    EXTENT_AZ:double;
    EXTENT_EL:double;
    EXTENT_RANGE:double;
    LAT:double;
    LON:double;
    ALT:double;
    STOP_LAT:double;
    STOP_LON:double;
    STOP_ALT:double;
    SRCH_INC:double;
    X_ANGLE:double;
    Y_ANGLE:double;
    ORIENT_ANGLE:double;
    CUSTOMER:string;
    NOTES:string;
    SOURCE:string;
    ORIGIN:string;
    DATA_MODE:string;
  }
  table CSM {
    OBJECT_1:ubyte;
  }
  table CTR {
    ID:string;
    NAME:string;
    GENC_CODE:string;
    ALPHA_2_CODE:string;
    ALPHA_3_CODE:string;
    STANAG_CODE:string;
    INTERNET_CCTLD:string;
    COMMENT:string;
  }
  table CVG {
    COVERAGE_ID:string;
    NAME:string;
    GRID_SCHEME:string;
    GRID_RESOLUTION:uint8;
  }
  table CVP {
    COVERAGE_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    GEOMETRY_KIND:byte;
    METRIC:byte;
    METRIC_UNITS:string;
    THRESHOLD_VALUE:double;
    THRESHOLD_UNITS:string;
    THRESHOLD_COMPARISON:byte;
    EPOCH:double;
    INTERVAL_START:double;
    INTERVAL_STOP:double;
    TIME_SYSTEM:byte;
    GENERATION:uint64;
    SUPERSEDES_COVERAGE_ID:string;
  }
  table CZM {
    NAME:string;
    VERSION:string;
    CLOCK_CURRENT_TIME:string;
    CLOCK_INTERVAL:string;
    CLOCK_MULTIPLIER:double;
    CLOCK_RANGE:string;
    CLOCK_STEP:string;
  }
  table DFH {
    ID:string;
    SAT_NO:uint32;
    OBJECT_DESIGNATOR:string;
    OBJECT_NAME:string;
    START_TIME:string;
    END_TIME:string;
    EFFECTIVE_UNTIL:string;
    DRIFT_RATE:double;
    MEAN_LONGITUDE:double;
    SLOT_CENTER:double;
    SLOT_HALF_WIDTH:double;
    STATION_KEEPING:bool;
  }
  table DMG {
    OVERALL_HEALTH:float;
    MOBILITY:float;
    FIREPOWER:float;
    MODULE_COUNT:ubyte;
    CREW_COUNT:ubyte;
    FIRE_COUNT:ubyte;
    FLOOD_COUNT:ubyte;
    IS_DESTROYED:ubyte;
    DESTRUCTION_CAUSE:ubyte;
    EXTINGUISHERS:ubyte;
    REPAIR_ACTIVE:ubyte;
    RELOAD_MULTIPLIER:float;
    ACCURACY_MULTIPLIER:float;
    CREW_ALIVE:ubyte;
    CREW_WOUNDED:ubyte;
    RESERVED:[ubyte];
  }
  table DOA {
    ID:string;
    OB_TIME:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    UCT:bool;
    TASK_ID:string;
    TRANSACTION_ID:string;
    COLLECTION_MODE:byte;
    ID_SENSOR1:string;
    ORIG_SENSOR_ID1:string;
    SENLAT:double;
    SENLON:double;
    SENALT:double;
    SENSOR1_DELAY:double;
    ID_SENSOR2:string;
    ORIG_SENSOR_ID2:string;
    SEN2LAT:double;
    SEN2LON:double;
    SEN2ALT:double;
    SENSOR2_DELAY:double;
    FREQUENCY:double;
    BANDWIDTH:double;
    SNR:double;
    DELTA_RANGE:double;
    DELTA_RANGE_UNC:double;
    DELTA_RANGE_RATE:double;
    DELTA_RANGE_RATE_UNC:double;
    TDOA:double;
    TDOA_UNC:double;
    FDOA:double;
    FDOA_UNC:double;
    RAW_FILE_URI:string;
    DESCRIPTOR:string;
  }
  table DPM {
    VERSION:string;
    DATASET_ID:string;
    UPDATE_ID:string;
    FILE_ID:string;
    PROVIDER_PEER_ID:string;
    PROVIDER_EPM_CID:string;
    PUBLISH_TIMESTAMP:string;
  }
  table DSS {
    STATUS:byte;
    SYNCED_ROWS:uint64;
    TOTAL_ROWS:uint64;
    LOCAL_ROWS:uint64;
    PINNED_ROWS:uint64;
    MISSING_ROWS:uint64;
    CACHED_BYTES:uint64;
    PINNED_BYTES:uint64;
    DOWNLOADED_BYTES:uint64;
    DOWNLOAD_SPEED_BYTES_PER_SECOND:uint64;
    MEASURED_WIRE_SPEED_BYTES_PER_SECOND:uint64;
    HAS_WIRE_SPEED_UTILIZATION:bool;
    WIRE_SPEED_UTILIZATION:double;
    WIRE_SPEED_TARGET:double;
    HAS_WIRE_SPEED_TARGET_MET:bool;
    WIRE_SPEED_TARGET_MET:bool;
    MANIFEST_DISCOVERY_MS:uint64;
    NETWORK_TRANSFER_MS:uint64;
    VERIFICATION_MS:uint64;
    FLATSQL_MATERIALIZATION_MS:uint64;
    PROVIDER_PEER_ID:string;
    PROVIDER_PUBLIC_KEY:string;
    SNAPSHOT_ID:string;
    HEAD:string;
    CURSOR:string;
    NEXT_CURSOR:string;
    HIGH_WATER_MARK:string;
    QUERY_PROFILE:string;
    CHUNK_HASH:string;
    SYNC_PROTOCOL:string;
    SYNC_FILTER:string;
  }
  table DTT {
    TILESET_ID:string;
    TILESET_NAME:string;
    TILING_SCHEME:byte;
    LEVEL:uint32;
    X:uint32;
    Y:uint32;
    ROW_ORIGIN_NORTH:bool;
    WEST_DEG:double;
    SOUTH_DEG:double;
    EAST_DEG:double;
    NORTH_DEG:double;
    MIN_HEIGHT_M:double;
    MAX_HEIGHT_M:double;
    PAYLOAD_FORMAT:byte;
    PAYLOAD_FORMAT_VERSION:string;
  }
  table EGP {
    GROUP_ID:string;
    NAME:string;
    DESCRIPTION:string;
  }
  table EMC {
    EMC_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    RFL_ID:string;
  }
  table EME {
    ENCRYPTED_BLOB:[ubyte];
    EPHEMERAL_PUBLIC_KEY:string;
    MAC:string;
    NONCE_START:[ubyte];
    TAG:string;
    IV:string;
    SALT:string;
    PUBLIC_KEY_IDENTIFIER:string;
    CIPHER_SUITE:string;
    KDF_PARAMETERS:string;
    ENCRYPTION_ALGORITHM_PARAMETERS:string;
  }
  table ENC {
    VERSION:ubyte;
    KEY_EXCHANGE:byte;
    SYMMETRIC:byte;
    KEY_DERIVATION:byte;
    EPHEMERAL_PUBLIC_KEY:[ubyte];
    NONCE_START:[ubyte];
    RECIPIENT_KEY_ID:[ubyte];
    CONTEXT:string;
    SCHEMA_HASH:[ubyte];
    ROOT_TYPE:string;
    TIMESTAMP:uint64;
  }
  table ENT {
    ENTITLEMENT_ID:string;
    XPUB:string;
    PEER_ID:string;
    PLAN:string;
    STATUS:byte;
    STATUS_TEXT:string;
    STRIPE_CUSTOMER_ID:string;
    STRIPE_SUBSCRIPTION_ID:string;
    EXPIRES_AT:uint64;
    CREATED_AT:uint64;
    UPDATED_AT:uint64;
    PROVIDER_PEER_ID:string;
    PROVIDER_SIGNATURE:[ubyte];
  }
  table ENV {
    ATMOSPHERE:string;
    WEATHER:string;
    TIME_UTC:double;
    LATITUDE:double;
    LONGITUDE:double;
    SUN_AZIMUTH:float;
    SUN_ELEVATION:float;
    MOON_PHASE:float;
    ILLUMINATION:float;
    MAGNETIC_DECLINATION:float;
    MAGNETIC_INCLINATION:float;
    RESERVED:[ubyte];
  }
  table EOO {
    ID:string;
    CLASSIFICATION:string;
    OB_TIME:string;
    CORR_QUALITY:float;
    ID_ON_ORBIT:string;
    SENSOR_ID:string;
    COLLECT_METHOD:byte;
    NORAD_CAT_ID:int;
    TASK_ID:string;
    TRANSACTION_ID:string;
    IMAGE_SET_ID:string;
    IMAGE_SET_LENGTH:int;
    SEQUENCE_ID:int;
    OB_POSITION:byte;
    ORIG_OBJECT_ID:string;
    ORIG_SENSOR_ID:string;
    UCT:bool;
    AZIMUTH:float;
    AZIMUTH_UNC:float;
    AZIMUTH_BIAS:float;
    AZIMUTH_RATE:float;
    ELEVATION:float;
    ELEVATION_UNC:float;
    ELEVATION_BIAS:float;
    ELEVATION_RATE:float;
    RANGE:float;
    RANGE_UNC:float;
    RANGE_BIAS:float;
    RANGE_RATE:float;
    RANGE_RATE_UNC:float;
    RA:float;
    RA_RATE:float;
    RA_UNC:float;
    RA_BIAS:float;
    DECLINATION:float;
    DECLINATION_RATE:float;
    DECLINATION_UNC:float;
    DECLINATION_BIAS:float;
    LOSX:float;
    LOSY:float;
    LOSZ:float;
    LOS_UNC:float;
    LOSXVEL:float;
    LOSYVEL:float;
    LOSZVEL:float;
    SENLAT:float;
    SENLON:float;
    SENALT:float;
    SENX:float;
    SENY:float;
    SENZ:float;
    FOV_COUNT:int;
    FOV_COUNT_UCTS:int;
    EXP_DURATION:float;
    ZEROPTD:float;
    NET_OBJ_SIG:float;
    NET_OBJ_SIG_UNC:float;
    MAG:float;
    MAG_UNC:float;
    MAG_NORM_RANGE:float;
    GEOLAT:float;
    GEOLON:float;
    GEOALT:float;
    GEORANGE:float;
    SKY_BKGRND:float;
    PRIMARY_EXTINCTION:float;
    PRIMARY_EXTINCTION_UNC:float;
    SOLAR_PHASE_ANGLE:float;
    SOLAR_EQ_PHASE_ANGLE:float;
    SOLAR_DEC_ANGLE:float;
    SHUTTER_DELAY:float;
    TIMING_BIAS:float;
    RAW_FILE_URI:string;
    INTENSITY:float;
    BG_INTENSITY:float;
    DESCRIPTOR:string;
    SOURCE:string;
    ORIGIN:string;
    DATA_MODE:byte;
    CREATED_AT:string;
    CREATED_BY:string;
  }
  table EOP {
    DATE:string;
    MJD:uint;
    X_POLE_WANDER_RADIANS:float;
    Y_POLE_WANDER_RADIANS:float;
    X_CELESTIAL_POLE_OFFSET_RADIANS:float;
    Y_CELESTIAL_POLE_OFFSET_RADIANS:float;
    UT1_MINUS_UTC_SECONDS:float;
    TAI_MINUS_UTC_SECONDS:ushort;
    LENGTH_OF_DAY_CORRECTION_SECONDS:float;
    DATA_TYPE:byte;
    SERIES:ubyte;
    IAU_CONVENTION:ubyte;
    X_POLE_WANDER_UNCERTAINTY_RADIANS:float;
    Y_POLE_WANDER_UNCERTAINTY_RADIANS:float;
    X_CELESTIAL_POLE_OFFSET_UNCERTAINTY_RADIANS:float;
    Y_CELESTIAL_POLE_OFFSET_UNCERTAINTY_RADIANS:float;
    UT1_MINUS_UTC_UNCERTAINTY_SECONDS:float;
    LENGTH_OF_DAY_UNCERTAINTY_SECONDS:float;
  }
  table EPF {
    EPF_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    RFL_ID:string;
    ACI_ID:string;
    VICTIM_ENDPOINT_ID:string;
    LIMIT_KIND:byte;
    LIMIT_MODEL_NAME:string;
    VALUE_UNITS:string;
    SAMPLE_COUNT:uint32;
  }
  table EPM {
    DN:string;
    LEGAL_NAME:string;
    FAMILY_NAME:string;
    GIVEN_NAME:string;
    ADDITIONAL_NAME:string;
    HONORIFIC_PREFIX:string;
    HONORIFIC_SUFFIX:string;
    JOB_TITLE:string;
    OCCUPATION:string;
  }
  table ESL {
    LINK_KEY:string;
    ENTITY_ID:string;
    ENTITY_RECORD_KEY:string;
    ENTITY_ROWID:double;
    RECORD_KEY:string;
    SCHEMA_NAME:string;
    RECORD_ROWID:double;
    CASCADE_DELETE:bool;
    UPDATED_AT_MS:double;
    RESERVED:[ubyte];
  }
  table ETM {
    ENTITY_ID:string;
    NAME:string;
    KIND:byte;
    SUBTYPE:string;
    PARENT_ENTITY_ID:string;
    WASM_HANDLE:uint;
    NORAD_CAT_ID:uint;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    CAT_OBJECT_NAME:string;
    CAT_OBJECT_ID:string;
    FACILITY_TYPE:string;
    SEARCH_TEXT:string;
    OWNER:string;
    STATUS_CODE:string;
    LAUNCH_DATE:string;
    LAUNCH_YEAR:string;
    ORBIT_REGIME:string;
    PERIOD:double;
    INCLINATION:double;
    APOGEE:double;
    PERIGEE:double;
    MEAN_MOTION:double;
    ECCENTRICITY:double;
    BSTAR:double;
    HAS_GP:bool;
    RESERVED:[ubyte];
  }
  table EWR {
    SYSTEM_ID:uint;
    ENTITY_ID:uint;
    ESM_ACTIVE:bool;
    ECM_ACTIVE:bool;
    RWR_ACTIVE:bool;
  }
  table FCS {
    MODE:ubyte;
    LEAD_METHOD:ubyte;
    RANGEFINDER_TYPE:ubyte;
    AMMO_SELECTED:ubyte;
    TARGET:string;
    SOLUTION:string;
    LAST_RANGE:double;
    RANGE_RATE:double;
    ROUNDS_REMAINING:ushort;
    TEMPERATURE:float;
    RESERVED:[ubyte];
  }
  table FPC {
    GRAPH_DEFINITION:ubyte;
  }
  table FRM {
    FRAME_TRANSFORM_REQUEST:ubyte;
  }
  table FSB {
    REQUEST_ID:ulong;
    KIND:ubyte;
    CHUNK_SEQUENCE:uint;
    FINAL:bool;
    TOTAL_BYTES:ulong;
    RECORD_COUNT:ulong;
    COLUMN_COUNT:uint;
    SCHEMA_NAME:string;
    FILE_IDENTIFIER:string;
    DATA:[ubyte];
    SHA256:[ubyte];
  }
  table FSM {
    MESSAGE_ID:string;
    PROVIDER_PEER_ID:string;
    LISTING_ID:string;
    STREAM_ID:string;
    SCHEMA_CODE:string;
    SCHEMA_HASH:[ubyte];
    POLICY_ID:string;
    POLICY_VERSION:uint32;
    KEY_EPOCH:string;
    SEQUENCE:uint64;
    PRODUCED_AT:uint64;
    EXPIRES_AT:uint64;
    SUBJECT_ID:string;
  }
  table FSO {
    OPERATION:ubyte;
    REQUEST_ID:ulong;
    DATABASE_NAME:string;
    SCHEMA_IDL:[ubyte];
  }
  table FSP {
    POLICY_ID:string;
    POLICY_VERSION:uint32;
    PROVIDER_PEER_ID:string;
    LISTING_ID:string;
    STREAM_ID:string;
    SCHEMA_CODE:string;
    SCHEMA_HASH:[ubyte];
  }
  table GDI {
    ID:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    IMAGE_TIME:string;
    FILENAME:string;
    FORMAT:byte;
    FILESIZE:long;
    CHECKSUM_VALUE:string;
    REGION_GEO_JSON:string;
    REGION_TEXT:string;
    REGION:string;
    REGION_TYPE:string;
    REGION_NDIMS:uint8;
    REGION_SRID:uint16;
    SUBJECT_ID:string;
    NAME:string;
    TRANSACTION_ID:string;
  }
  table GEL {
    GEL_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    EMITTER_ID:string;
    TECHNIQUE:byte;
    SOLUTION_EPOCH:double;
    LATITUDE_DEG:double;
    LONGITUDE_DEG:double;
    ALTITUDE_M:double;
  }
  table GEO {
    ID:string;
    ORIG_OBJECT_ID:string;
    SAT_NO:uint32;
    ON_ORBIT:string;
    STATION_KEEPING:byte;
    SS:double;
    SC:double;
    RELATIVE_ENERGY:double;
    LONGITUDE_RATE:double;
    LONGITUDE_MIN:double;
    LONGITUDE_MAX:double;
    CONFIDENCE:byte;
    TROUGH:byte;
    PLANE_CHANGE_STATUS:string;
    LOST_FLAG:bool;
    SEMI_ANNUAL_CORR_FLAG:bool;
    OBJECT_STATUS:string;
    INCLINATION:double;
    ECCENTRICITY:double;
    EPOCH:string;
    RAW_FILE_URI:string;
  }
  table GJN {
    FEATURES:ubyte;
  }
  table GNO {
    ID:string;
    RECEIVER_ID:string;
    RECEIVER_TYPE:string;
    ANTENNA_ID:string;
    ANTENNA_TYPE:string;
    FIRMWARE_VERSION:string;
    EPOCH:string;
    CLOCK_OFFSET:double;
    CLOCK_DRIFT:double;
    LATITUDE:double;
    LONGITUDE:double;
    ALTITUDE:double;
    APPROX_X:double;
    APPROX_Y:double;
    APPROX_Z:double;
    INTERVAL:double;
    NUM_SATS:uint;
    PDOP:double;
    HDOP:double;
    VDOP:double;
  }
  table GNP {
    ID:string;
    NAME:string;
    ASCII_NAME:string;
  }
  table GPX {
    VERSION:string;
    CREATOR:string;
    NAME:string;
    DESCRIPTION:string;
    AUTHOR_NAME:string;
    AUTHOR_EMAIL:string;
  }
  table GRV {
    MODEL_TYPE:byte;
    MODEL_NAME:byte;
    CENTRAL_BODY:byte;
    MAX_DEGREE:uint16;
    MAX_ORDER:uint16;
    INCLUDE_SUN:bool;
    INCLUDE_MOON:bool;
    INCLUDE_PLANETS:bool;
    SOLID_TIDES:bool;
    OCEAN_TIDES:bool;
    POLE_TIDES:bool;
    EQUATORIAL_RADIUS:double;
    J2:double;
    MU:double;
    J3:double;
    J4:double;
    J5:double;
    J6:double;
  }
  table GST {
    STATION_ID:string;
    NAME:string;
    NETWORK:ubyte;
    DOMES_NUMBER:string;
    CDP_NUMBER:string;
    FRAME_REALIZATION:ubyte;
    FRAME_REALIZATION_NAME:string;
    REFERENCE_EPOCH:string;
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    POSITION_SIGMA_X:double;
    POSITION_SIGMA_Y:double;
    POSITION_SIGMA_Z:double;
    ANTENNA_AXIS_TYPE:ubyte;
    AXIS_OFFSET_M:double;
    ECCENTRICITY_X:double;
    ECCENTRICITY_Y:double;
    ECCENTRICITY_Z:double;
    ECCENTRICITY_FRAME:string;
  }
  table GVH {
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    ATTITUDE_X:double;
    ATTITUDE_Y:double;
    ATTITUDE_Z:double;
    ATTITUDE_W:double;
    OMEGA_X:double;
    OMEGA_Y:double;
    OMEGA_Z:double;
    SPEED:float;
    HEADING:float;
    LATERAL_G:float;
    LONGITUDINAL_G:float;
    TURRET:string;
    DRIVETRAIN:string;
    SUSPENSION_LF:string;
    SUSPENSION_RF:string;
    SUSPENSION_LR:string;
    SUSPENSION_RR:string;
    VEHICLE_TYPE:ubyte;
    DRIVE_TYPE:ubyte;
    ENGINE_RUNNING:ubyte;
    LIGHTS:ubyte;
    FUEL_LEVEL:float;
  }
  table HEL {
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    QUAT_W:double;
    QUAT_X:double;
    QUAT_Y:double;
    QUAT_Z:double;
    OMEGA_BODY_X:double;
    OMEGA_BODY_Y:double;
    OMEGA_BODY_Z:double;
    MAIN_ROTOR:string;
    TAIL_ROTOR:string;
    ENGINE_N1:double;
    ENGINE_TORQUE:double;
    FLAGS:uint;
    FUEL_REMAINING:float;
  }
  table HFC {
    MESSAGE_ID:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    TIME_SYSTEM:string;
    REF_FRAME:string;
    START_TIME:string;
    STOP_TIME:string;
    STEP_SIZE:double;
  }
  table HYP {
    CAT_IDS:ubyte;
  }
  table IDM {
    ID:string;
    NAME:string;
    DATA_MODE:byte;
  }
  table ION {
    ID:string;
    SOURCE:byte;
    STATION_ID:string;
    STATION_NAME:string;
    LATITUDE:double;
    LONGITUDE:double;
    ALTITUDE:double;
    START_TIME:string;
    STOP_TIME:string;
    FOF2:double;
    FOF1:double;
    FOE:double;
    FOES:double;
    HMF2:double;
    HMF1:double;
    HME:double;
    NMF2:double;
    VTEC:double;
    STEC:double;
    S4:double;
  }
  table IQC {
    ID:string;
    CAPTURE_ID:string;
    SOURCE_NAME:string;
    SOURCE_URL:string;
    SOURCE_RECORD_ID:string;
    SOURCE_SHA256:string;
    RETRIEVED_AT:string;
    TITLE:string;
    DESCRIPTION:string;
    AUTHOR:string;
    SIGMF_VERSION:string;
    COLLECTION:string;
  }
  table IRM {
    JOB_ID:string;
    SEQUENCE:ulong;
    PROVIDER_ID:string;
    INGESTOR_ID:string;
  }
  table IRO {
    ID:string;
    ID_ENTITY:string;
    NAME:string;
    DESCRIPTION:string;
    ENTITY:string;
    EPOCH:string;
    SENSOR_ID:string;
    SAT_NO:uint32;
    OBJECT_DESIGNATOR:string;
    BAND:byte;
    DETECTION_TYPE:byte;
    RA:double;
    DEC:double;
    RA_UNC:double;
    DEC_UNC:double;
    AZIMUTH:double;
    ELEVATION:double;
    RANGE:double;
    IRRADIANCE:double;
    IRRADIANCE_UNC:double;
    IR_MAG:double;
    MAG_UNC:double;
    TEMPERATURE:double;
    INTEGRATION_TIME:double;
    BACKGROUND:double;
    SNR:double;
  }
  table KML {
    NAME:string;
    DESCRIPTION:string;
    VISIBILITY:bool;
    OPEN:bool;
  }
  table KRF {
    KEY_ID:string;
    SLOT_ID:string;
    ROLE:byte;
    ALGORITHM:byte;
    PUBLIC_KEY:[ubyte];
    VERSION:uint32;
    EXPIRES_AT:uint64;
    HOST_MANAGED:bool;
  }
  table LAM {
    MESSAGE_ID:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    MISSION_NAME:string;
    VEHICLE_NAME:string;
    TIME_SYSTEM:string;
    REF_FRAME:string;
    LAUNCH_EPOCH:string;
    START_TIME:string;
    STOP_TIME:string;
    STEP_SIZE:double;
  }
  table LCC {
    OWNER:byte;
  }
  table LCF {
    MESSAGE_TYPE:byte;
    ROLE:byte;
    PROVIDER_PEER_ID:string;
  }
  table LCH {
    MESSAGE_TYPE:byte;
    ROLE:byte;
    REQUEST_ID:string;
    MODULE_ID:string;
    MODULE_VERSION:string;
    REQUESTER_PEER_ID:string;
    REQUESTER_XPUB:string;
    REQUESTER_SIGNING_PUBKEY:[ubyte];
    REQUESTER_EPHEMERAL_PUBKEY:[ubyte];
    REQUESTED_DOMAIN:string;
    REQUESTED_TIMEOUT_MS:uint64;
    REQUESTED_AT:uint64;
    CHALLENGE_NONCE:[ubyte];
    EXPIRES_AT:uint64;
    PROVIDER_PEER_ID:string;
    ERROR_CODE:string;
    ERROR_MESSAGE:string;
    REQUESTER_EPM:[ubyte];
  }
  table LDM {
    SITE:ubyte;
  }
  table LGR {
    MESSAGE_TYPE:byte;
    REQUEST_ID:string;
    MODULE_ID:string;
    MODULE_VERSION:string;
    REQUESTER_PEER_ID:string;
    REQUESTER_XPUB:string;
    REQUESTED_DOMAIN:string;
    REQUESTED_TIMEOUT_MS:uint64;
    GRANTED_DOMAIN:string;
    GRANTED_TIMEOUT_MS:uint64;
    EXPIRES_AT:uint64;
    REQUIRED_SCOPE:string;
    GRANT_STATUS:string;
    DENIAL_REASON:string;
    CAPABILITY_TOKEN:[ubyte];
  }
  table LKS {
    ID:string;
    ID_ON_ORBIT1:string;
    SAT_NO1:uint32;
    ID_ON_ORBIT2:string;
    SAT_NO2:uint32;
    CONSTELLATION:string;
    LINK_NAME:string;
    LINK_TYPE:byte;
    LINK_STATE:byte;
    BAND:string;
    LINK_START_TIME:string;
    LINK_STOP_TIME:string;
    ID_BEAM1:string;
    END_POINT1_NAME:string;
    END_POINT1_LAT:double;
    END_POINT1_LON:double;
    ID_BEAM2:string;
    END_POINT2_NAME:string;
    END_POINT2_LAT:double;
    END_POINT2_LON:double;
    DATA_RATE1_TO2:double;
    DATA_RATE2_TO1:double;
    SYS_CAP:string;
    OPS_CAP:string;
  }
  table LMO {
    REQUEST_ID:string;
    STATUS:byte;
    ERROR_CODE:string;
    ERROR_MESSAGE:string;
  }
  table LMR {
    ACTION:byte;
    REQUEST_ID:string;
    MODULE_ID:string;
    MODULE_VERSION:string;
    WASM_CID:string;
    MODULE_HASH:[ubyte];
    STATUS:string;
    ERROR_CODE:string;
    ERROR_MESSAGE:string;
  }
  table LMS {
    REQUEST_ID:string;
    R1_X:double;
    R1_Y:double;
    R1_Z:double;
    R2_X:double;
    R2_Y:double;
    R2_Z:double;
    TOF_SEC:double;
    MU_KM3_S2:double;
    TRANSFER_WAY:byte;
    MAX_REVS:uint16;
    REF_FRAME:string;
    EPOCH:string;
    FLAGS:uint16;
  }
  table LND {
    ID:string;
    EVENT_ID:string;
    DETECTION_TYPE:byte;
    MESSAGE_TYPE:string;
    LAUNCH_TIME:string;
    LAUNCH_LATITUDE:double;
    LAUNCH_LONGITUDE:double;
    LAUNCH_AZIMUTH:double;
    RAAN:double;
    INCLINATION:double;
    OBSERVATION_TIME:string;
    OBSERVATION_LATITUDE:double;
    OBSERVATION_LONGITUDE:double;
    OBSERVATION_ALTITUDE:double;
    STEREO_FLAG:bool;
    HIGH_ZENITH_AZIMUTH:bool;
    SEQUENCE_NUMBER:uint16;
    LAUNCH_SITE_ID:string;
    LAUNCH_VEHICLE:string;
    TRAJECTORY_TYPE:string;
    CONFIDENCE:double;
    DESCRIPTOR:string;
  }
  table LNE {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    DERIVED_FROM:string;
    DECLASSIFICATION_DATE:string;
    DECLASSIFICATION_STRING:string;
    MSG_CREATE_DATE:string;
    LAUNCH_DATE:string;
    OUTCOME:byte;
    LAUNCH_FAILURE_CODE:string;
    BE_NUMBER:string;
    O_SUFFIX:string;
    LAUNCH_FACILITY_NAME:string;
    LAUNCH_FACILITY_CODE:string;
    LAUNCH_VEHICLE:string;
    LAUNCH_VEHICLE_CONFIG:string;
    TARGET_ORBIT:string;
    OBJECTS_ON_ORBIT:uint16;
    ON_ORBIT:string;
    LAUNCH_COUNTRY:string;
    MISSION_NAME:string;
    REMARKS:string;
  }
  table LPF {
    MESSAGE_TYPE:byte;
    REQUEST_ID:string;
    MODULE_ID:string;
    MODULE_VERSION:string;
    REQUESTER_PEER_ID:string;
    REQUESTER_XPUB:string;
    REQUESTED_DOMAIN:string;
    REQUESTED_TIMEOUT_MS:uint64;
    REQUESTER_EPHEMERAL_PUBKEY:[ubyte];
    CHALLENGE_NONCE:[ubyte];
    CHALLENGE_EXPIRES_AT:uint64;
    PROVIDER_PEER_ID:string;
    SIGNATURE:[ubyte];
    SIGNING_PUBKEY:[ubyte];
    TIMESTAMP_MS:uint64;
    REJECTION_CODE:string;
    REJECTION_MESSAGE:string;
  }
  table LWK {
    REQUEST_ID:string;
    MODULE_ID:string;
    MODULE_VERSION:string;
    CONTENT_KEY_ID:string;
    RECIPIENT_KEY_ID:string;
    ALGORITHM:byte;
    REQUESTER_EPHEMERAL_PUBKEY:[ubyte];
    PROVIDER_EPHEMERAL_PUBKEY:[ubyte];
    HKDF_SALT:[ubyte];
    IV:[ubyte];
    CIPHERTEXT:[ubyte];
    TAG:[ubyte];
    EXPIRES_AT:uint64;
  }
  table MBL {
    bundle_version:uint16;
    module_format:string;
  }
  table MDP {
    PROBLEM_ID:string;
    NAME:string;
  }
  table MDS {
    SOLUTION_SET_ID:string;
    PROBLEM_ID:string;
  }
  table MET {
    MEAN_ELEMENT_THEORY:byte;
  }
  table MFE {
    ID:string;
    TMP_SAT_NO:int;
    EPOCH:string;
    MEAN_MOTION:double;
    ECCENTRICITY:double;
    INCLINATION:double;
    RAAN:double;
    ARG_OF_PERIGEE:double;
    MEAN_ANOMALY:double;
    REV_NO:int;
    B_STAR:double;
    MEAN_MOTION_DOT:double;
    MEAN_MOTION_DDOT:double;
    SEMI_MAJOR_AXIS:double;
    PERIOD:double;
    APOGEE:double;
    PERIGEE:double;
    LINE1:string;
    LINE2:string;
  }
  table MNF {
    ID:string;
    SAT_NO:uint32;
    OBJECT_DESIGNATOR:string;
    STATUS:byte;
    EVENT_EPOCH:string;
    SOURCE:string;
    REF_FRAME:string;
    ORIG_SEMI_MAJOR_AXIS:double;
    ORIG_ECCENTRICITY:double;
    ORIG_INCLINATION:double;
    DELTA_V_MIN:double;
    DELTA_V_MAX:double;
    DELTA_V_STEP:double;
    DELTA_T_MIN:double;
    DELTA_T_MAX:double;
    DELTA_T_STEP:double;
    NUM_ELEMENTS:uint;
  }
  table MNV {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    STATUS:byte;
    CHARACTERIZATION:byte;
    CHARACTERIZATION_UNC:double;
    REPORT_TIME:string;
    EVENT_START_TIME:string;
    EVENT_END_TIME:string;
    TOTAL_BURN_TIME:double;
    OD_FIT_END_TIME:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    EVENT_ID:string;
    UCT:bool;
    MANEUVER_UNC:double;
    DELTA_VEL:double;
    DELTA_VEL_U:double;
    DELTA_VEL_V:double;
    DELTA_VEL_W:double;
    DELTA_POS:double;
    DELTA_POS_U:double;
    DELTA_POS_V:double;
    DELTA_POS_W:double;
    DELTA_MASS:double;
  }
  table MPE {
    ENTITY_ID:string;
    EPOCH:double;
    MEAN_MOTION:double;
    ECCENTRICITY:double;
    INCLINATION:double;
    RA_OF_ASC_NODE:double;
    ARG_OF_PERICENTER:double;
    MEAN_ANOMALY:double;
    BSTAR:double;
    MEAN_ELEMENT_THEORY:byte;
  }
  table MSL {
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    ATTITUDE_X:double;
    ATTITUDE_Y:double;
    ATTITUDE_Z:double;
    ATTITUDE_W:double;
    OMEGA_X:double;
    OMEGA_Y:double;
    OMEGA_Z:double;
    MASS:double;
    MASS_INITIAL:double;
    TARGET_POSITION_X:double;
    TARGET_POSITION_Y:double;
    TARGET_POSITION_Z:double;
    TARGET_VELOCITY_X:double;
    TARGET_VELOCITY_Y:double;
    TARGET_VELOCITY_Z:double;
    MISS_DISTANCE:double;
    SEEKER:string;
    MOTOR:string;
    GUIDANCE_CMD:string;
    PHASE:ubyte;
    GUIDANCE_LAW:ubyte;
    TYPE:ubyte;
    ARMED:ubyte;
    TIME_OF_FLIGHT:float;
    MAX_G:float;
    RESERVED:[ubyte];
  }
  table MST {
    ID:string;
    MSG_TYPE:string;
    MSG_SUB_TYPE:string;
    MSG_CREATE_DATE:string;
    ENVIRONMENT:byte;
    OBJ_TYPE:string;
    OBJ_TYPE_CONF:uint8;
    OBJ_PLAT:string;
    OBJ_IDENT:string;
    SPACE_AMP:string;
    SPACE_AMP_CONF:uint8;
    OBJ_ACT:string;
    SPACE_SPEC_TYPE:string;
    ACFT_SUB_TYPE:string;
    NAME:string;
    CALL_SIGN:string;
    LOST_TRK_IND:bool;
    TRACK_ID:string;
    PARENT_TRACK_ID:string;
    MUID_SRC_TRK:string;
    MUID_SRC:string;
    ALERT:string;
    MSL_STATUS:byte;
    TS:string;
    AOU_RPT_TYPE:byte;
    CONTAINMENT:double;
    TRK_CONF:double;
    TRK_QUAL:uint8;
    ANG_ELEV:double;
    SEN_MODE:string;
    INFO_SOURCE:string;
    BOOSTING:bool;
    POLAR_SING_LOC_LAT:double;
    POLAR_SING_LOC_LON:double;
    EMG_IND:bool;
    DROP_PT_IND:bool;
    LAUNCH_TIME:string;
    LAUNCH_LAT:double;
    LAUNCH_LON:double;
    AZ_CORR:double;
    BURNOUT_ALT:double;
    LAUNCH_AOU_TYPE:byte;
    IMPACT_TIME:string;
    IMPACT_LAT:double;
    IMPACT_LON:double;
    IMPACT_AOU_TYPE:byte;
    VECTOR_START_TIME:string;
    VECTOR_STEP_SIZE:double;
    VECTOR_COMPONENTS:uint8;
  }
  table MTI {
    ID:string;
    STANDARD:byte;
    P3:string;
    P6:string;
    P7:string;
    P8:string;
    P9:uint32;
    P10:uint16;
  }
  table NAV {
    POSITION_X:double;
    POSITION_Y:double;
    POSITION_Z:double;
    VELOCITY_X:double;
    VELOCITY_Y:double;
    VELOCITY_Z:double;
    ATTITUDE_X:double;
    ATTITUDE_Y:double;
    ATTITUDE_Z:double;
    ATTITUDE_W:double;
    OMEGA_X:double;
    OMEGA_Y:double;
    OMEGA_Z:double;
    SPEED_KNOTS:float;
    HEADING:float;
    COURSE:float;
    RUDDER_ANGLE:float;
    HULL:string;
    PROPULSION:string;
    DC_STATE:ubyte;
    FIRES_ACTIVE:ubyte;
    FLOODING_ACTIVE:ubyte;
    CREW_CASUALTIES:ubyte;
    HULL_INTEGRITY:float;
    POWER_AVAILABLE:float;
    WEAPONS_ONLINE:ubyte;
    SENSORS_ONLINE:ubyte;
    RESERVED1:ushort;
    FUEL_REMAINING:float;
    AMMO_MAIN:ushort;
    MISSILES_REMAINING:ubyte;
    TORPEDOES_REMAINING:ubyte;
    VESSEL_TYPE:ubyte;
    PROPULSION_TYPE:ubyte;
    RESERVED:[ubyte];
  }
  table NUM {
    ROOT_SOLVE_REQUEST:ubyte;
  }
  table OBD {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    START_TIME:string;
    END_TIME:string;
    METHOD:byte;
    METHOD_SOURCE:string;
    INITIAL_OD:bool;
    APRIORI_ID_ELSET:string;
    APRIORI_ELSET:string;
    APRIORI_ID_STATE_VECTOR:string;
    APRIORI_STATE_VECTOR:string;
    LAST_OB_START:string;
    LAST_OB_END:string;
    TIME_SPAN:double;
    FIT_SPAN:double;
    EFFECTIVE_FROM:string;
    EFFECTIVE_UNTIL:string;
    WRMS:double;
    PREVIOUS_WRMS:double;
    FIRST_PASS_WRMS:double;
    BEST_PASS_WRMS:double;
    ERROR_GROWTH_RATE:double;
    EDR:double;
    BALLISTIC_COEFF_EST:bool;
    BALLISTIC_COEFF_MODEL:string;
    AGOM_EST:bool;
    AGOM_MODEL:string;
    RMS_CONVERGENCE_CRITERIA:double;
    NUM_ITERATIONS:uint16;
    NUM_ACCEPTED_OBS:uint32;
    NUM_REJECTED_OBS:uint32;
  }
  table OBT {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    TS:string;
    LAT:double;
    LON:double;
    ALT:double;
    SPD:double;
    ANG_ELEV:double;
    RDF_RF:double;
    CALL_SIGN:string;
    RPT_NUM:string;
    TRK_ID:string;
    OBJ_IDENT:string;
    IDENT_AMP:string;
    SAT_STATUS:string;
    OBJ_TYPE:byte;
    COUNTRY_CODE:string;
    DECAY:double;
    CHARLIE_LINE:string;
    AOU_TYPE:byte;
  }
  table OCM {
    HEADER:ubyte;
  }
  table OEM {
    CLASSIFICATION:string;
    CCSDS_OEM_VERS:double;
    CREATION_DATE:string;
    ORIGINATOR:string;
  }
  table OOA {
    ID:string;
    ID_ON_ORBIT:string;
    ID_ANTENNA:string;
    NAME:string;
    ANTENNA_TYPE:string;
    QUANTITY:uint;
    BAND:string;
    FREQ_MIN:double;
    FREQ_MAX:double;
    GAIN:double;
    APERTURE:double;
    BEAMWIDTH:double;
    POLARIZATION:string;
    STEERABLE:bool;
    SLEW_RATE:double;
    PURPOSE:string;
    NOTES:string;
  }
  table OOB {
    ID:string;
    ID_ON_ORBIT:string;
    ID_BATTERY:string;
    NAME:string;
    CHEMISTRY:string;
    QUANTITY:uint;
    VOLTAGE:double;
    CAPACITY_AH:double;
    ENERGY_WH:double;
    MAX_DOD:double;
    CYCLE_LIFE:uint;
    MASS:double;
    STATE_OF_HEALTH:double;
    NOTES:string;
  }
  table OOD {
    ID:string;
    LAST_OB_TIME:string;
    VISMAG:double;
    VISMAG_MIN:double;
    VISMAG_MAX:double;
    VISMAG_MEAN:double;
    RCS:double;
    RCS_MIN:double;
    RCS_MAX:double;
    RCS_MEAN:double;
    BOL_DELTA_V:double;
    MAX_DELTA_V:double;
    DELTA_VUNC:double;
    EST_DELTA_VDURATION:double;
    NUM_MISSION:int;
  }
  table OOE {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    DERIVED_FROM:string;
    DECLASSIFICATION_DATE:string;
    DECLASSIFICATION_STRING:string;
    EVENT_TIME:string;
    EVENT_TIME_NOTES:string;
    CATEGORY:byte;
    RESULT:byte;
    EVENT_TYPE:string;
    OPERATOR_ORG_ID:string;
    OWNER_ORG_ID:string;
    LESSEE_ORG_ID:string;
    OPERATED_ON_BEHALF_OF_ORG_ID:string;
    GEO_POSITION:double;
    PLANE_SLOT:string;
    PLANE_NUMBER:string;
    POSITION_STATUS:string;
    UNTIL_TIME:string;
    OFFICIAL_LOSS_DATE:string;
    NET_AMOUNT:double;
    UNDERLYING_CAUSE:string;
    CAPABILITY_LOSS:double;
    CAPACITY_LOSS:double;
    INSURANCE_LOSS:double;
    THIRD_PARTY_INSURANCE_LOSS:double;
    INJURED:uint16;
    KILLED:uint16;
    AGE_AT_EVENT:double;
    LIFE_LOST:double;
    ACHIEVED_FLIGHT_PHASE:string;
    OCCURRENCE_FLIGHT_PHASE:string;
    STAGE_AT_FAULT:string;
    EQUIPMENT_AT_FAULT:string;
    EQUIPMENT_TYPE_AT_FAULT:string;
    EQUIPMENT_PART_AT_FAULT:string;
    CONSEQUENTIAL_EQUIPMENT_FAILURE:string;
    INCLINED:bool;
    DESCRIPTION:string;
    REMARKS:string;
    OBJECT_STATUS:string;
    SATELLITE_POSITION:string;
    ON_ORBIT:string;
  }
  table OOI {
    ID:string;
    SAT_NO:uint32;
    NAME:string;
    ON_ORBIT:string;
    STATUS:byte;
    STATUS_DATE:string;
    PRIORITY:byte;
    DESCRIPTION:string;
    SENSOR_TASKING_START_TIME:string;
    SENSOR_TASKING_STOP_TIME:string;
    LAST_OB_TIME:string;
    MISSED_OB_TIME:string;
    SV_EPOCH:string;
    X:double;
    Y:double;
    Z:double;
    XVEL:double;
    YVEL:double;
    ZVEL:double;
    ELSET_EPOCH:string;
    MEAN_MOTION:double;
    ECCENTRICITY:double;
    INCLINATION:double;
    RAAN:double;
    ARG_OF_PERIGEE:double;
    MEAN_ANOMALY:double;
    REV_NO:uint32;
    B_STAR:double;
    MEAN_MOTION_DOT:double;
    MEAN_MOTION_DDOT:double;
    SEMI_MAJOR_AXIS:double;
    PERIOD:double;
    APOGEE:double;
    PERIGEE:double;
  }
  table OOL {
    ID:string;
    NAME:string;
    DESCRIPTION:string;
  }
  table OON {
    SAT_NO:int;
    COMMON_NAME:string;
    CONSTELLATION:string;
    INTL_DES:string;
    LAUNCH_DATE:string;
    DECAY_DATE:string;
    OBJECT_TYPE:string;
    MISSION_NUMBER:string;
    CATEGORY:string;
    LIFETIME_YEARS:int;
    ALT_NAME:string;
    LAUNCH_SITE_ID:string;
  }
  table OOS {
    ID:string;
    ID_ON_ORBIT:string;
    ID_SOLAR_ARRAY:string;
    NAME:string;
    CELL_TYPE:string;
    QUANTITY:uint;
    AREA:double;
    POWER_BOL:double;
    POWER_EOL:double;
    EFFICIENCY:double;
    DEGRADATION_RATE:double;
    NUM_PANELS:uint;
    DEPLOYABLE:bool;
    TRACKING:bool;
    MASS:double;
    NOTES:string;
  }
  table OOT {
    ID:string;
    ID_ON_ORBIT:string;
    ID_THRUSTER:string;
    NAME:string;
    TYPE:byte;
    QUANTITY:uint;
    THRUST:double;
    ISP:double;
    PROPELLANT:string;
    PROPELLANT_MASS:double;
    PROPELLANT_REMAINING:double;
    DELTA_V_TOTAL:double;
    DELTA_V_REMAINING:double;
    TOTAL_IMPULSE:double;
    MASS:double;
    PURPOSE:string;
    NOTES:string;
  }
  table OPM {
    CCSDS_OPM_VERS:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    CENTER_NAME:string;
    REF_FRAME:string;
    TIME_SYSTEM:string;
    EPOCH:string;
    X:double;
    Y:double;
    Z:double;
    X_DOT:double;
    Y_DOT:double;
    Z_DOT:double;
    SEMI_MAJOR_AXIS:double;
    ECCENTRICITY:double;
    INCLINATION:double;
    RA_OF_ASC_NODE:double;
    ARG_OF_PERICENTER:double;
    TRUE_ANOMALY:double;
    MEAN_ANOMALY:double;
    GM:double;
    MASS:double;
    SOLAR_RAD_AREA:double;
    SOLAR_RAD_COEFF:double;
    DRAG_AREA:double;
    DRAG_COEFF:double;
  }
  table OPP {
    ID:string;
    VERSION:string;
    NORAD_CAT_ID:uint;
    OBJECT_ID:string;
    OBJECT_NAME:string;
    ENTITY_ID:string;
    BUS_ID:string;
    BUS_FAMILY:string;
  }
  table OSM {
    IS_STABLE:bool;
    NUM_OBS:int;
    OBJECT_ID:string;
    ID_SENSOR:string;
    PASS_START:string;
    PASS_DURATION:int;
  }
  table PAP {
    PAP_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    RFE_ID:string;
    BEM_ID:string;
    HOP_SCHEDULE_ID:string;
    GEOMETRY:byte;
  }
  table PCF {
    STEP_SIZE:double;
    TOLERANCE:double;
    MIN_STEP:double;
    MAX_STEP:double;
    MAX_ITERATIONS:uint;
    GRAVITY_DEGREE:ushort;
    GRAVITY_ORDER:ushort;
    INTEGRATOR:ubyte;
    OUTPUT_FRAME:ubyte;
    FORCE_FLAGS:ushort;
    DRAG_COEFFICIENT:float;
    SRP_COEFFICIENT:float;
    AREA_MASS_RATIO:float;
    RESERVED:[ubyte];
  }
  table PGM {
    GROUP_NAME:string;
    DESCRIPTION:string;
    DEFAULT_TRUST_LEVEL:byte;
  }
  table PGR {
    TIMESTAMP:string;
    LOCAL_PEER_ID:string;
  }
  table PHY {
    COMMAND:string;
    SIMULATION_STEP:string;
    RIGID_BODY:string;
    INTEGRATION_CONFIG:string;
    COLLISION_QUERY_A:string;
    COLLISION_QUERY_B:string;
    TRANSFORM_A:string;
    TRANSFORM_B:string;
    POSITION_A:string;
    POSITION_B:string;
    FLUID:string;
    AERO_QUERY:string;
    DRAG_MODEL:string;
    THERMAL_STATE:string;
  }
  table PIV {
    REQUEST:ubyte;
  }
  table PKB {
    BROKER_ID:string;
    PUBLISHER_EPM_CID:string;
    PROVIDER_PEER_ID:string;
    PROTOCOL_ID:string;
  }
  table PLD {
    PAYLOAD_DURATION:string;
    MASS_AT_LAUNCH:float;
    DIMENSIONS:string;
    SOLAR_ARRAY_AREA:float;
    SOLAR_ARRAY_DIMENSIONS:string;
    NOMINAL_OPERATIONAL_LIFETIME:string;
  }
  table PLG {
    PLUGIN_ID:string;
    NAME:string;
    VERSION:string;
    DESCRIPTION:string;
    TAGLINE:string;
    PLUGIN_TYPE:byte;
    PUBLISHER_NAME:string;
    PUBLISHER_HANDLE:string;
    PUBLISHER_URL:string;
    SUPPORT_URL:string;
  }
  table PLHD {
    SCHEMA_TYPE:string;
    PUBLISHER_PEER_ID:string;
    HEAD_SEQUENCE:uint64;
    HEAD_ENTRY_HASH:string;
    RECORD_COUNT:uint64;
    MULTIFORMAT_ADDRESS:string;
    TIMESTAMP:uint64;
    SIGNATURE:[ubyte];
    SIGNATURE_TYPE:string;
    OLDEST_EPOCH_DAY:string;
    NEWEST_EPOCH_DAY:string;
  }
  table PLK {
    LICENSE_ID:string;
    PLUGIN_ID:string;
    PLUGIN_VERSION:string;
    LICENSEE_ORG:string;
    LICENSEE_EMAIL:string;
    LICENSEE_PEER_ID:string;
    LICENSEE_PUBKEY:[ubyte];
    ISSUER_PUBKEY:[ubyte];
  }
  table PLOG {
    SEQUENCE:uint64;
    SCHEMA_TYPE:string;
    PUBLISHER_PEER_ID:string;
    RECORD_CID:string;
    PREVIOUS_ENTRY_HASH:string;
    ENTRY_HASH:string;
    TIMESTAMP:uint64;
    SIGNATURE:[ubyte];
    SIGNATURE_TYPE:string;
  }
  table PMM {
    PROVIDER_DOMAIN:string;
    PROVIDER_NAME:string;
    DESCRIPTION:string;
    EPOCH:uint64;
  }
  table PNL {
    OBJECT_ID:string;
    OBJECT_NAME:string;
    NORAD_CAT_ID:uint32;
    BODY_FRAME:string;
    TOTAL_MASS_KG:double;
    EPOCH:string;
  }
  table PNM {
    MULTIFORMAT_ADDRESS:string;
    PUBLISH_TIMESTAMP:string;
    CID:string;
    FILE_NAME:string;
    FILE_ID:string;
    SIGNATURE:string;
    TIMESTAMP_SIGNATURE:string;
    SIGNATURE_TYPE:string;
    TIMESTAMP_SIGNATURE_TYPE:string;
  }
  table PPE {
    COMMENT:ubyte;
  }
  table PRG {
    NAME:string;
    HD_KEY_PATH:string;
  }
  table PRR {
    PEER_ID:string;
  }
  table PRW {
    INIT:ubyte;
  }
  table PUR {
    REQUEST_ID:string;
    LISTING_ID:string;
    TIER_NAME:string;
    BUYER_PEER_ID:string;
    BUYER_ENCRYPTION_PUBKEY:[ubyte];
    PAYMENT_METHOD:byte;
    PAYMENT_AMOUNT:uint64;
    PAYMENT_CURRENCY:string;
    PAYMENT_TX_HASH:string;
    PAYMENT_CHAIN:string;
    PAYMENT_REFERENCE:string;
    BUYER_SIGNATURE:[ubyte];
    TIMESTAMP:uint64;
    KEY_ALGORITHM:string;
    BUYER_EMAIL:string;
    SENDER_ADDRESS:string;
    CONFIRMATION_BLOCK:uint64;
    PAYMENT_INTENT_ID:string;
    CREDITS_TRANSACTION_ID:string;
    STATUS:byte;
    STATUS_MESSAGE:string;
    CREATED_AT:uint64;
    UPDATED_AT:uint64;
    PAYMENT_DEADLINE:uint64;
    PAYMENT_CONFIRMED_AT:uint64;
    GRANT_ISSUED_AT:uint64;
    GRANT_ID:string;
    PROVIDER_PEER_ID:string;
    PROVIDER_ACKNOWLEDGED_AT:uint64;
    PREFERRED_DELIVERY_METHOD:string;
    WEBHOOK_URL:string;
    PROVIDER_SIGNATURE:[ubyte];
  }
  table QEM {
    MODEL_ID:string;
    MODEL_VERSION:string;
    MODEL_WEIGHTS_SHA256:string;
    POOLING_METHOD:byte;
    TEMPLATE_VERSION:string;
    DIMENSIONS:uint32;
    ENCODING:byte;
    NORMALIZATION:byte;
    VOCAB_SIZE:uint32;
  }
  table RAF {
    PDU_TYPE:byte;
    INITIATOR_ID:string;
    RESPONDER_PORT_ID:string;
    SERVICE_TYPE:ubyte;
    VERSION:ushort;
    INVOKE_ID:uint;
    FRAME_QUALITY:ubyte;
    DATA:[ubyte];
  }
  table RBK {
    RIGID_BODY_REQUEST:ubyte;
  }
  table RCF {
    PDU_TYPE:byte;
    INITIATOR_ID:string;
    RESPONDER_PORT_ID:string;
    SERVICE_TYPE:ubyte;
    VERSION:ushort;
    INVOKE_ID:uint;
    SPACECRAFT_ID:ushort;
    VIRTUAL_CHANNEL_ID:ubyte;
    DATA:[ubyte];
  }
  table RDM {
    CCSDS_RDM_VERS:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    NORAD_CAT_ID:uint32;
    OBJECT_TYPE:string;
    DISPOSITION:byte;
    REASON:byte;
    REENTRY_EPOCH:string;
    REENTRY_EPOCH_UNC:double;
    REENTRY_LATITUDE:double;
    REENTRY_LONGITUDE:double;
    REENTRY_ALTITUDE:double;
    TIME_SYSTEM:string;
    PREV_PREDICTION_EPOCH:string;
    BALLISTIC_COEFF:double;
    MASS:double;
    SOLAR_RAD_AREA:double;
    DRAG_AREA:double;
  }
  table RDO {
    ID:string;
    OB_TIME:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    UCT:bool;
    OBS_TYPE:byte;
    TASK_ID:string;
    TRANSACTION_ID:string;
    TRACK_ID:string;
    OB_POSITION:string;
    SEN_REFERENCE_FRAME:string;
    AZIMUTH:double;
    AZIMUTH_UNC:double;
    AZIMUTH_BIAS:double;
    AZIMUTH_RATE:double;
    ELEVATION:double;
    ELEVATION_UNC:double;
    ELEVATION_BIAS:double;
    ELEVATION_RATE:double;
    RANGE:double;
    RANGE_UNC:double;
    RANGE_BIAS:double;
    RANGE_RATE:double;
    RANGE_RATE_UNC:double;
    RANGE_ACCEL:double;
    RANGE_ACCEL_UNC:double;
    DOPPLER:double;
    DOPPLER_UNC:double;
    RA:double;
    DECLINATION:double;
    X:double;
    Y:double;
    Z:double;
    XVEL:double;
    YVEL:double;
    ZVEL:double;
    SENX:double;
    SENY:double;
    SENZ:double;
    RCS:double;
    RCS_UNC:double;
    ORTHOGONAL_RCS:double;
    ORTHOGONAL_RCS_UNC:double;
    SNR:double;
    BEAM:double;
    TIMING_BIAS:double;
    RAW_FILE_URI:string;
    DESCRIPTOR:string;
  }
  table REC {
    version:string;
  }
  table REM {
    MESSAGE_ID:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    NORAD_CAT_ID:uint;
    TIME_SYSTEM:string;
    REF_FRAME:string;
    START_TIME:string;
    STOP_TIME:string;
    STEP_SIZE:double;
  }
  table REV {
    REVIEW_ID:string;
    LISTING_ID:string;
    REVIEWER_PEER_ID:string;
    RATING:uint8;
    TITLE:string;
    CONTENT:string;
    ACL_GRANT_ID:string;
    TIMESTAMP:uint64;
    REVIEWER_SIGNATURE:[ubyte];
  }
  table RFB {
    ID:string;
    ID_ENTITY:string;
    NAME:string;
    BAND:byte;
    MODE:string;
    PURPOSE:string;
    FREQ_MIN:double;
    FREQ_MAX:double;
    CENTER_FREQ:double;
    BANDWIDTH:double;
    PEAK_GAIN:double;
    EDGE_GAIN:double;
    BEAMWIDTH:double;
    POLARIZATION:byte;
    ERP:double;
    EIRP:double;
    NORAD_CAT_ID:uint;
    ID_TRANSMITTER:string;
    LINK_DIRECTION:byte;
    BAUD:double;
    SERVICE:string;
    XMT_STATUS:byte;
    INVERT:bool;
    IARU_COORDINATION:string;
    CITATION:string;
  }
  table RFE {
    ID:string;
    ID_ENTITY:string;
    NAME:string;
    TYPE:byte;
    ENTITY:string;
    ELNOT:string;
    NATO_NAME:string;
    PLATFORM_TYPE:string;
    COUNTRY:string;
    FUNCTION:string;
    BAND:string;
    FREQ_MIN:double;
    FREQ_MAX:double;
    PEAK_POWER:double;
    AVG_POWER:double;
    ANTENNA_GAIN:double;
    NUM_MODES:uint;
  }
  table RFL {
    RFL_ID:string;
    NAME:string;
    SCENARIO_ID:string;
  }
  table RFM {
    REFERENCE_FRAME_type:ubyte;
  }
  table RFO {
    ID:string;
    OB_TIME:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    OBS_TYPE:byte;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    UCT:bool;
    TASK_ID:string;
    TRANSACTION_ID:string;
    TRACK_ID:string;
    TRANSPONDER:string;
    DETECTION_STATUS:byte;
    AZIMUTH:double;
    AZIMUTH_UNC:double;
    AZIMUTH_RATE:double;
    ELEVATION:double;
    ELEVATION_UNC:double;
    ELEVATION_RATE:double;
    RANGE:double;
    RANGE_UNC:double;
    RANGE_RATE:double;
    RANGE_RATE_UNC:double;
    TRACK_RANGE:double;
    SENLAT:double;
    SENLON:double;
    SENALT:double;
    ELNOT:string;
    ANTENNA_NAME:string;
    COLLECTION_MODE:string;
    FREQUENCY:double;
    NOMINAL_FREQUENCY:double;
    START_FREQUENCY:double;
    END_FREQUENCY:double;
    FREQUENCY_SHIFT:double;
    BANDWIDTH:double;
    NOMINAL_BANDWIDTH:double;
    RESOLUTION_BANDWIDTH:double;
    VIDEO_BANDWIDTH:double;
    RELATIVE_CARRIER_POWER:double;
    SPECTRUM_ANALYZER_POWER:double;
    RELATIVE_NOISE_FLOOR:double;
    REFERENCE_LEVEL:double;
    NOISE_PWR_DENSITY:double;
    PGRI:double;
    EIRP:double;
    NOMINAL_EIRP:double;
    MIN_PSD:double;
    MAX_PSD:double;
    SNR:double;
    NOMINAL_SNR:double;
    POWER_OVER_NOISE:double;
    NOMINAL_POWER_OVER_NOISE:double;
    POLARITY:double;
    POLARITY_TYPE:string;
    CHANNEL:uint16;
    BAUD_RATE:double;
    SYMBOL_TO_NOISE_RATIO:double;
    BIT_ERROR_RATE:double;
    PEAK:bool;
    INCOMING:bool;
    SWITCH_POINT:uint16;
    CONFIDENCE:double;
    CARRIER_STANDARD:string;
    MODULATION:string;
    INNER_CODING_RATE:uint8;
    OUTER_CODING_RATE:uint8;
    TRANSMIT_FILTER_TYPE:string;
    TRANSMIT_FILTER_ROLL_OFF:double;
    RAW_FILE_URI:string;
    DESCRIPTOR:string;
    URL:string;
  }
  table RFS {
    MATERIAL_ID:string;
    NAME:string;
    MATERIAL_CLASS:byte;
    DESCRIPTION:string;
    FREQUENCY_MIN_MHZ:double;
    FREQUENCY_MAX_MHZ:double;
    PERMITTIVITY_COEFFICIENT_A:double;
    PERMITTIVITY_EXPONENT_B:double;
    CONDUCTIVITY_COEFFICIENT_C:double;
    CONDUCTIVITY_EXPONENT_D:double;
    REFERENCE_FREQUENCY_MHZ:double;
    RELATIVE_PERMITTIVITY_REAL:double;
    RELATIVE_PERMITTIVITY_IMAGINARY:double;
    CONDUCTIVITY_S_PER_M:double;
    LOSS_TANGENT:double;
    RELATIVE_PERMEABILITY_REAL:double;
    RELATIVE_PERMEABILITY_IMAGINARY:double;
    REFLECTIVITY:double;
    REFLECTION_LOSS_DB:double;
    THICKNESS_M:double;
    TRANSMISSION_LOSS_DB:double;
    ATTENUATION_DB_PER_M:double;
    ABSORPTION_COEFFICIENT:double;
    SURFACE_ROUGHNESS_RMS_M:double;
    ROUGHNESS_CORRELATION_LENGTH_M:double;
    SCATTERING_CLASS:byte;
    DIFFUSE_SCATTERING_COEFFICIENT:double;
    BACKSCATTER_COEFFICIENT_DB:double;
    TEMPERATURE_K:double;
    MOISTURE_CONTENT_FRACTION:double;
    SALINITY_PSU:double;
  }
  table RHD {
    schema_type:string;
  }
  table ROC {
    NAME:string;
    FAMILY:string;
    VARIANT:string;
  }
  table RPT {
    REPORT_ID:string;
    TEMPLATE_ID:string;
    TEMPLATE_VERSION:string;
    TITLE:string;
    SOURCE_QUERY:string;
    SOURCE_DATA_HASH:[ubyte];
    CONTENT_HASH:[ubyte];
    CONTENT_TYPE:string;
    CONTENT_CID:string;
    GENERATED_AT:uint64;
    GENERATOR_MODULE_ID:string;
    GENERATOR_MODULE_VERSION:string;
    CREATOR_EPM_CID:string;
    SIGNATURE:[ubyte];
  }
  table RSD {
    RSD_ID:string;
    NAME:string;
    SCENARIO_ID:string;
    SENSOR_ID:string;
    SNR_ID:string;
    SDR_ID:string;
    APL_ID:string;
    WAVEFORM:byte;
    INTEGRATION:byte;
    CFAR:byte;
    TARGET_MODEL:byte;
    PULSE_COUNT:uint32;
    CFAR_REFERENCE_CELL_COUNT:uint32;
    CFAR_GUARD_CELL_COUNT:uint32;
    CFAR_LOSS_DB:double;
    TARGET_RCS_M2:double;
    FALSE_ALARM_PROBABILITY_REQUIREMENT:double;
    DETECTION_PROBABILITY_REQUIREMENT:double;
  }
  table SAR {
    ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ON_ORBIT:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    EXTERNAL_ID:string;
    COLLECTION_ID:string;
    DETECTION_ID:string;
    COLLECTION_START:string;
    COLLECTION_END:string;
    CENTER_TIME:string;
    DETECTION_START:string;
    DETECTION_END:string;
    DWELL_TIME:double;
    ORBIT_STATE:string;
    SAR_MODE:byte;
    OPERATING_BAND:string;
    OPERATING_FREQ:double;
    SNR:double;
    TX_POLARIZATION:byte;
    RX_POLARIZATION:byte;
    GRAZE_ANGLE:double;
    INCIDENCE_ANGLE:double;
    SQUINT_ANGLE:double;
    PULSE_BANDWIDTH:double;
    PULSE_DURATION:double;
    CONTINUOUS_SPOT_ANGLE:double;
    SLANT_RANGE:double;
    NEAR_RANGE:double;
    FAR_RANGE:double;
    SWATH_LENGTH:double;
    AGJSON:string;
    ATEXT:string;
    ATYPE:string;
    COORD_SYS:string;
    SPACING_RANGE:double;
    SPACING_AZIMUTH:double;
    LOOKS_AZIMUTH:uint8;
    LOOKS_RANGE:uint8;
    RESOLUTION_RANGE:double;
    RESOLUTION_AZIMUTH:double;
    OB_DIRECTION:string;
    TARGETPOSX:double;
    TARGETPOSY:double;
    TARGETPOSZ:double;
    SENALT:double;
    SENVELX:double;
    SENVELY:double;
    SENVELZ:double;
    SENLAT_START:double;
    SENLON_START:double;
    SENLAT_END:double;
    SENLON_END:double;
    TRANSACTION_ID:string;
  }
  table SBM {
    MESSAGE_ID:string;
    CREATION_DATE:string;
    ORIGINATOR:string;
    EVENT_TYPE:byte;
    OBJECT_CLASS:byte;
    EPOCH:string;
    TIME_SYSTEM:string;
    REF_FRAME:string;
    OBJECT_NAME:string;
    OBJECT_ID:string;
    NORAD_CAT_ID:uint;
    IMPACTOR_OBJECT_NAME:string;
    IMPACTOR_NORAD_CAT_ID:uint;
    TARGET_MASS_KG:double;
    TARGET_L_C_M:double;
    IMPACTOR_MASS_KG:double;
    IMPACTOR_L_C_M:double;
    RELATIVE_VELOCITY_M_PER_S:double;
    CATASTROPHIC:bool;
    PARENT_POSITION_X_KM:double;
    PARENT_POSITION_Y_KM:double;
    PARENT_POSITION_Z_KM:double;
    PARENT_VELOCITY_X_KM_PER_S:double;
    PARENT_VELOCITY_Y_KM_PER_S:double;
    PARENT_VELOCITY_Z_KM_PER_S:double;
    MIN_LC_M:double;
    SEED:uint32;
    MODEL_NAME:string;
    MODEL_VERSION:string;
    FRAGMENT_COUNT:uint;
    INPUT_MASS_KG:double;
    OUTPUT_MASS_KG:double;
  }
  table SCC {
    MESSAGE_KIND:byte;
    TRACE_ID:string;
  }
  table SCM {
    version:string;
  }
  table SCN {
    SCENARIO_ID:string;
  }
  table SCV {
    ENVELOPE_KIND:ubyte;
  }
  table SCX {
    CHAIN:string;
    CHAIN_ID:uint64;
    SETTLEMENT_KIND:byte;
    SPLITTER_STANDARD:string;
    SPLITTER_ADDRESS:string;
    SPLIT_CONFIG_ID:string;
    TOKEN_ADDRESS:string;
    TOKEN_SYMBOL:string;
    TOKEN_DECIMALS:uint8;
  }
  table SDF {
    CONFIG:ubyte;
  }
  table SDL {
    SPI:ushort;
    IV_LENGTH:ubyte;
    IV:[ubyte];
    MAC_LENGTH:ubyte;
    MAC:[ubyte];
    PAD_LENGTH:ubyte;
    PAYLOAD:[ubyte];
  }
  table SDR {
    CONFIG:ubyte;
  }
  table SEN {
    ID:string;
    NAME:string;
    TYPE:string;
    STATUS:byte;
    SITE_ID:string;
    LATITUDE:double;
    LONGITUDE:double;
    ALTITUDE:double;
    STATUS_TIME:string;
  }
  table SEO {
    ID:string;
    MSG_TYPE:string;
    GEN_SYSTEM:string;
    EXTERNAL_ID:string;
    DATA_TYPE:byte;
    GEN_TIME:string;
    FORECAST:bool;
    DERIVED:bool;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    OBSERVATORY_TYPE:byte;
    OBSERVATORY_NAME:string;
    OBSERVATORY_NOTES:string;
    INSTRUMENT_TYPE:string;
    LAT:double;
    LON:double;
    ALT:double;
    SEN_REFERENCE_FRAME:string;
  }
  table SEV {
    OB_TYPE:string;
    OB_UO_M:string;
    OB_VALUE:double;
    OB_STRING:string;
  }
  table SHC {
    MODEL_NAME:string;
    CENTRAL_BODY_NAIF_ID:int;
    BODY_NAME:string;
    GM:double;
    REFERENCE_RADIUS:double;
    MAX_DEGREE:ushort;
    MAX_ORDER:ushort;
    NORMALIZATION:ubyte;
    PERMANENT_TIDE_SYSTEM:ubyte;
    REFERENCE_EPOCH:string;
  }
  table SHW {
    COMPILE_REQUEST:ubyte;
  }
  table SIT {
    ID:string;
    NAME:string;
    ABBREVIATION:string;
    SITE_TYPE:byte;
    CATCODE:string;
    NETWORK:string;
    LATITUDE:float;
    LONGITUDE:float;
    ALTITUDE:float;
  }
  table SKI {
    ID:string;
    ON_ORBIT:string;
    ORIG_OBJECT_ID:string;
    SAT_NO:uint32;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    SENLAT:double;
    SENLON:double;
    SENALT:double;
    SENX:double;
    SENY:double;
    SENZ:double;
  }
  table SNR {
    TYPE:ubyte;
    MODE:ubyte;
    RESERVED1:ushort;
    MAX_RANGE:double;
    MIN_RANGE:double;
    FOV_AZIMUTH:float;
    FOV_ELEVATION:float;
    ANGULAR_RESOLUTION:float;
    RANGE_RESOLUTION:float;
    UPDATE_RATE:float;
    DETECTION_THRESHOLD:float;
    AZIMUTH_SCAN_RATE:float;
    ELEVATION_SCAN_RATE:float;
    POWER:float;
    FREQUENCY:float;
    RESERVED:[ubyte];
  }
  table SNW {
    BATCH_REQUEST:ubyte;
  }
  table SOI {
    ID:string;
    MSG_CREATE_DATE:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    SENSOR_AS_ID:string;
    SAT_NO:uint32;
    ORIG_OBJECT_ID:string;
    SATELLITE_NAME:string;
    UCT:bool;
    SENLAT:double;
    SENLON:double;
    SENALT:double;
    SENX:double;
    SENY:double;
    SENZ:double;
    SENVELX:double;
    SENVELY:double;
    SENVELZ:double;
    SEN_REFERENCE_FRAME:string;
    OBS_TYPE:byte;
    COLLECTION_MODE:byte;
    START_TIME:string;
    END_TIME:string;
    NUM_OBS:uint32;
    REFERENCE_FRAME:string;
    POLAR_ANGLE_START:double;
    POLAR_ANGLE_END:double;
    LOS_DECLINATION_START:double;
    LOS_DECLINATION_END:double;
    POINTING_ANGLE_AZ_START:double;
    POINTING_ANGLE_AZ_END:double;
    POINTING_ANGLE_EL_START:double;
    POINTING_ANGLE_EL_END:double;
    PIXEL_ARRAY_WIDTH:uint16;
    PIXEL_ARRAY_HEIGHT:uint16;
    NUM_SPECTRAL_FILTERS:uint8;
  }
  table SON {
    COMMAND:string;
    ACTIVE_CONFIG:string;
    PASSIVE_CONFIG:string;
    TL_REQUEST:string;
    ENVIRONMENT:string;
    TARGET_SIGNATURE:string;
    TMA_INPUT:string;
    TORPEDO_SEEKER:string;
  }
  table SPP {
    VERSION:ubyte;
    PACKET_TYPE:byte;
    SEC_HDR_FLAG:bool;
    APID:ushort;
    SEQUENCE_FLAGS:ubyte;
    SEQUENCE_COUNT:ushort;
    DATA_LENGTH:ushort;
    DATA:[ubyte];
  }
  table SPW {
    DATE:string;
    BSRN:int;
    ND:int;
    KP1:int;
    KP2:int;
    KP3:int;
    KP4:int;
    KP5:int;
    KP6:int;
    KP7:int;
    KP8:int;
    KP_SUM:int;
    AP1:int;
    AP2:int;
    AP3:int;
    AP4:int;
    AP5:int;
    AP6:int;
    AP7:int;
    AP8:int;
    AP_AVG:int;
    CP:float;
    C9:int;
    ISN:int;
    F107_OBS:float;
    F107_ADJ:float;
    F107_DATA_TYPE:byte;
    F107_OBS_CENTER81:float;
    F107_OBS_LAST81:float;
    F107_ADJ_CENTER81:float;
    F107_ADJ_LAST81:float;
  }
  table SRI {
    RECORD_KEY:string;
    SCHEMA_NAME:string;
    ROLE:string;
    ATTACHED_VIA:string;
    PAYLOAD_KIND:string;
    UPDATED_AT_MS:double;
    RESERVED:[ubyte];
  }
  table STF {
    LISTING_ID:string;
    PROVIDER_PEER_ID:string;
    PROVIDER_EPM_CID:string;
    TITLE:string;
    DESCRIPTION:string;
  }
  table STO {
    STORE_ID:string;
    NAME:string;
    DESCRIPTION:string;
    OPERATOR_EPM_CID:string;
  }
  table STR {
    ID:string;
    CS_ID:long;
    GNC_CAT_ID:uint32;
    GAIADR3_CAT_ID:long;
    HIP_CAT_ID:uint32;
    CAT_VERSION:string;
    ASTROMETRY_ORIGIN:string;
    STAR_EPOCH:double;
    RA:double;
    RA_UNC:double;
    DEC:double;
    DEC_UNC:double;
    POS_UNC_FLAG:bool;
    PARALLAX:double;
    PARALLAX_UNC:double;
    PMRA:double;
    PMRA_UNC:double;
    PMDEC:double;
    PMDEC_UNC:double;
    PM_UNC_FLAG:bool;
    GMAG:double;
    GMAG_UNC:double;
    BPMAG:double;
    BPMAG_UNC:double;
    RPMAG:double;
    RPMAG_UNC:double;
    JMAG:double;
    JMAG_UNC:double;
    KMAG:double;
    KMAG_UNC:double;
    HMAG:double;
    HMAG_UNC:double;
    VAR_FLAG:bool;
    MULT_FLAG:bool;
    NEIGHBOR_ID:uint32;
    NEIGHBOR_FLAG:bool;
    NEIGHBOR_DISTANCE:double;
    SHIFT_FLAG:bool;
    SHIFT:double;
  }
  table STV {
    EPOCH:double;
    POS_X:double;
    POS_Y:double;
    POS_Z:double;
    VEL_X:double;
    VEL_Y:double;
    VEL_Z:double;
    REF_FRAME:ubyte;
    FLAGS:ubyte;
    RESERVED:[ubyte];
  }
  table STX {
    ID:string;
    SITE_ID:string;
    SITE_NATIVE_ID:string;
    STATION_NAME:string;
    STATION_IDENTITY:string;
    FREQUENCY_KHZ:double;
    BANDWIDTH_KHZ:double;
    EMISSION_DESIGNATOR:string;
    MODULATION:byte;
    POLARIZATION:byte;
    SERVICE:byte;
    CONTENT:byte;
    TIME_START_UTC:string;
    TIME_STOP_UTC:string;
    DAYS:ubyte;
    IRREGULAR:bool;
    VALID_FROM:string;
    VALID_UNTIL:string;
    SEASON:string;
    TARGET_AREA:string;
  }
  table SUB {
    SUBSCRIPTION_ID:string;
    ENTITLEMENT_ID:string;
    LISTING_ID:string;
    AUTH_KIND:byte;
  }
  table SWR {
    ID:string;
    ON_ORBIT:string;
    ORIG_OBJECT_ID:string;
    SAT_NO:uint32;
    TS:string;
    SOLAR_PHASE_ANGLE:double;
    LAT:double;
    LON:double;
    LOCATION_NAME:string;
    BAD_WAVE:string;
  }
  table TAB {
    OFFSET:uint;
    SIZE:uint;
    ALIGNMENT:uint;
    WIRE_FORMAT:ubyte;
  }
  table TCF {
    VERSION:ubyte;
    BYPASS_FLAG:bool;
    CONTROL_CMD_FLAG:bool;
    SPACECRAFT_ID:ushort;
    VIRTUAL_CHANNEL_ID:ubyte;
    FRAME_LENGTH:ushort;
    FRAME_SEQUENCE_NUM:ubyte;
    DATA:[ubyte];
    FECF:ushort;
  }
  table TDM {
    OBSERVER_ID:string;
    OBSERVER_X:double;
    OBSERVER_Y:double;
    OBSERVER_Z:double;
    OBSERVER_VX:double;
    OBSERVER_VY:double;
    OBSERVER_VZ:double;
  }
  table TFN {
    ID:string;
    PLACE_ID:string;
    FACILITY_TYPE:byte;
    NAME:string;
  }
  table TIM {
    TIME_SYSTEM:byte;
  }
  table TKG {
    COMMAND:string;
    FILTER_CONFIG:string;
    IMM_CONFIG:string;
    MHT_CONFIG:string;
    JPDA_CONFIG:string;
    FUSION_CONFIG:string;
    MEASUREMENTS:string;
    INITIAL_STATE:string;
    TRACK_TO_UPDATE:string;
  }
  table TME {
    COMMAND:string;
    CONVERSION_REQUEST:string;
    LEAP_SECOND_QUERY:string;
    EOP_QUERY:string;
    SIDEREAL_QUERY:string;
    INTERVAL_REQUEST:string;
    SOLAR_POSITION_QUERY:string;
    LUNAR_POSITION_QUERY:string;
  }
  table TMF {
    VERSION:ubyte;
    SPACECRAFT_ID:ushort;
    VIRTUAL_CHANNEL_ID:ubyte;
    OCF_FLAG:bool;
    MASTER_FRAME_COUNT:ubyte;
    VIRTUAL_FRAME_COUNT:ubyte;
    SEC_HDR_FLAG:bool;
    SYNCH_FLAG:bool;
    PACKET_ORDER_FLAG:bool;
    SEGMENT_LENGTH_ID:ubyte;
    FIRST_HDR_POINTER:ushort;
    DATA:[ubyte];
    OCF:[ubyte];
    FECF:ushort;
  }
  table TMS {
    ID:string;
    TRACK_ID:string;
    ENVIRONMENT:byte;
    EPOCH:string;
    LATITUDE:double;
    LONGITUDE:double;
    ALTITUDE_M:double;
    GROUND_SPEED_MPS:double;
    VELOCITY_NORTH_MPS:double;
    VELOCITY_EAST_MPS:double;
    VELOCITY_UP_MPS:double;
    HEADING_DEG:double;
    COURSE_DEG:double;
    TURN_RATE_DPS:double;
    VERTICAL_RATE_MPS:double;
    MODEL_ID:string;
  }
  table TNR {
    NODE_ID:string;
    CREATED_AT:uint64;
    UPDATED_AT:uint64;
    DELETED:bool;
    PROVIDER_PEER_ID:string;
    PROVIDER_SIGNATURE:[ubyte];
  }
  table TPN {
    ID:string;
    NAME:string;
    NID:string;
    TID:string;
    TTF:double;
    SYMBOL_RATE:double;
    FEC:int;
    MODULATION:string;
    FORMAT:string;
    SYSTEM:string;
  }
  table TRE {
    EDGE_ID:string;
    TRUSTER_ID:string;
    TRUSTEE_ID:string;
    WEIGHT:double;
    UPDATED_AT:uint64;
    DELETED:bool;
    PROVIDER_PEER_ID:string;
    PROVIDER_SIGNATURE:[ubyte];
  }
  table TRK {
    ID:string;
    CNTCT:string;
    MSG_TS:string;
    MSN_ID:string;
    ASSET_NAT:string;
    ASSET:string;
    SENSOR_ID:string;
    SEN_QUAL:string;
    TRK_ID:string;
    TRK_NUM:string;
    TRK_STAT:byte;
    OBJ_NAT:string;
    OBJ_ID:string;
    OBJ_TYPE:string;
    OBJ_SPEC:string;
    OBJ_PLAT:string;
    OBJ_ACT:string;
    MOD_TYPE:string;
    TRK_ITM_ID:string;
    TS:string;
    TRK_QUAL:uint8;
    TRK_PT_TYPE:string;
    OBJ_IDENT:string;
    IDENT_CRED:uint8;
    IDENT_REL:uint8;
    IDENT_AMP:string;
    ENVIRONMENT:byte;
    ENVIRONMENT_CONF:double;
    TRK_CONF:double;
    LAT:double;
    LON:double;
    ALT:double;
    SPD:double;
    HDNG:double;
    COURSE:double;
  }
  table TRN {
    SOURCES:ubyte;
  }
  table TRS {
    REQUEST:ubyte;
  }
  table TXS {
    ID:string;
    NATIVE_ID:string;
    SITE_NAME:string;
    STATION_IDENTITY:string;
    LICENSEE:string;
    LICENSE_ID:string;
    SERVICE:byte;
    STATUS:byte;
    COUNTRY_CODE:string;
    ADMIN_AREA:string;
    LATITUDE:double;
    LONGITUDE:double;
    POSITION_AUTHORITY:byte;
    POSITION_UNCERTAINTY_M:double;
    POSITION_DISPUTED:bool;
  }
  table VAM {
    ID:string;
    VERSION:string;
    ENTITY_ID:string;
    ENTITY_KIND:string;
    CANONICAL_VARIANT_ID:string;
  }
  table VCF {
    CARD_ID:string;
    FORM:byte;
    CARD:string;
    MEDIA_TYPE:string;
  }
  table VEP {
    ID:string;
    VEHICLE_CLASS_ID:string;
    VEHICLE_TYPE_DESIGNATOR:string;
    ENVIRONMENT:byte;
    ENERGY_TYPE:byte;
    CAPACITY_VALUE:double;
    CAPACITY_UNITS:string;
    RESERVE_FRACTION:double;
  }
  table VST {
    CAMERA:ubyte;
  }
  table WKS {
    WORKSPACE_ID:string;
    NAME:string;
    DESCRIPTION:string;
    OWNER_EPM_CID:string;
    APP_ID:string;
  }
  table WPN {
    CALIBER:float;
    MUZZLE_VELOCITY:float;
    RATE_OF_FIRE:float;
    DISPERSION:float;
    AMMO_CAPACITY:ushort;
    BURST_LENGTH:ushort;
    RELOAD_TIME:float;
    OVERHEAT_ROUNDS:ushort;
    COOLDOWN_RATE:float;
    ELEVATION_MIN:float;
    ELEVATION_MAX:float;
    TRAVERSE_MIN:float;
    TRAVERSE_MAX:float;
    SLEW_RATE:float;
    WEAPON_TYPE:ubyte;
    FUZE_TYPE:ubyte;
    RESERVED:[ubyte];
  }
  table WTH {
    ID:string;
    ID_SENSOR:string;
    ORIG_SENSOR_ID:string;
    OB_TIME:string;
    FILE_CREATION:string;
    QC_VALUE:uint8;
    TERM_ALT:double;
    AVG_TX_PWR:double;
    AVG_REF_PWR:double;
    SECTOR_NUM:uint16;
    NUM_ELEMENTS:uint16;
    CHECKSUM:uint32;
  }
  table XTC {
    NAME:string;
    SHORT_DESCRIPTION:string;
    LONG_DESCRIPTION:string;
    OPERATIONAL_STATUS:string;
  }
`

// engineGeneratedStandardBindings binds each generated table to the 4-byte
// FlatBuffer file identifier its standard declares. RegisterFileID is what
// materializes a table in the engine, and it THROWS on a name that is not in
// the schema — so this map and engineStandardCatalogGraph are generated
// together and can never disagree.
var engineGeneratedStandardBindings = map[string]engineRoutedSchema{
	"ACI.fbs":  {Table: "ACI", FileID: "$ACI"},
	"ACL.fbs":  {Table: "ACL", FileID: "$ACL"},
	"ACM.fbs":  {Table: "ACM", FileID: "$ACM"},
	"ACR.fbs":  {Table: "ACR", FileID: "$ACR"},
	"ACW.fbs":  {Table: "ACW", FileID: "$ACW"},
	"AEM.fbs":  {Table: "AEM", FileID: "$AEM"},
	"ANI.fbs":  {Table: "ANI", FileID: "$ANI"},
	"AOF.fbs":  {Table: "AOF", FileID: "$AOF"},
	"APL.fbs":  {Table: "APL", FileID: "$APL"},
	"APM.fbs":  {Table: "APM", FileID: "$APM"},
	"APP.fbs":  {Table: "APP", FileID: "$APP"},
	"ARM.fbs":  {Table: "ARM", FileID: "$ARM"},
	"AST.fbs":  {Table: "AST", FileID: "$AST"},
	"ATD.fbs":  {Table: "ATD", FileID: "$ATD"},
	"ATM.fbs":  {Table: "ATM", FileID: "$ATM"},
	"AVL.fbs":  {Table: "AVL", FileID: "$AVL"},
	"BAL.fbs":  {Table: "BAL", FileID: "$BAL"},
	"BEM.fbs":  {Table: "BEM", FileID: "$BEM"},
	"BMC.fbs":  {Table: "BMC", FileID: "$BMC"},
	"BOV.fbs":  {Table: "BOV", FileID: "$BOV"},
	"BSP.fbs":  {Table: "BSP", FileID: "$BSP"},
	"BUS.fbs":  {Table: "BUS", FileID: "$BUS"},
	"CAQ.fbs":  {Table: "CAQ", FileID: "$CAQ"},
	"CAT.fbs":  {Table: "CAT", FileID: "$CAT"},
	"CCT.fbs":  {Table: "CCT", FileID: "$CCT"},
	"CDM.fbs":  {Table: "CDM", FileID: "$CDM"},
	"CES.fbs":  {Table: "CES", FileID: "$CES"},
	"CFP.fbs":  {Table: "CFP", FileID: "$CFP"},
	"CHN.fbs":  {Table: "CHN", FileID: "$CHN"},
	"CLT.fbs":  {Table: "CLT", FileID: "$CLT"},
	"CMR.fbs":  {Table: "CMR", FileID: "$CMR"},
	"CMS.fbs":  {Table: "CMS", FileID: "$CMS"},
	"CMT.fbs":  {Table: "CMT", FileID: "$CMT"},
	"CNP.fbs":  {Table: "CNP", FileID: "$CNP"},
	"COM.fbs":  {Table: "COM", FileID: "$COM"},
	"COT.fbs":  {Table: "COT", FileID: "$COT"},
	"CPS.fbs":  {Table: "CPS", FileID: "$CPS"},
	"CRD.fbs":  {Table: "CRD", FileID: "$CRD"},
	"CRM.fbs":  {Table: "CRM", FileID: "$CRM"},
	"CSM.fbs":  {Table: "CSM", FileID: "$CSM"},
	"CTR.fbs":  {Table: "CTR", FileID: "$CTR"},
	"CVG.fbs":  {Table: "CVG", FileID: "$CVG"},
	"CVP.fbs":  {Table: "CVP", FileID: "$CVP"},
	"CZM.fbs":  {Table: "CZM", FileID: "$CZM"},
	"DFH.fbs":  {Table: "DFH", FileID: "$DFH"},
	"DMG.fbs":  {Table: "DMG", FileID: "$DMG"},
	"DOA.fbs":  {Table: "DOA", FileID: "$DOA"},
	"DPM.fbs":  {Table: "DPM", FileID: "$DPM"},
	"DSS.fbs":  {Table: "DSS", FileID: "$DSS"},
	"DTT.fbs":  {Table: "DTT", FileID: "$DTT"},
	"EGP.fbs":  {Table: "EGP", FileID: "$EGP"},
	"EMC.fbs":  {Table: "EMC", FileID: "$EMC"},
	"EME.fbs":  {Table: "EME", FileID: "$EME"},
	"ENC.fbs":  {Table: "ENC", FileID: "$ENC"},
	"ENT.fbs":  {Table: "ENT", FileID: "$ENT"},
	"ENV.fbs":  {Table: "ENV", FileID: "$ENV"},
	"EOO.fbs":  {Table: "EOO", FileID: "$EOO"},
	"EOP.fbs":  {Table: "EOP", FileID: "$EOP"},
	"EPF.fbs":  {Table: "EPF", FileID: "$EPF"},
	"EPM.fbs":  {Table: "EPM", FileID: "$EPM"},
	"ESL.fbs":  {Table: "ESL", FileID: "$ESL"},
	"ETM.fbs":  {Table: "ETM", FileID: "$ETM"},
	"EWR.fbs":  {Table: "EWR", FileID: "$EWR"},
	"FCS.fbs":  {Table: "FCS", FileID: "$FCS"},
	"FPC.fbs":  {Table: "FPC", FileID: "$FPC"},
	"FRM.fbs":  {Table: "FRM", FileID: "$FRM"},
	"FSB.fbs":  {Table: "FSB", FileID: "$FSB"},
	"FSM.fbs":  {Table: "FSM", FileID: "$FSM"},
	"FSO.fbs":  {Table: "FSO", FileID: "$FSO"},
	"FSP.fbs":  {Table: "FSP", FileID: "$FSP"},
	"GDI.fbs":  {Table: "GDI", FileID: "$GDI"},
	"GEL.fbs":  {Table: "GEL", FileID: "$GEL"},
	"GEO.fbs":  {Table: "GEO", FileID: "$GEO"},
	"GJN.fbs":  {Table: "GJN", FileID: "$GJN"},
	"GNO.fbs":  {Table: "GNO", FileID: "$GNO"},
	"GNP.fbs":  {Table: "GNP", FileID: "$GNP"},
	"GPX.fbs":  {Table: "GPX", FileID: "$GPX"},
	"GRV.fbs":  {Table: "GRV", FileID: "$GRV"},
	"GST.fbs":  {Table: "GST", FileID: "$GST"},
	"GVH.fbs":  {Table: "GVH", FileID: "$GVH"},
	"HEL.fbs":  {Table: "HEL", FileID: "$HEL"},
	"HFC.fbs":  {Table: "HFC", FileID: "$HFC"},
	"HYP.fbs":  {Table: "HYP", FileID: "$HYP"},
	"IDM.fbs":  {Table: "IDM", FileID: "$IDM"},
	"ION.fbs":  {Table: "ION", FileID: "$ION"},
	"IQC.fbs":  {Table: "IQC", FileID: "$IQC"},
	"IRM.fbs":  {Table: "IRM", FileID: "$IRM"},
	"IRO.fbs":  {Table: "IRO", FileID: "$IRO"},
	"KML.fbs":  {Table: "KML", FileID: "$KML"},
	"KRF.fbs":  {Table: "KRF", FileID: "$KRF"},
	"LAM.fbs":  {Table: "LAM", FileID: "$LAM"},
	"LCC.fbs":  {Table: "LCC", FileID: "$LCC"},
	"LCF.fbs":  {Table: "LCF", FileID: "$LCF"},
	"LCH.fbs":  {Table: "LCH", FileID: "$LCH"},
	"LDM.fbs":  {Table: "LDM", FileID: "$LDM"},
	"LGR.fbs":  {Table: "LGR", FileID: "$LGR"},
	"LKS.fbs":  {Table: "LKS", FileID: "$LKS"},
	"LMO.fbs":  {Table: "LMO", FileID: "$LMO"},
	"LMR.fbs":  {Table: "LMR", FileID: "$LMR"},
	"LMS.fbs":  {Table: "LMS", FileID: "$LMS"},
	"LND.fbs":  {Table: "LND", FileID: "$LND"},
	"LNE.fbs":  {Table: "LNE", FileID: "$LNE"},
	"LPF.fbs":  {Table: "LPF", FileID: "$LPF"},
	"LWK.fbs":  {Table: "LWK", FileID: "$LWK"},
	"MBL.fbs":  {Table: "MBL", FileID: "$MBL"},
	"MDP.fbs":  {Table: "MDP", FileID: "$MDP"},
	"MDS.fbs":  {Table: "MDS", FileID: "$MDS"},
	"MET.fbs":  {Table: "MET", FileID: "$MET"},
	"MFE.fbs":  {Table: "MFE", FileID: "$MFE"},
	"MNF.fbs":  {Table: "MNF", FileID: "$MNF"},
	"MNV.fbs":  {Table: "MNV", FileID: "$MNV"},
	"MPE.fbs":  {Table: "MPE", FileID: "$MPE"},
	"MSL.fbs":  {Table: "MSL", FileID: "$MSL"},
	"MST.fbs":  {Table: "MST", FileID: "$MST"},
	"MTI.fbs":  {Table: "MTI", FileID: "$MTI"},
	"NAV.fbs":  {Table: "NAV", FileID: "$NAV"},
	"NUM.fbs":  {Table: "NUM", FileID: "$NUM"},
	"OBD.fbs":  {Table: "OBD", FileID: "$OBD"},
	"OBT.fbs":  {Table: "OBT", FileID: "$OBT"},
	"OCM.fbs":  {Table: "OCM", FileID: "$OCM"},
	"OEM.fbs":  {Table: "OEM", FileID: "$OEM"},
	"OOA.fbs":  {Table: "OOA", FileID: "$OOA"},
	"OOB.fbs":  {Table: "OOB", FileID: "$OOB"},
	"OOD.fbs":  {Table: "OOD", FileID: "$OOD"},
	"OOE.fbs":  {Table: "OOE", FileID: "$OOE"},
	"OOI.fbs":  {Table: "OOI", FileID: "$OOI"},
	"OOL.fbs":  {Table: "OOL", FileID: "$OOL"},
	"OON.fbs":  {Table: "OON", FileID: "$OON"},
	"OOS.fbs":  {Table: "OOS", FileID: "$OOS"},
	"OOT.fbs":  {Table: "OOT", FileID: "$OOT"},
	"OPM.fbs":  {Table: "OPM", FileID: "$OPM"},
	"OPP.fbs":  {Table: "OPP", FileID: "$OPP"},
	"OSM.fbs":  {Table: "OSM", FileID: "$OSM"},
	"PAP.fbs":  {Table: "PAP", FileID: "$PAP"},
	"PCF.fbs":  {Table: "PCF", FileID: "$PCF"},
	"PGM.fbs":  {Table: "PGM", FileID: "$PGM"},
	"PGR.fbs":  {Table: "PGR", FileID: "$PGR"},
	"PHY.fbs":  {Table: "PHY", FileID: "$PHY"},
	"PIV.fbs":  {Table: "PIV", FileID: "$PIV"},
	"PKB.fbs":  {Table: "PKB", FileID: "$PKB"},
	"PLD.fbs":  {Table: "PLD", FileID: "$PLD"},
	"PLG.fbs":  {Table: "PLG", FileID: "$PLG"},
	"PLHD.fbs": {Table: "PLHD", FileID: "PLHD"},
	"PLK.fbs":  {Table: "PLK", FileID: "$PLK"},
	"PLOG.fbs": {Table: "PLOG", FileID: "PLOG"},
	"PMM.fbs":  {Table: "PMM", FileID: "$PMM"},
	"PNL.fbs":  {Table: "PNL", FileID: "$PNL"},
	"PNM.fbs":  {Table: "PNM", FileID: "$PNM"},
	"PPE.fbs":  {Table: "PPE", FileID: "$PPE"},
	"PRG.fbs":  {Table: "PRG", FileID: "$PRG"},
	"PRR.fbs":  {Table: "PRR", FileID: "$PRR"},
	"PRW.fbs":  {Table: "PRW", FileID: "$PRW"},
	"PUR.fbs":  {Table: "PUR", FileID: "$PUR"},
	"QEM.fbs":  {Table: "QEM", FileID: "$QEM"},
	"RAF.fbs":  {Table: "RAF", FileID: "$RAF"},
	"RBK.fbs":  {Table: "RBK", FileID: "$RBK"},
	"RCF.fbs":  {Table: "RCF", FileID: "$RCF"},
	"RDM.fbs":  {Table: "RDM", FileID: "$RDM"},
	"RDO.fbs":  {Table: "RDO", FileID: "$RDO"},
	"REC.fbs":  {Table: "REC", FileID: "$REC"},
	"REM.fbs":  {Table: "REM", FileID: "$REM"},
	"REV.fbs":  {Table: "REV", FileID: "$REV"},
	"RFB.fbs":  {Table: "RFB", FileID: "$RFB"},
	"RFE.fbs":  {Table: "RFE", FileID: "$RFE"},
	"RFL.fbs":  {Table: "RFL", FileID: "$RFL"},
	"RFM.fbs":  {Table: "RFM", FileID: "$RFM"},
	"RFO.fbs":  {Table: "RFO", FileID: "$RFO"},
	"RFS.fbs":  {Table: "RFS", FileID: "$RFS"},
	"RHD.fbs":  {Table: "RHD", FileID: "$RHD"},
	"ROC.fbs":  {Table: "ROC", FileID: "$ROC"},
	"RPT.fbs":  {Table: "RPT", FileID: "$RPT"},
	"RSD.fbs":  {Table: "RSD", FileID: "$RSD"},
	"SAR.fbs":  {Table: "SAR", FileID: "$SAR"},
	"SBM.fbs":  {Table: "SBM", FileID: "$SBM"},
	"SCC.fbs":  {Table: "SCC", FileID: "$SCC"},
	"SCM.fbs":  {Table: "SCM", FileID: "$SCM"},
	"SCN.fbs":  {Table: "SCN", FileID: "$SCN"},
	"SCV.fbs":  {Table: "SCV", FileID: "$SCV"},
	"SCX.fbs":  {Table: "SCX", FileID: "$SCX"},
	"SDF.fbs":  {Table: "SDF", FileID: "$SDF"},
	"SDL.fbs":  {Table: "SDL", FileID: "$SDL"},
	"SDR.fbs":  {Table: "SDR", FileID: "$SDR"},
	"SEN.fbs":  {Table: "SEN", FileID: "$SEN"},
	"SEO.fbs":  {Table: "SEO", FileID: "$SEO"},
	"SEV.fbs":  {Table: "SEV", FileID: "$SEV"},
	"SHC.fbs":  {Table: "SHC", FileID: "$SHC"},
	"SHW.fbs":  {Table: "SHW", FileID: "$SHW"},
	"SIT.fbs":  {Table: "SIT", FileID: "$SIT"},
	"SKI.fbs":  {Table: "SKI", FileID: "$SKI"},
	"SNR.fbs":  {Table: "SNR", FileID: "$SNR"},
	"SNW.fbs":  {Table: "SNW", FileID: "$SNW"},
	"SOI.fbs":  {Table: "SOI", FileID: "$SOI"},
	"SON.fbs":  {Table: "SON", FileID: "$SON"},
	"SPP.fbs":  {Table: "SPP", FileID: "$SPP"},
	"SPW.fbs":  {Table: "SPW", FileID: "$SPW"},
	"SRI.fbs":  {Table: "SRI", FileID: "$SRI"},
	"STF.fbs":  {Table: "STF", FileID: "$STF"},
	"STO.fbs":  {Table: "STO", FileID: "$STO"},
	"STR.fbs":  {Table: "STR", FileID: "$STR"},
	"STV.fbs":  {Table: "STV", FileID: "$STV"},
	"STX.fbs":  {Table: "STX", FileID: "$STX"},
	"SUB.fbs":  {Table: "SUB", FileID: "$SUB"},
	"SWR.fbs":  {Table: "SWR", FileID: "$SWR"},
	"TAB.fbs":  {Table: "TAB", FileID: "$TAB"},
	"TCF.fbs":  {Table: "TCF", FileID: "$TCF"},
	"TDM.fbs":  {Table: "TDM", FileID: "$TDM"},
	"TFN.fbs":  {Table: "TFN", FileID: "$TFN"},
	"TIM.fbs":  {Table: "TIM", FileID: "$TIM"},
	"TKG.fbs":  {Table: "TKG", FileID: "$TKG"},
	"TME.fbs":  {Table: "TME", FileID: "$TME"},
	"TMF.fbs":  {Table: "TMF", FileID: "$TMF"},
	"TMS.fbs":  {Table: "TMS", FileID: "$TMS"},
	"TNR.fbs":  {Table: "TNR", FileID: "$TNR"},
	"TPN.fbs":  {Table: "TPN", FileID: "$TPN"},
	"TRE.fbs":  {Table: "TRE", FileID: "$TRE"},
	"TRK.fbs":  {Table: "TRK", FileID: "$TRK"},
	"TRN.fbs":  {Table: "TRN", FileID: "$TRN"},
	"TRS.fbs":  {Table: "TRS", FileID: "$TRS"},
	"TXS.fbs":  {Table: "TXS", FileID: "$TXS"},
	"VAM.fbs":  {Table: "VAM", FileID: "$VAM"},
	"VCF.fbs":  {Table: "VCF", FileID: "$VCF"},
	"VEP.fbs":  {Table: "VEP", FileID: "$VEP"},
	"VST.fbs":  {Table: "VST", FileID: "$VST"},
	"WKS.fbs":  {Table: "WKS", FileID: "$WKS"},
	"WPN.fbs":  {Table: "WPN", FileID: "$WPN"},
	"WTH.fbs":  {Table: "WTH", FileID: "$WTH"},
	"XTC.fbs":  {Table: "XTC", FileID: "$XTC"},
}

// engineUnroutableSchemas records the embedded standards that are NOT routed,
// with the reason. This is a DECLARATION, not a carve-out: each entry names a
// property of the IDL, and the standard routes automatically once the IDL
// stops having it. TestEveryEmbeddedStandardIsRoutedOrDeclaredUnroutable fails
// if an entry goes stale.
var engineUnroutableSchemas = map[string]string{
	"KMF.fbs": "declares an (encrypted) field, whose plaintext must never reach the engine's public query surface",
	"VCM.fbs": "declares no file_identifier",
}

// engineUnprojectableFirstFields names the standards whose root table already
// starts with a field the engine cannot represent. The >=1 COLUMN INVARIANT
// forces a column anyway (a zero-column table emits malformed DDL and traps
// the no-exceptions engine), so their single column is a FIXED-WIDTH one-byte
// read of slot 0: a number, never that field's value, and never raw record
// bytes in the public JSON response — which is what a string column there
// produced. Consumers of these standards read `_data`, which is the
// whole record. The entry disappears by itself if the standard ever declares a
// representable first field.
var engineUnprojectableFirstFields = map[string]string{
	"ACW.fbs": "REQUEST",
	"BSP.fbs": "INTERPOLATION_REQUEST",
	"CAQ.fbs": "REQUEST",
	"CSM.fbs": "OBJECT_1",
	"FPC.fbs": "GRAPH_DEFINITION",
	"FRM.fbs": "FRAME_TRANSFORM_REQUEST",
	"GJN.fbs": "FEATURES",
	"HYP.fbs": "CAT_IDS",
	"LDM.fbs": "SITE",
	"NUM.fbs": "ROOT_SOLVE_REQUEST",
	"OCM.fbs": "HEADER",
	"PIV.fbs": "REQUEST",
	"PPE.fbs": "COMMENT",
	"PRW.fbs": "INIT",
	"RBK.fbs": "RIGID_BODY_REQUEST",
	"SDF.fbs": "CONFIG",
	"SDR.fbs": "CONFIG",
	"SHW.fbs": "COMPILE_REQUEST",
	"SNW.fbs": "BATCH_REQUEST",
	"TRN.fbs": "SOURCES",
	"TRS.fbs": "REQUEST",
	"VST.fbs": "CAMERA",
}

// enginePinnedSchemas are routed, but their table text lives elsewhere as a
// cross-host contract and must not be regenerated here.
var enginePinnedSchemas = map[string]bool{
	"OMM.fbs": true,
	"TBS.fbs": true,
}
