// Code generated by scripts/generate-suite-version-info.js. DO NOT EDIT.

package versioninfo

const (
	SuiteVersion = "1.0.4"
	SpaceDataStandardsVersion = "1.198.0"
	FlatSQLVersion = "1.4.5"
	HDWalletWasmVersion = "2.0.29"
	HDWalletUIVersion = "2.0.29"
	IPFSWebUIVersion = "4.12.0"
	KuboVersion = "0.40.0-dev"
	DefaultUpdateChannel = "stable"
	CurrentAdvertisementFlag = "spacedatanetwork/1.0.0"
)

var SupportedAdvertisementFlags = []string{
	"spacedatanetwork/1.0.0",
}

func CopySupportedAdvertisementFlags() []string {
	return append([]string(nil), SupportedAdvertisementFlags...)
}
