// Code generated by scripts/generate-suite-version-info.js. DO NOT EDIT.

package versioninfo

const (
	SuiteVersion = "1.0.2"
	SpaceDataStandardsVersion = "1.85.0"
	HDWalletWasmVersion = "2.0.2"
	HDWalletUIVersion = "2.0.2"
	IPFSWebUIVersion = "4.12.0"
	DefaultUpdateChannel = "stable"
	CurrentAdvertisementFlag = "spacedatanetwork/1.0.0"
)

var SupportedAdvertisementFlags = []string{
	"spacedatanetwork/1.0.0",
}

func CopySupportedAdvertisementFlags() []string {
	return append([]string(nil), SupportedAdvertisementFlags...)
}
