// Code generated by scripts/generate-suite-version-info.js. DO NOT EDIT.

package versioninfo

const (
	SuiteVersion = "1.0.3"
	SpaceDataStandardsVersion = "1.134.0"
	FlatSQLVersion = "1.0.1"
	HDWalletWasmVersion = "2.0.20"
	HDWalletUIVersion = "2.0.20"
	IPFSWebUIVersion = "4.12.0"
	DefaultUpdateChannel = "stable"
	CurrentAdvertisementFlag = "spacedatanetwork/1.0.0"
)

var SupportedAdvertisementFlags = []string{
	"spacedatanetwork/1.0.0",
}

func CopySupportedAdvertisementFlags() []string {
	return append([]string(nil), SupportedAdvertisementFlags...)
}
