// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Live traffic for one pubsub topic.
type DashboardTopicStat struct {
	_tab flatbuffers.Table
}

func GetRootAsDashboardTopicStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardTopicStat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DashboardTopicStat{}
	x.Init(buf, n+offset)
	return x
}

func FinishDashboardTopicStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDashboardTopicStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardTopicStat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DashboardTopicStat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDashboardTopicStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DashboardTopicStat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DashboardTopicStat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DashboardTopicStat) TOPIC() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardTopicStat) Topic() []byte {
	return rcv.TOPIC()
}

func (rcv *DashboardTopicStat) RATE_PER_MIN() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DashboardTopicStat) RatePerMin() float64 {
	return rcv.RATE_PER_MIN()
}

func (rcv *DashboardTopicStat) MutateRATE_PER_MIN(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *DashboardTopicStat) MutateRatePerMin(n float64) bool {
	return rcv.MutateRATE_PER_MIN(n)
}

/// Unix seconds; 0 = not observed.
func (rcv *DashboardTopicStat) LAST_SEEN_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardTopicStat) LastSeenAt() int64 {
	return rcv.LAST_SEEN_AT()
}

/// Unix seconds; 0 = not observed.
func (rcv *DashboardTopicStat) MutateLAST_SEEN_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *DashboardTopicStat) MutateLastSeenAt(n int64) bool {
	return rcv.MutateLAST_SEEN_AT(n)
}

func (rcv *DashboardTopicStat) SUBSCRIBED() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DashboardTopicStat) Subscribed() bool {
	return rcv.SUBSCRIBED()
}

func (rcv *DashboardTopicStat) MutateSUBSCRIBED(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *DashboardTopicStat) MutateSubscribed(n bool) bool {
	return rcv.MutateSUBSCRIBED(n)
}

func DashboardTopicStatStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DashboardTopicStatAddTOPIC(builder *flatbuffers.Builder, TOPIC flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(TOPIC), 0)
}
func DashboardTopicStatAddTopic(builder *flatbuffers.Builder, TOPIC flatbuffers.UOffsetT) {
	DashboardTopicStatAddTOPIC(builder, TOPIC)
}
func DashboardTopicStatAddRATE_PER_MIN(builder *flatbuffers.Builder, RATE_PER_MIN float64) {
	builder.PrependFloat64Slot(1, RATE_PER_MIN, 0.0)
}
func DashboardTopicStatAddRatePerMin(builder *flatbuffers.Builder, RATE_PER_MIN float64) {
	DashboardTopicStatAddRATE_PER_MIN(builder, RATE_PER_MIN)
}
func DashboardTopicStatAddLAST_SEEN_AT(builder *flatbuffers.Builder, LAST_SEEN_AT int64) {
	builder.PrependInt64Slot(2, LAST_SEEN_AT, 0)
}
func DashboardTopicStatAddLastSeenAt(builder *flatbuffers.Builder, LAST_SEEN_AT int64) {
	DashboardTopicStatAddLAST_SEEN_AT(builder, LAST_SEEN_AT)
}
func DashboardTopicStatAddSUBSCRIBED(builder *flatbuffers.Builder, SUBSCRIBED bool) {
	builder.PrependBoolSlot(3, SUBSCRIBED, false)
}
func DashboardTopicStatAddSubscribed(builder *flatbuffers.Builder, SUBSCRIBED bool) {
	DashboardTopicStatAddSUBSCRIBED(builder, SUBSCRIBED)
}
func DashboardTopicStatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
