// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import "strconv"

type DashboardIngestEventKind int8

const (
	DashboardIngestEventKindStall   DashboardIngestEventKind = 0
	DashboardIngestEventKindReject  DashboardIngestEventKind = 1
	DashboardIngestEventKindRecover DashboardIngestEventKind = 2
)

var EnumNamesDashboardIngestEventKind = map[DashboardIngestEventKind]string{
	DashboardIngestEventKindStall:   "Stall",
	DashboardIngestEventKindReject:  "Reject",
	DashboardIngestEventKindRecover: "Recover",
}

var EnumValuesDashboardIngestEventKind = map[string]DashboardIngestEventKind{
	"Stall":   DashboardIngestEventKindStall,
	"Reject":  DashboardIngestEventKindReject,
	"Recover": DashboardIngestEventKindRecover,
}

func (v DashboardIngestEventKind) String() string {
	if s, ok := EnumNamesDashboardIngestEventKind[v]; ok {
		return s
	}
	return "DashboardIngestEventKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
