// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One source-ingest transition surfaced to the dashboard.
type DashboardIngestEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsDashboardIngestEvent(buf []byte, offset flatbuffers.UOffsetT) *DashboardIngestEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DashboardIngestEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishDashboardIngestEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDashboardIngestEvent(buf []byte, offset flatbuffers.UOffsetT) *DashboardIngestEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DashboardIngestEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDashboardIngestEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DashboardIngestEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DashboardIngestEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DashboardIngestEvent) KIND() DashboardIngestEventKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return DashboardIngestEventKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DashboardIngestEvent) Kind() DashboardIngestEventKind {
	return rcv.KIND()
}

func (rcv *DashboardIngestEvent) MutateKIND(n DashboardIngestEventKind) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *DashboardIngestEvent) MutateKind(n DashboardIngestEventKind) bool {
	return rcv.MutateKIND(n)
}

func (rcv *DashboardIngestEvent) SCHEMA() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardIngestEvent) Schema() []byte {
	return rcv.SCHEMA()
}

func (rcv *DashboardIngestEvent) PROVIDER_ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardIngestEvent) ProviderId() []byte {
	return rcv.PROVIDER_ID()
}

func (rcv *DashboardIngestEvent) SOURCE_NAME() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardIngestEvent) SourceName() []byte {
	return rcv.SOURCE_NAME()
}

func (rcv *DashboardIngestEvent) MESSAGE() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardIngestEvent) Message() []byte {
	return rcv.MESSAGE()
}

func (rcv *DashboardIngestEvent) COUNT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardIngestEvent) Count() int64 {
	return rcv.COUNT()
}

func (rcv *DashboardIngestEvent) MutateCOUNT(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *DashboardIngestEvent) MutateCount(n int64) bool {
	return rcv.MutateCOUNT(n)
}

/// Unix seconds when the transition occurred.
func (rcv *DashboardIngestEvent) AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardIngestEvent) At() int64 {
	return rcv.AT()
}

/// Unix seconds when the transition occurred.
func (rcv *DashboardIngestEvent) MutateAT(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *DashboardIngestEvent) MutateAt(n int64) bool {
	return rcv.MutateAT(n)
}

func DashboardIngestEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func DashboardIngestEventAddKIND(builder *flatbuffers.Builder, KIND DashboardIngestEventKind) {
	builder.PrependInt8Slot(0, int8(KIND), 0)
}
func DashboardIngestEventAddKind(builder *flatbuffers.Builder, KIND DashboardIngestEventKind) {
	DashboardIngestEventAddKIND(builder, KIND)
}
func DashboardIngestEventAddSCHEMA(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(SCHEMA), 0)
}
func DashboardIngestEventAddSchema(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	DashboardIngestEventAddSCHEMA(builder, SCHEMA)
}
func DashboardIngestEventAddPROVIDER_ID(builder *flatbuffers.Builder, PROVIDER_ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(PROVIDER_ID), 0)
}
func DashboardIngestEventAddProviderId(builder *flatbuffers.Builder, PROVIDER_ID flatbuffers.UOffsetT) {
	DashboardIngestEventAddPROVIDER_ID(builder, PROVIDER_ID)
}
func DashboardIngestEventAddSOURCE_NAME(builder *flatbuffers.Builder, SOURCE_NAME flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(SOURCE_NAME), 0)
}
func DashboardIngestEventAddSourceName(builder *flatbuffers.Builder, SOURCE_NAME flatbuffers.UOffsetT) {
	DashboardIngestEventAddSOURCE_NAME(builder, SOURCE_NAME)
}
func DashboardIngestEventAddMESSAGE(builder *flatbuffers.Builder, MESSAGE flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(MESSAGE), 0)
}
func DashboardIngestEventAddMessage(builder *flatbuffers.Builder, MESSAGE flatbuffers.UOffsetT) {
	DashboardIngestEventAddMESSAGE(builder, MESSAGE)
}
func DashboardIngestEventAddCOUNT(builder *flatbuffers.Builder, COUNT int64) {
	builder.PrependInt64Slot(5, COUNT, 0)
}
func DashboardIngestEventAddCount(builder *flatbuffers.Builder, COUNT int64) {
	DashboardIngestEventAddCOUNT(builder, COUNT)
}
func DashboardIngestEventAddAT(builder *flatbuffers.Builder, AT int64) {
	builder.PrependInt64Slot(6, AT, 0)
}
func DashboardIngestEventAddAt(builder *flatbuffers.Builder, AT int64) {
	DashboardIngestEventAddAT(builder, AT)
}
func DashboardIngestEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
