// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DashboardStatsSet struct {
	_tab flatbuffers.Table
}

const DashboardStatsSetIdentifier = "$NDS"

func GetRootAsDashboardStatsSet(buf []byte, offset flatbuffers.UOffsetT) *DashboardStatsSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DashboardStatsSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishDashboardStatsSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(DashboardStatsSetIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func DashboardStatsSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, DashboardStatsSetIdentifier)
}

func GetSizePrefixedRootAsDashboardStatsSet(buf []byte, offset flatbuffers.UOffsetT) *DashboardStatsSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DashboardStatsSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDashboardStatsSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(DashboardStatsSetIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedDashboardStatsSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, DashboardStatsSetIdentifier)
}

func (rcv *DashboardStatsSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DashboardStatsSet) Table() flatbuffers.Table {
	return rcv._tab
}

/// Unix seconds when this snapshot was assembled
func (rcv *DashboardStatsSet) GENERATED_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardStatsSet) GeneratedAt() int64 {
	return rcv.GENERATED_AT()
}

/// Unix seconds when this snapshot was assembled
func (rcv *DashboardStatsSet) MutateGENERATED_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *DashboardStatsSet) MutateGeneratedAt(n int64) bool {
	return rcv.MutateGENERATED_AT(n)
}

func (rcv *DashboardStatsSet) SCHEMAS(obj *DashboardSchemaStat, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(DashboardSchemaStat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DashboardStatsSet) Schemas(obj *DashboardSchemaStat, j int) bool {
	return rcv.SCHEMAS(obj, j)
}

func (rcv *DashboardStatsSet) SCHEMASLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DashboardStatsSet) SchemasLength() int {
	return rcv.SCHEMASLength()
}

func (rcv *DashboardStatsSet) SOURCES(obj *DashboardSourceStat, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(DashboardSourceStat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DashboardStatsSet) Sources(obj *DashboardSourceStat, j int) bool {
	return rcv.SOURCES(obj, j)
}

func (rcv *DashboardStatsSet) SOURCESLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DashboardStatsSet) SourcesLength() int {
	return rcv.SOURCESLength()
}

func (rcv *DashboardStatsSet) TOTAL_RECORDS() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardStatsSet) TotalRecords() int64 {
	return rcv.TOTAL_RECORDS()
}

func (rcv *DashboardStatsSet) MutateTOTAL_RECORDS(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *DashboardStatsSet) MutateTotalRecords(n int64) bool {
	return rcv.MutateTOTAL_RECORDS(n)
}

func (rcv *DashboardStatsSet) TOTAL_BYTES() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardStatsSet) TotalBytes() int64 {
	return rcv.TOTAL_BYTES()
}

func (rcv *DashboardStatsSet) MutateTOTAL_BYTES(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *DashboardStatsSet) MutateTotalBytes(n int64) bool {
	return rcv.MutateTOTAL_BYTES(n)
}

/// True when the assembling read hit its store budget and this set carries
/// the last-known-good numbers. A stale snapshot is reported AS stale —
/// never as a confident zero.
func (rcv *DashboardStatsSet) STALE() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DashboardStatsSet) Stale() bool {
	return rcv.STALE()
}

/// True when the assembling read hit its store budget and this set carries
/// the last-known-good numbers. A stale snapshot is reported AS stale —
/// never as a confident zero.
func (rcv *DashboardStatsSet) MutateSTALE(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *DashboardStatsSet) MutateStale(n bool) bool {
	return rcv.MutateSTALE(n)
}

/// Unix seconds the store numbers were last true; 0 = never read
func (rcv *DashboardStatsSet) AS_OF() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardStatsSet) AsOf() int64 {
	return rcv.AS_OF()
}

/// Unix seconds the store numbers were last true; 0 = never read
func (rcv *DashboardStatsSet) MutateAS_OF(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *DashboardStatsSet) MutateAsOf(n int64) bool {
	return rcv.MutateAS_OF(n)
}

func (rcv *DashboardStatsSet) EVENTS(obj *DashboardIngestEvent, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(DashboardIngestEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DashboardStatsSet) Events(obj *DashboardIngestEvent, j int) bool {
	return rcv.EVENTS(obj, j)
}

func (rcv *DashboardStatsSet) EVENTSLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DashboardStatsSet) EventsLength() int {
	return rcv.EVENTSLength()
}

func (rcv *DashboardStatsSet) TOPICS(obj *DashboardTopicStat, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(DashboardTopicStat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DashboardStatsSet) Topics(obj *DashboardTopicStat, j int) bool {
	return rcv.TOPICS(obj, j)
}

func (rcv *DashboardStatsSet) TOPICSLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DashboardStatsSet) TopicsLength() int {
	return rcv.TOPICSLength()
}

func DashboardStatsSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func DashboardStatsSetAddGENERATED_AT(builder *flatbuffers.Builder, GENERATED_AT int64) {
	builder.PrependInt64Slot(0, GENERATED_AT, 0)
}
func DashboardStatsSetAddGeneratedAt(builder *flatbuffers.Builder, GENERATED_AT int64) {
	DashboardStatsSetAddGENERATED_AT(builder, GENERATED_AT)
}
func DashboardStatsSetAddSCHEMAS(builder *flatbuffers.Builder, SCHEMAS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(SCHEMAS), 0)
}
func DashboardStatsSetAddSchemas(builder *flatbuffers.Builder, SCHEMAS flatbuffers.UOffsetT) {
	DashboardStatsSetAddSCHEMAS(builder, SCHEMAS)
}
func DashboardStatsSetStartSCHEMASVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DashboardStatsSetStartSchemasVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return DashboardStatsSetStartSCHEMASVector(builder, numElems)
}
func DashboardStatsSetAddSOURCES(builder *flatbuffers.Builder, SOURCES flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(SOURCES), 0)
}
func DashboardStatsSetAddSources(builder *flatbuffers.Builder, SOURCES flatbuffers.UOffsetT) {
	DashboardStatsSetAddSOURCES(builder, SOURCES)
}
func DashboardStatsSetStartSOURCESVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DashboardStatsSetStartSourcesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return DashboardStatsSetStartSOURCESVector(builder, numElems)
}
func DashboardStatsSetAddTOTAL_RECORDS(builder *flatbuffers.Builder, TOTAL_RECORDS int64) {
	builder.PrependInt64Slot(3, TOTAL_RECORDS, 0)
}
func DashboardStatsSetAddTotalRecords(builder *flatbuffers.Builder, TOTAL_RECORDS int64) {
	DashboardStatsSetAddTOTAL_RECORDS(builder, TOTAL_RECORDS)
}
func DashboardStatsSetAddTOTAL_BYTES(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	builder.PrependInt64Slot(4, TOTAL_BYTES, 0)
}
func DashboardStatsSetAddTotalBytes(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	DashboardStatsSetAddTOTAL_BYTES(builder, TOTAL_BYTES)
}
func DashboardStatsSetAddSTALE(builder *flatbuffers.Builder, STALE bool) {
	builder.PrependBoolSlot(5, STALE, false)
}
func DashboardStatsSetAddStale(builder *flatbuffers.Builder, STALE bool) {
	DashboardStatsSetAddSTALE(builder, STALE)
}
func DashboardStatsSetAddAS_OF(builder *flatbuffers.Builder, AS_OF int64) {
	builder.PrependInt64Slot(6, AS_OF, 0)
}
func DashboardStatsSetAddAsOf(builder *flatbuffers.Builder, AS_OF int64) {
	DashboardStatsSetAddAS_OF(builder, AS_OF)
}
func DashboardStatsSetAddEVENTS(builder *flatbuffers.Builder, EVENTS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(EVENTS), 0)
}
func DashboardStatsSetAddEvents(builder *flatbuffers.Builder, EVENTS flatbuffers.UOffsetT) {
	DashboardStatsSetAddEVENTS(builder, EVENTS)
}
func DashboardStatsSetStartEVENTSVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DashboardStatsSetStartEventsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return DashboardStatsSetStartEVENTSVector(builder, numElems)
}
func DashboardStatsSetAddTOPICS(builder *flatbuffers.Builder, TOPICS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(TOPICS), 0)
}
func DashboardStatsSetAddTopics(builder *flatbuffers.Builder, TOPICS flatbuffers.UOffsetT) {
	DashboardStatsSetAddTOPICS(builder, TOPICS)
}
func DashboardStatsSetStartTOPICSVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DashboardStatsSetStartTopicsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return DashboardStatsSetStartTOPICSVector(builder, numElems)
}
func DashboardStatsSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
