// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One (schema, provider, source, batch) ingest lane's live progress.
type DashboardSourceStat struct {
	_tab flatbuffers.Table
}

func GetRootAsDashboardSourceStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardSourceStat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DashboardSourceStat{}
	x.Init(buf, n+offset)
	return x
}

func FinishDashboardSourceStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDashboardSourceStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardSourceStat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DashboardSourceStat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDashboardSourceStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DashboardSourceStat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DashboardSourceStat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DashboardSourceStat) SCHEMA() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardSourceStat) Schema() []byte {
	return rcv.SCHEMA()
}

func (rcv *DashboardSourceStat) PROVIDER_ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardSourceStat) ProviderId() []byte {
	return rcv.PROVIDER_ID()
}

func (rcv *DashboardSourceStat) SOURCE_NAME() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardSourceStat) SourceName() []byte {
	return rcv.SOURCE_NAME()
}

func (rcv *DashboardSourceStat) BATCH_ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardSourceStat) BatchId() []byte {
	return rcv.BATCH_ID()
}

func (rcv *DashboardSourceStat) RECORD_COUNT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSourceStat) RecordCount() int64 {
	return rcv.RECORD_COUNT()
}

func (rcv *DashboardSourceStat) MutateRECORD_COUNT(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *DashboardSourceStat) MutateRecordCount(n int64) bool {
	return rcv.MutateRECORD_COUNT(n)
}

func (rcv *DashboardSourceStat) TOTAL_BYTES() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSourceStat) TotalBytes() int64 {
	return rcv.TOTAL_BYTES()
}

func (rcv *DashboardSourceStat) MutateTOTAL_BYTES(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *DashboardSourceStat) MutateTotalBytes(n int64) bool {
	return rcv.MutateTOTAL_BYTES(n)
}

/// Unix seconds; 0 = unknown
func (rcv *DashboardSourceStat) FIRST_INGEST_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSourceStat) FirstIngestAt() int64 {
	return rcv.FIRST_INGEST_AT()
}

/// Unix seconds; 0 = unknown
func (rcv *DashboardSourceStat) MutateFIRST_INGEST_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *DashboardSourceStat) MutateFirstIngestAt(n int64) bool {
	return rcv.MutateFIRST_INGEST_AT(n)
}

func (rcv *DashboardSourceStat) LAST_INGEST_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSourceStat) LastIngestAt() int64 {
	return rcv.LAST_INGEST_AT()
}

func (rcv *DashboardSourceStat) MutateLAST_INGEST_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *DashboardSourceStat) MutateLastIngestAt(n int64) bool {
	return rcv.MutateLAST_INGEST_AT(n)
}

func (rcv *DashboardSourceStat) UPDATED_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSourceStat) UpdatedAt() int64 {
	return rcv.UPDATED_AT()
}

func (rcv *DashboardSourceStat) MutateUPDATED_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *DashboardSourceStat) MutateUpdatedAt(n int64) bool {
	return rcv.MutateUPDATED_AT(n)
}

func DashboardSourceStatStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func DashboardSourceStatAddSCHEMA(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(SCHEMA), 0)
}
func DashboardSourceStatAddSchema(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	DashboardSourceStatAddSCHEMA(builder, SCHEMA)
}
func DashboardSourceStatAddPROVIDER_ID(builder *flatbuffers.Builder, PROVIDER_ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(PROVIDER_ID), 0)
}
func DashboardSourceStatAddProviderId(builder *flatbuffers.Builder, PROVIDER_ID flatbuffers.UOffsetT) {
	DashboardSourceStatAddPROVIDER_ID(builder, PROVIDER_ID)
}
func DashboardSourceStatAddSOURCE_NAME(builder *flatbuffers.Builder, SOURCE_NAME flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(SOURCE_NAME), 0)
}
func DashboardSourceStatAddSourceName(builder *flatbuffers.Builder, SOURCE_NAME flatbuffers.UOffsetT) {
	DashboardSourceStatAddSOURCE_NAME(builder, SOURCE_NAME)
}
func DashboardSourceStatAddBATCH_ID(builder *flatbuffers.Builder, BATCH_ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(BATCH_ID), 0)
}
func DashboardSourceStatAddBatchId(builder *flatbuffers.Builder, BATCH_ID flatbuffers.UOffsetT) {
	DashboardSourceStatAddBATCH_ID(builder, BATCH_ID)
}
func DashboardSourceStatAddRECORD_COUNT(builder *flatbuffers.Builder, RECORD_COUNT int64) {
	builder.PrependInt64Slot(4, RECORD_COUNT, 0)
}
func DashboardSourceStatAddRecordCount(builder *flatbuffers.Builder, RECORD_COUNT int64) {
	DashboardSourceStatAddRECORD_COUNT(builder, RECORD_COUNT)
}
func DashboardSourceStatAddTOTAL_BYTES(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	builder.PrependInt64Slot(5, TOTAL_BYTES, 0)
}
func DashboardSourceStatAddTotalBytes(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	DashboardSourceStatAddTOTAL_BYTES(builder, TOTAL_BYTES)
}
func DashboardSourceStatAddFIRST_INGEST_AT(builder *flatbuffers.Builder, FIRST_INGEST_AT int64) {
	builder.PrependInt64Slot(6, FIRST_INGEST_AT, 0)
}
func DashboardSourceStatAddFirstIngestAt(builder *flatbuffers.Builder, FIRST_INGEST_AT int64) {
	DashboardSourceStatAddFIRST_INGEST_AT(builder, FIRST_INGEST_AT)
}
func DashboardSourceStatAddLAST_INGEST_AT(builder *flatbuffers.Builder, LAST_INGEST_AT int64) {
	builder.PrependInt64Slot(7, LAST_INGEST_AT, 0)
}
func DashboardSourceStatAddLastIngestAt(builder *flatbuffers.Builder, LAST_INGEST_AT int64) {
	DashboardSourceStatAddLAST_INGEST_AT(builder, LAST_INGEST_AT)
}
func DashboardSourceStatAddUPDATED_AT(builder *flatbuffers.Builder, UPDATED_AT int64) {
	builder.PrependInt64Slot(8, UPDATED_AT, 0)
}
func DashboardSourceStatAddUpdatedAt(builder *flatbuffers.Builder, UPDATED_AT int64) {
	DashboardSourceStatAddUPDATED_AT(builder, UPDATED_AT)
}
func DashboardSourceStatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
