// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One schema's record footprint in the FlatSQL store.
type DashboardSchemaStat struct {
	_tab flatbuffers.Table
}

func GetRootAsDashboardSchemaStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardSchemaStat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DashboardSchemaStat{}
	x.Init(buf, n+offset)
	return x
}

func FinishDashboardSchemaStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDashboardSchemaStat(buf []byte, offset flatbuffers.UOffsetT) *DashboardSchemaStat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DashboardSchemaStat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDashboardSchemaStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DashboardSchemaStat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DashboardSchemaStat) Table() flatbuffers.Table {
	return rcv._tab
}

/// SDS schema name, e.g. "OMM"
func (rcv *DashboardSchemaStat) SCHEMA() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DashboardSchemaStat) Schema() []byte {
	return rcv.SCHEMA()
}

/// SDS schema name, e.g. "OMM"
func (rcv *DashboardSchemaStat) RECORD_COUNT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSchemaStat) RecordCount() int64 {
	return rcv.RECORD_COUNT()
}

func (rcv *DashboardSchemaStat) MutateRECORD_COUNT(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *DashboardSchemaStat) MutateRecordCount(n int64) bool {
	return rcv.MutateRECORD_COUNT(n)
}

func (rcv *DashboardSchemaStat) TOTAL_BYTES() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DashboardSchemaStat) TotalBytes() int64 {
	return rcv.TOTAL_BYTES()
}

func (rcv *DashboardSchemaStat) MutateTOTAL_BYTES(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *DashboardSchemaStat) MutateTotalBytes(n int64) bool {
	return rcv.MutateTOTAL_BYTES(n)
}

func DashboardSchemaStatStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DashboardSchemaStatAddSCHEMA(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(SCHEMA), 0)
}
func DashboardSchemaStatAddSchema(builder *flatbuffers.Builder, SCHEMA flatbuffers.UOffsetT) {
	DashboardSchemaStatAddSCHEMA(builder, SCHEMA)
}
func DashboardSchemaStatAddRECORD_COUNT(builder *flatbuffers.Builder, RECORD_COUNT int64) {
	builder.PrependInt64Slot(1, RECORD_COUNT, 0)
}
func DashboardSchemaStatAddRecordCount(builder *flatbuffers.Builder, RECORD_COUNT int64) {
	DashboardSchemaStatAddRECORD_COUNT(builder, RECORD_COUNT)
}
func DashboardSchemaStatAddTOTAL_BYTES(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	builder.PrependInt64Slot(2, TOTAL_BYTES, 0)
}
func DashboardSchemaStatAddTotalBytes(builder *flatbuffers.Builder, TOTAL_BYTES int64) {
	DashboardSchemaStatAddTOTAL_BYTES(builder, TOTAL_BYTES)
}
func DashboardSchemaStatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
