// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NodeStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsNodeStatus(buf []byte, offset flatbuffers.UOffsetT) *NodeStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeStatus{}
	x.Init(buf, n+offset)
	return x
}

func FinishNodeStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNodeStatus(buf []byte, offset flatbuffers.UOffsetT) *NodeStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NodeStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNodeStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NodeStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeStatus) Table() flatbuffers.Table {
	return rcv._tab
}

/// libp2p peer ID (base58)
func (rcv *NodeStatus) PEER_ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) PeerId() []byte {
	return rcv.PEER_ID()
}

/// libp2p peer ID (base58)
/// Distinguished name from the node's EPM
func (rcv *NodeStatus) DN() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) Dn() []byte {
	return rcv.DN()
}

/// Distinguished name from the node's EPM
func (rcv *NodeStatus) ORGANIZATION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) Organization() []byte {
	return rcv.ORGANIZATION()
}

func (rcv *NodeStatus) TRUST_LEVEL() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) TrustLevel() []byte {
	return rcv.TRUST_LEVEL()
}

func (rcv *NodeStatus) ROLE() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) Role() []byte {
	return rcv.ROLE()
}

func (rcv *NodeStatus) AGENT_VERSION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) AgentVersion() []byte {
	return rcv.AGENT_VERSION()
}

/// Multiaddrs the peer is known by
func (rcv *NodeStatus) MULTIFORMAT_ADDRESS(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *NodeStatus) MultiformatAddress(j int) []byte {
	return rcv.MULTIFORMAT_ADDRESS(j)
}

func (rcv *NodeStatus) MULTIFORMAT_ADDRESSLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NodeStatus) MultiformatAddressLength() int {
	return rcv.MULTIFORMAT_ADDRESSLength()
}

/// Multiaddrs the peer is known by
/// Unix seconds of last observation (0 = never)
func (rcv *NodeStatus) LAST_SEEN() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NodeStatus) LastSeen() int64 {
	return rcv.LAST_SEEN()
}

/// Unix seconds of last observation (0 = never)
func (rcv *NodeStatus) MutateLAST_SEEN(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *NodeStatus) MutateLastSeen(n int64) bool {
	return rcv.MutateLAST_SEEN(n)
}

func (rcv *NodeStatus) IS_ONLINE() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *NodeStatus) IsOnline() bool {
	return rcv.IS_ONLINE()
}

func (rcv *NodeStatus) MutateIS_ONLINE(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *NodeStatus) MutateIsOnline(n bool) bool {
	return rcv.MutateIS_ONLINE(n)
}

/// Round-trip latency to the peer, milliseconds (0 = unknown)
func (rcv *NodeStatus) LATENCY_MS() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NodeStatus) LatencyMs() float32 {
	return rcv.LATENCY_MS()
}

/// Round-trip latency to the peer, milliseconds (0 = unknown)
func (rcv *NodeStatus) MutateLATENCY_MS(n float32) bool {
	return rcv._tab.MutateFloat32Slot(22, n)
}

func (rcv *NodeStatus) MutateLatencyMs(n float32) bool {
	return rcv.MutateLATENCY_MS(n)
}

/// Full vCard 4.0 text derived from the peer's EPM
func (rcv *NodeStatus) VCARD() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) Vcard() []byte {
	return rcv.VCARD()
}

/// Full vCard 4.0 text derived from the peer's EPM
/// GeoIP-resolved coordinates (0,0 = unresolved)
func (rcv *NodeStatus) LAT() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NodeStatus) Lat() float32 {
	return rcv.LAT()
}

/// GeoIP-resolved coordinates (0,0 = unresolved)
func (rcv *NodeStatus) MutateLAT(n float32) bool {
	return rcv._tab.MutateFloat32Slot(26, n)
}

func (rcv *NodeStatus) MutateLat(n float32) bool {
	return rcv.MutateLAT(n)
}

func (rcv *NodeStatus) LON() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NodeStatus) Lon() float32 {
	return rcv.LON()
}

func (rcv *NodeStatus) MutateLON(n float32) bool {
	return rcv._tab.MutateFloat32Slot(28, n)
}

func (rcv *NodeStatus) MutateLon(n float32) bool {
	return rcv.MutateLON(n)
}

func (rcv *NodeStatus) GEO_COUNTRY() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) GeoCountry() []byte {
	return rcv.GEO_COUNTRY()
}

func (rcv *NodeStatus) GEO_CITY() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) GeoCity() []byte {
	return rcv.GEO_CITY()
}

/// True on the node emitting this set
func (rcv *NodeStatus) IS_SELF() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *NodeStatus) IsSelf() bool {
	return rcv.IS_SELF()
}

/// True on the node emitting this set
func (rcv *NodeStatus) MutateIS_SELF(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

func (rcv *NodeStatus) MutateIsSelf(n bool) bool {
	return rcv.MutateIS_SELF(n)
}

/// Seconds since the emitting process started (self only)
func (rcv *NodeStatus) UPTIME_S() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NodeStatus) UptimeS() int64 {
	return rcv.UPTIME_S()
}

/// Seconds since the emitting process started (self only)
func (rcv *NodeStatus) MutateUPTIME_S(n int64) bool {
	return rcv._tab.MutateInt64Slot(36, n)
}

func (rcv *NodeStatus) MutateUptimeS(n int64) bool {
	return rcv.MutateUPTIME_S(n)
}

func (rcv *NodeStatus) SUITE_VERSION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) SuiteVersion() []byte {
	return rcv.SUITE_VERSION()
}

func (rcv *NodeStatus) STANDARDS_VERSION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatus) StandardsVersion() []byte {
	return rcv.STANDARDS_VERSION()
}

func NodeStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(19)
}
func NodeStatusAddPEER_ID(builder *flatbuffers.Builder, PEER_ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PEER_ID), 0)
}
func NodeStatusAddPeerId(builder *flatbuffers.Builder, PEER_ID flatbuffers.UOffsetT) {
	NodeStatusAddPEER_ID(builder, PEER_ID)
}
func NodeStatusAddDN(builder *flatbuffers.Builder, DN flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(DN), 0)
}
func NodeStatusAddDn(builder *flatbuffers.Builder, DN flatbuffers.UOffsetT) {
	NodeStatusAddDN(builder, DN)
}
func NodeStatusAddORGANIZATION(builder *flatbuffers.Builder, ORGANIZATION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(ORGANIZATION), 0)
}
func NodeStatusAddOrganization(builder *flatbuffers.Builder, ORGANIZATION flatbuffers.UOffsetT) {
	NodeStatusAddORGANIZATION(builder, ORGANIZATION)
}
func NodeStatusAddTRUST_LEVEL(builder *flatbuffers.Builder, TRUST_LEVEL flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(TRUST_LEVEL), 0)
}
func NodeStatusAddTrustLevel(builder *flatbuffers.Builder, TRUST_LEVEL flatbuffers.UOffsetT) {
	NodeStatusAddTRUST_LEVEL(builder, TRUST_LEVEL)
}
func NodeStatusAddROLE(builder *flatbuffers.Builder, ROLE flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ROLE), 0)
}
func NodeStatusAddRole(builder *flatbuffers.Builder, ROLE flatbuffers.UOffsetT) {
	NodeStatusAddROLE(builder, ROLE)
}
func NodeStatusAddAGENT_VERSION(builder *flatbuffers.Builder, AGENT_VERSION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(AGENT_VERSION), 0)
}
func NodeStatusAddAgentVersion(builder *flatbuffers.Builder, AGENT_VERSION flatbuffers.UOffsetT) {
	NodeStatusAddAGENT_VERSION(builder, AGENT_VERSION)
}
func NodeStatusAddMULTIFORMAT_ADDRESS(builder *flatbuffers.Builder, MULTIFORMAT_ADDRESS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(MULTIFORMAT_ADDRESS), 0)
}
func NodeStatusAddMultiformatAddress(builder *flatbuffers.Builder, MULTIFORMAT_ADDRESS flatbuffers.UOffsetT) {
	NodeStatusAddMULTIFORMAT_ADDRESS(builder, MULTIFORMAT_ADDRESS)
}
func NodeStatusStartMULTIFORMAT_ADDRESSVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NodeStatusStartMultiformatAddressVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return NodeStatusStartMULTIFORMAT_ADDRESSVector(builder, numElems)
}
func NodeStatusAddLAST_SEEN(builder *flatbuffers.Builder, LAST_SEEN int64) {
	builder.PrependInt64Slot(7, LAST_SEEN, 0)
}
func NodeStatusAddLastSeen(builder *flatbuffers.Builder, LAST_SEEN int64) {
	NodeStatusAddLAST_SEEN(builder, LAST_SEEN)
}
func NodeStatusAddIS_ONLINE(builder *flatbuffers.Builder, IS_ONLINE bool) {
	builder.PrependBoolSlot(8, IS_ONLINE, false)
}
func NodeStatusAddIsOnline(builder *flatbuffers.Builder, IS_ONLINE bool) {
	NodeStatusAddIS_ONLINE(builder, IS_ONLINE)
}
func NodeStatusAddLATENCY_MS(builder *flatbuffers.Builder, LATENCY_MS float32) {
	builder.PrependFloat32Slot(9, LATENCY_MS, 0.0)
}
func NodeStatusAddLatencyMs(builder *flatbuffers.Builder, LATENCY_MS float32) {
	NodeStatusAddLATENCY_MS(builder, LATENCY_MS)
}
func NodeStatusAddVCARD(builder *flatbuffers.Builder, VCARD flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(VCARD), 0)
}
func NodeStatusAddVcard(builder *flatbuffers.Builder, VCARD flatbuffers.UOffsetT) {
	NodeStatusAddVCARD(builder, VCARD)
}
func NodeStatusAddLAT(builder *flatbuffers.Builder, LAT float32) {
	builder.PrependFloat32Slot(11, LAT, 0.0)
}
func NodeStatusAddLat(builder *flatbuffers.Builder, LAT float32) {
	NodeStatusAddLAT(builder, LAT)
}
func NodeStatusAddLON(builder *flatbuffers.Builder, LON float32) {
	builder.PrependFloat32Slot(12, LON, 0.0)
}
func NodeStatusAddLon(builder *flatbuffers.Builder, LON float32) {
	NodeStatusAddLON(builder, LON)
}
func NodeStatusAddGEO_COUNTRY(builder *flatbuffers.Builder, GEO_COUNTRY flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(GEO_COUNTRY), 0)
}
func NodeStatusAddGeoCountry(builder *flatbuffers.Builder, GEO_COUNTRY flatbuffers.UOffsetT) {
	NodeStatusAddGEO_COUNTRY(builder, GEO_COUNTRY)
}
func NodeStatusAddGEO_CITY(builder *flatbuffers.Builder, GEO_CITY flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(GEO_CITY), 0)
}
func NodeStatusAddGeoCity(builder *flatbuffers.Builder, GEO_CITY flatbuffers.UOffsetT) {
	NodeStatusAddGEO_CITY(builder, GEO_CITY)
}
func NodeStatusAddIS_SELF(builder *flatbuffers.Builder, IS_SELF bool) {
	builder.PrependBoolSlot(15, IS_SELF, false)
}
func NodeStatusAddIsSelf(builder *flatbuffers.Builder, IS_SELF bool) {
	NodeStatusAddIS_SELF(builder, IS_SELF)
}
func NodeStatusAddUPTIME_S(builder *flatbuffers.Builder, UPTIME_S int64) {
	builder.PrependInt64Slot(16, UPTIME_S, 0)
}
func NodeStatusAddUptimeS(builder *flatbuffers.Builder, UPTIME_S int64) {
	NodeStatusAddUPTIME_S(builder, UPTIME_S)
}
func NodeStatusAddSUITE_VERSION(builder *flatbuffers.Builder, SUITE_VERSION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(SUITE_VERSION), 0)
}
func NodeStatusAddSuiteVersion(builder *flatbuffers.Builder, SUITE_VERSION flatbuffers.UOffsetT) {
	NodeStatusAddSUITE_VERSION(builder, SUITE_VERSION)
}
func NodeStatusAddSTANDARDS_VERSION(builder *flatbuffers.Builder, STANDARDS_VERSION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(STANDARDS_VERSION), 0)
}
func NodeStatusAddStandardsVersion(builder *flatbuffers.Builder, STANDARDS_VERSION flatbuffers.UOffsetT) {
	NodeStatusAddSTANDARDS_VERSION(builder, STANDARDS_VERSION)
}
func NodeStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
