// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nst

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NodeStatusSet struct {
	_tab flatbuffers.Table
}

const NodeStatusSetIdentifier = "$NST"

func GetRootAsNodeStatusSet(buf []byte, offset flatbuffers.UOffsetT) *NodeStatusSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeStatusSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishNodeStatusSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(NodeStatusSetIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func NodeStatusSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, NodeStatusSetIdentifier)
}

func GetSizePrefixedRootAsNodeStatusSet(buf []byte, offset flatbuffers.UOffsetT) *NodeStatusSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NodeStatusSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNodeStatusSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(NodeStatusSetIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedNodeStatusSetBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, NodeStatusSetIdentifier)
}

func (rcv *NodeStatusSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeStatusSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NodeStatusSet) NODES(obj *NodeStatus, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(NodeStatus)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *NodeStatusSet) Nodes(obj *NodeStatus, j int) bool {
	return rcv.NODES(obj, j)
}

func (rcv *NodeStatusSet) NODESLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NodeStatusSet) NodesLength() int {
	return rcv.NODESLength()
}

/// Unix milliseconds when this set was generated
func (rcv *NodeStatusSet) GENERATED_AT() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NodeStatusSet) GeneratedAt() int64 {
	return rcv.GENERATED_AT()
}

/// Unix milliseconds when this set was generated
func (rcv *NodeStatusSet) MutateGENERATED_AT(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *NodeStatusSet) MutateGeneratedAt(n int64) bool {
	return rcv.MutateGENERATED_AT(n)
}

/// Peer ID of the emitting node
func (rcv *NodeStatusSet) SOURCE_PEER_ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeStatusSet) SourcePeerId() []byte {
	return rcv.SOURCE_PEER_ID()
}

/// Peer ID of the emitting node
func NodeStatusSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NodeStatusSetAddNODES(builder *flatbuffers.Builder, NODES flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(NODES), 0)
}
func NodeStatusSetAddNodes(builder *flatbuffers.Builder, NODES flatbuffers.UOffsetT) {
	NodeStatusSetAddNODES(builder, NODES)
}
func NodeStatusSetStartNODESVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NodeStatusSetStartNodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return NodeStatusSetStartNODESVector(builder, numElems)
}
func NodeStatusSetAddGENERATED_AT(builder *flatbuffers.Builder, GENERATED_AT int64) {
	builder.PrependInt64Slot(1, GENERATED_AT, 0)
}
func NodeStatusSetAddGeneratedAt(builder *flatbuffers.Builder, GENERATED_AT int64) {
	NodeStatusSetAddGENERATED_AT(builder, GENERATED_AT)
}
func NodeStatusSetAddSOURCE_PEER_ID(builder *flatbuffers.Builder, SOURCE_PEER_ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(SOURCE_PEER_ID), 0)
}
func NodeStatusSetAddSourcePeerId(builder *flatbuffers.Builder, SOURCE_PEER_ID flatbuffers.UOffsetT) {
	NodeStatusSetAddSOURCE_PEER_ID(builder, SOURCE_PEER_ID)
}
func NodeStatusSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
