// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package invoke

import (
	flatbuffers "github.com/google/flatbuffers/go"

	orbpro__stream "github.com/spacedatanetwork/sdn-server/internal/wasiplugin/fbs/orbpro/stream"
)

/// Canonical invoke result emitted by direct ABI and command-mode execution.
type PluginInvokeResponse struct {
	_tab flatbuffers.Table
}

const PluginInvokeResponseIdentifier = "PINS"

func GetRootAsPluginInvokeResponse(buf []byte, offset flatbuffers.UOffsetT) *PluginInvokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PluginInvokeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPluginInvokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PluginInvokeResponseIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func PluginInvokeResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, PluginInvokeResponseIdentifier)
}

func GetSizePrefixedRootAsPluginInvokeResponse(buf []byte, offset flatbuffers.UOffsetT) *PluginInvokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PluginInvokeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPluginInvokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PluginInvokeResponseIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedPluginInvokeResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, PluginInvokeResponseIdentifier)
}

func (rcv *PluginInvokeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PluginInvokeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

/// Method-specific status code. Zero conventionally indicates success.
func (rcv *PluginInvokeResponse) StatusCode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

/// Method-specific status code. Zero conventionally indicates success.
func (rcv *PluginInvokeResponse) MutateStatusCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

/// True when the method yielded before fully draining queued work.
func (rcv *PluginInvokeResponse) Yielded() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// True when the method yielded before fully draining queued work.
func (rcv *PluginInvokeResponse) MutateYielded(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

/// Remaining backlog, if known.
func (rcv *PluginInvokeResponse) BacklogRemaining() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Remaining backlog, if known.
func (rcv *PluginInvokeResponse) MutateBacklogRemaining(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

/// Output frames produced by the invocation, routed by port_id.
func (rcv *PluginInvokeResponse) OutputFrames(obj *orbpro__stream.TypedArenaBuffer, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(orbpro__stream.TypedArenaBuffer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PluginInvokeResponse) OutputFramesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Output frames produced by the invocation, routed by port_id.
/// Arena backing all output frame payload bytes.
func (rcv *PluginInvokeResponse) PayloadArena(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PluginInvokeResponse) PayloadArenaLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PluginInvokeResponse) PayloadArenaBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Arena backing all output frame payload bytes.
func (rcv *PluginInvokeResponse) MutatePayloadArena(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

/// Stable machine-readable error code when invocation fails.
func (rcv *PluginInvokeResponse) ErrorCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Stable machine-readable error code when invocation fails.
/// Human-readable error message when invocation fails.
func (rcv *PluginInvokeResponse) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Human-readable error message when invocation fails.
func PluginInvokeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func PluginInvokeResponseAddStatusCode(builder *flatbuffers.Builder, statusCode int32) {
	builder.PrependInt32Slot(0, statusCode, 0)
}
func PluginInvokeResponseAddYielded(builder *flatbuffers.Builder, yielded bool) {
	builder.PrependBoolSlot(1, yielded, false)
}
func PluginInvokeResponseAddBacklogRemaining(builder *flatbuffers.Builder, backlogRemaining uint32) {
	builder.PrependUint32Slot(2, backlogRemaining, 0)
}
func PluginInvokeResponseAddOutputFrames(builder *flatbuffers.Builder, outputFrames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(outputFrames), 0)
}
func PluginInvokeResponseStartOutputFramesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PluginInvokeResponseAddPayloadArena(builder *flatbuffers.Builder, payloadArena flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(payloadArena), 0)
}
func PluginInvokeResponseStartPayloadArenaVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PluginInvokeResponseAddErrorCode(builder *flatbuffers.Builder, errorCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(errorCode), 0)
}
func PluginInvokeResponseAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(errorMessage), 0)
}
func PluginInvokeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
