// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package invoke

import (
	flatbuffers "github.com/google/flatbuffers/go"

	orbpro__stream "github.com/spacedatanetwork/sdn-server/internal/wasiplugin/fbs/orbpro/stream"
)

/// Canonical invoke envelope consumed by direct ABI and command-mode execution.
type PluginInvokeRequest struct {
	_tab flatbuffers.Table
}

const PluginInvokeRequestIdentifier = "PINQ"

func GetRootAsPluginInvokeRequest(buf []byte, offset flatbuffers.UOffsetT) *PluginInvokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PluginInvokeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPluginInvokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PluginInvokeRequestIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func PluginInvokeRequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, PluginInvokeRequestIdentifier)
}

func GetSizePrefixedRootAsPluginInvokeRequest(buf []byte, offset flatbuffers.UOffsetT) *PluginInvokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PluginInvokeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPluginInvokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PluginInvokeRequestIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedPluginInvokeRequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, PluginInvokeRequestIdentifier)
}

func (rcv *PluginInvokeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PluginInvokeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

/// Stable method identifier from PluginManifest.methods.
func (rcv *PluginInvokeRequest) MethodId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Stable method identifier from PluginManifest.methods.
/// Input frames for the invocation, routed by TypedArenaBuffer.port_id.
func (rcv *PluginInvokeRequest) InputFrames(obj *orbpro__stream.TypedArenaBuffer, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(orbpro__stream.TypedArenaBuffer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PluginInvokeRequest) InputFramesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Input frames for the invocation, routed by TypedArenaBuffer.port_id.
/// Arena backing all input frame payload bytes.
func (rcv *PluginInvokeRequest) PayloadArena(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PluginInvokeRequest) PayloadArenaLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PluginInvokeRequest) PayloadArenaBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Arena backing all input frame payload bytes.
func (rcv *PluginInvokeRequest) MutatePayloadArena(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PluginInvokeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PluginInvokeRequestAddMethodId(builder *flatbuffers.Builder, methodId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(methodId), 0)
}
func PluginInvokeRequestAddInputFrames(builder *flatbuffers.Builder, inputFrames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(inputFrames), 0)
}
func PluginInvokeRequestStartInputFramesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PluginInvokeRequestAddPayloadArena(builder *flatbuffers.Builder, payloadArena flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payloadArena), 0)
}
func PluginInvokeRequestStartPayloadArenaVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PluginInvokeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
