package format4proof

// Encrypted fields (owner, 2026-10-04: "make sure that encrypted fields work as
// well"; contract C-46, ENCRYPTED-FIELDS.md): records whose fields a client
// encrypted, stored through SDN on fresh format-1 and format-4 stores with the
// same writes and read back through every surface, the engine treating them as
// the opaque FlatBuffers they are. DriveEncryptedFields beside DriveFeedNames:
//
//   - the records: KMF whose KEY_BYTES the client encrypted with the
//     flatbuffers field-encryption API (format 3, the generated KMF walk
//     program); LGR grants whose content-key payload is an ecies.SealField
//     field with its $ENC header, and the ecies.Wrap shape ($ENC naming
//     ROOT_TYPE KMF, a KMF payload); OMM and MPE whose scalar (NORAD_CAT_ID,
//     MEAN_MOTION) or string (OBJECT_ID, OBJECT_NAME, EPOCH, ENTITY_ID)
//     fields the client encrypted (a client schema variant marking them
//     (encrypted)): fields the index rules and full text read. Even records
//     go tagged (one StoreBatchWithSourceTags per class, its own feed), odd
//     ones untagged (one Store each, local). SDN also seals every KMF record
//     at rest (C-25: an SDF1 envelope to the store's key; whole-record
//     sealing itself is SDN's suite: storage's
//     TestFormat4SealedRecordsMatchFormat1);
//   - every read surface on format 4 equals format 1 field by field, outside
//     the named rulings (encRulings: C-9, C-41 N3, C-39 E7, R18, C-48 (a),
//     (b)); every record a read returns is the
//     written bytes and decrypts with the throwaway keys to the plaintext;
//   - on disk: format 4's streams walk to EOF as [u32 size][record] frames
//     holding the client's ciphertext; no plaintext (raw, hex, base64, the
//     scalars as text) in any file of either store, open or closed; the
//     stock-reader check (enc-reader-check.py: stock flatbuffers, the SDS
//     Python readers and the generated decryption, no FlatSQL or SDN code)
//     parses and decrypts every frame of the format-4 and migrated stores;
//   - store-migrate --to 4 of the format-1 store answers as format 1 does;
//   - the full-text regression of records aligned to a size prefix SDN cut
//     off (C-46 (3), I1): OMM records cut out of SDN's size-prefixed builder
//     beside the same records finished bare; format 4 finds them as format 1
//     does (the 3.7.0 engine found none of the cut ones).
//
// Every key is a throwaway made here (crypto/rand). The stores'
// field-encryption identity is pre-provisioned with a throwaway X25519 pair,
// so the sealed frames open with a key this driver made. SDN pins SDS lib/go
// 1.228.0, whose KMF package predates the format-3 API, so the generated
// walker (lib/go 1.232) is carried below verbatim; the Python check decrypts
// with the generated Python API, an independent implementation.

import (
	"bytes"
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	KMFfb "github.com/DigitalArsenal/spacedatastandards.org/lib/go/KMF"
	LGRfb "github.com/DigitalArsenal/spacedatastandards.org/lib/go/LGR"
	MPEfb "github.com/DigitalArsenal/spacedatastandards.org/lib/go/MPE"
	OMMfb "github.com/DigitalArsenal/spacedatastandards.org/lib/go/OMM"
	flatbuffers "github.com/google/flatbuffers/go"
	"golang.org/x/crypto/curve25519"

	"github.com/spacedatanetwork/sdn-server/internal/ecies"
	"github.com/spacedatanetwork/sdn-server/internal/encfield"
	"github.com/spacedatanetwork/sdn-server/internal/sds"
	"github.com/spacedatanetwork/sdn-server/internal/storage"
)

// ---- field-encryption format 3 (the generated walker, SDS lib/go 1.232 KMF) --
//
// Copied from the fork's generated Go (spacedatastandards.org lib/go/KMF/
// flatbuffers_encryption.go, "Code generated by the FlatBuffers compiler"):
// SDN pins lib/go v1.228.0, whose KMF package still carries the retired
// encryption-context API. The KMF walk program is the generated one; the
// OMM/MPE programs are a client's schema variant (the same op codes: 0 a
// scalar of arg bytes, 1 a string).

type fb3Err string

func (e fb3Err) Error() string { return string(e) }

type fb3Walk struct {
	buf     []byte
	program []int
	block   cipher.Block
	tables  map[int64]bool
	regions map[int64]bool
}

func (w *fb3Walk) fail(what string) { panic(fb3Err("FlatbuffersEncryption: " + what)) }
func (w *fb3Walk) check(pos, length int64) {
	size := int64(len(w.buf))
	if pos < 0 || length < 0 || pos > size || length > size-pos {
		w.fail(fmt.Sprintf("the buffer is malformed (offset %d out of bounds)", pos))
	}
}
func (w *fb3Walk) u16(pos int64) int64 {
	w.check(pos, 2)
	return int64(binary.LittleEndian.Uint16(w.buf[pos:]))
}
func (w *fb3Walk) u32(pos int64) int64 {
	w.check(pos, 4)
	return int64(binary.LittleEndian.Uint32(w.buf[pos:]))
}
func (w *fb3Walk) i32(pos int64) int64 {
	w.check(pos, 4)
	return int64(int32(binary.LittleEndian.Uint32(w.buf[pos:])))
}
func (w *fb3Walk) follow(pos int64) int64 {
	target := pos + w.u32(pos)
	w.check(target, 4)
	return target
}
func (w *fb3Walk) count(pos, elementSize int64) int64 {
	n := w.u32(pos)
	w.check(pos+4, n*elementSize)
	return n
}
func (w *fb3Walk) crypt(start, length int64) {
	if length == 0 || w.regions[start] {
		return
	}
	w.regions[start] = true
	if w.block == nil {
		return
	}
	iv := make([]byte, aes.BlockSize)
	binary.BigEndian.PutUint32(iv, uint32(start))
	region := w.buf[start : start+length]
	cipher.NewCTR(w.block, iv).XORKeyStream(region, region)
}
func (w *fb3Walk) str(pos int64) {
	s := w.follow(pos)
	n := w.u32(s)
	w.check(s+4, n+1)
	w.crypt(s+4, n)
}
func (w *fb3Walk) field(table, slot int64) int64 {
	vtable := table - w.i32(table)
	if slot+2 > w.u16(vtable) {
		return 0
	}
	if offset := w.u16(vtable + slot); offset != 0 {
		return table + offset
	}
	return 0
}
func (w *fb3Walk) enter(table int64, depth int) bool {
	if depth > 64 {
		w.fail("tables nested deeper than 64 levels")
	}
	if w.tables[table] {
		return false
	}
	w.tables[table] = true
	vtable := table - w.i32(table)
	w.check(vtable, 4)
	vtableSize, tableSize := w.u16(vtable), w.u16(vtable+2)
	if vtableSize < 4 || vtableSize&1 != 0 {
		w.fail("the buffer is malformed (bad vtable)")
	}
	w.check(vtable, vtableSize)
	w.check(table, tableSize)
	return true
}
func (w *fb3Walk) walk(index int, table int64, depth int) {
	if !w.enter(table, depth) {
		return
	}
	p := w.program
	at := p[1+index]
	ops := p[at]
	at++
	for op := 0; op < ops; op++ {
		kind, slot := p[at], int64(p[at+1])
		at += 2
		arg := 0
		switch kind {
		case 0, 2, 4, 5:
			arg = p[at]
			at++
		case 6, 7:
			w.fail("unions are not used by this driver")
		}
		loc := w.field(table, slot)
		if loc == 0 {
			continue
		}
		switch kind {
		case 0:
			w.check(loc, int64(arg))
			w.crypt(loc, int64(arg))
		case 1:
			w.str(loc)
		case 2:
			v := w.follow(loc)
			w.crypt(v+4, w.count(v, int64(arg))*int64(arg))
		case 3:
			v := w.follow(loc)
			n := w.count(v, 4)
			for i := int64(0); i < n; i++ {
				w.str(v + 4 + 4*i)
			}
		case 4:
			w.walk(arg, w.follow(loc), depth+1)
		case 5:
			v := w.follow(loc)
			n := w.count(v, 4)
			for i := int64(0); i < n; i++ {
				w.walk(arg, w.follow(v+4+4*i), depth+1)
			}
		}
	}
}

// fb3BufferKey is HKDF-SHA256(key, no salt, "flatbuffers-buffer-v3" || BE32(recordIndex)).
func fb3BufferKey(key []byte, recordIndex uint32) []byte {
	extract := hmac.New(sha256.New, make([]byte, sha256.Size))
	extract.Write(key)
	expand := hmac.New(sha256.New, extract.Sum(nil))
	info := []byte("flatbuffers-buffer-v3\x00\x00\x00\x00\x01")
	binary.BigEndian.PutUint32(info[21:], recordIndex)
	expand.Write(info)
	return expand.Sum(nil)
}

// fb3Crypt encrypts or decrypts (the same operation) buf in place.
func fb3Crypt(buf, key []byte, recordIndex uint32, program []int) (err error) {
	if len(key) != 32 {
		return fb3Err("FlatbuffersEncryption: the key must be 32 bytes")
	}
	defer func() {
		if r := recover(); r != nil {
			e, ok := r.(fb3Err)
			if !ok {
				panic(r)
			}
			err = e
		}
	}()
	root := int64(binary.LittleEndian.Uint32(buf))
	dry := &fb3Walk{buf: buf, program: program, tables: map[int64]bool{}, regions: map[int64]bool{}}
	dry.check(root, 4)
	dry.walk(0, root, 0)
	block, e := aes.NewCipher(fb3BufferKey(key, recordIndex))
	if e != nil {
		return e
	}
	w := &fb3Walk{buf: buf, program: program, block: block, tables: map[int64]bool{}, regions: map[int64]bool{}}
	w.walk(0, root, 0)
	return nil
}

// Walk programs: [tables, start of table 0, ops, (kind, vtable slot[, arg])...].
var (
	fb3ProgramKMF       = []int{1, 2, 1, 2, 12, 1}           // generated: KEY_BYTES [ubyte] (slot 12)
	fb3ProgramOMMScalar = []int{1, 2, 2, 0, 58, 4, 0, 30, 8} // NORAD_CAT_ID uint32 (58), MEAN_MOTION double (30)
	fb3ProgramOMMString = []int{1, 2, 2, 1, 12, 1, 10}       // OBJECT_ID (12), OBJECT_NAME (10)
	fb3ProgramOMMEpoch  = []int{1, 2, 1, 1, 26}              // EPOCH string (26)
	fb3ProgramMPEString = []int{1, 2, 1, 1, 4}               // ENTITY_ID (4)
	fb3ProgramMPEEpoch  = []int{1, 2, 1, 0, 6, 8}            // EPOCH double (6)
)

// ---- throwaway keys --------------------------------------------------------

type encKeys struct {
	KMFKey    []byte `json:"kmf_key_hex"`
	FieldKey  []byte `json:"field_key_hex"`
	RecipPriv []byte `json:"recipient_x25519_priv_hex"`
	RecipPub  []byte `json:"recipient_x25519_pub_hex"`
	StorePriv []byte `json:"store_x25519_priv_hex"`
	StorePub  []byte `json:"store_x25519_pub_hex"`
}

func rnd(n int) []byte {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return b
}

func newEncKeys() encKeys {
	k := encKeys{KMFKey: rnd(32), FieldKey: rnd(32), RecipPriv: rnd(32), StorePriv: rnd(32)}
	k.RecipPub, _ = curve25519.X25519(k.RecipPriv, curve25519.Basepoint)
	k.StorePub, _ = curve25519.X25519(k.StorePriv, curve25519.Basepoint)
	return k
}

func (k encKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]string{
		"note":                      "THROWAWAY TEST KEYS generated by format4proof DriveEncryptedFields (encfields.go, crypto/rand); not credentials",
		"kmf_key_hex":               hex.EncodeToString(k.KMFKey),
		"field_key_hex":             hex.EncodeToString(k.FieldKey),
		"recipient_x25519_priv_hex": hex.EncodeToString(k.RecipPriv),
		"recipient_x25519_pub_hex":  hex.EncodeToString(k.RecipPub),
		"store_x25519_priv_hex":     hex.EncodeToString(k.StorePriv),
		"store_x25519_pub_hex":      hex.EncodeToString(k.StorePub),
	})
}

// provisionStoreKey writes the store's field-encryption identity (SDN reads
// it when present, storage/field_encryption.go) before the first open.
func provisionStoreKey(dir string, k encKeys) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	b, _ := json.MarshalIndent(map[string]string{"public_key_hex": hex.EncodeToString(k.StorePub), "private_key_hex": hex.EncodeToString(k.StorePriv)}, "", "  ")
	return os.WriteFile(filepath.Join(dir, "field-encryption-identity.json"), b, 0o600)
}

// storeFieldEncryptionContext is storage's encfield context
// (field_encryption.go fieldEncryptionContext, unexported there).
const storeFieldEncryptionContext = "space-data-network/storage/field-encryption/v1"

// ---- records ---------------------------------------------------------------

// encField is one encrypted field of a written record.
type encField struct {
	Name   string `json:"name"`
	Kind   string `json:"kind"` // vector | string | u32 | f64 | ecies
	Plain  []byte `json:"plain"`
	Cipher []byte `json:"cipher"`
	// ecies: the field id and context SealField keyed it by.
	FieldID uint16 `json:"field_id,omitempty"`
	Context string `json:"context,omitempty"`
}

// encRec is one written record: exactly the bytes SDN was given.
type encRec struct {
	Type    string     `json:"type"` // "KMF.fbs"
	Class   string     `json:"class"`
	Tagged  bool       `json:"tagged"`
	CID     string     `json:"cid"`
	Bytes   []byte     `json:"bytes"`
	RecIdx  uint32     `json:"rec_idx"`
	Program []int      `json:"program,omitempty"`
	KeyName string     `json:"key,omitempty"` // kmf | field | recipient
	Fields  []encField `json:"fields"`
}

const (
	encProvider = "enc-proof-provider"
	encPeer     = "16Uiu2HAmEncProofProducerA11111111111111111111111111"
)

var encSig = []byte("enc-proof-signature-0123456789abcdef0123456789abcdef0123456789ab")

// encClass is one record class: its type, feed source and records.
type encClass struct {
	Name, Type string
	Recs       []*encRec
}

func (c encClass) source() string { return "enc-" + c.Name }
func (c encClass) batch() string  { return "enc-" + c.Name + "-b1" }

// sentinel is a recognizable, single-token (FTS5 unicode61) plaintext.
func sentinel(tag string, i int) []byte {
	const alnum = "abcdefghijklmnopqrstuvwxyz0123456789"
	r := rnd(12)
	out := []byte(fmt.Sprintf("ZQ%s%02dx", tag, i))
	for _, b := range r {
		out = append(out, alnum[int(b)%len(alnum)])
	}
	return out
}

func buildKMFRec(keys encKeys, i int) (*encRec, error) {
	plain := append(sentinel("KMFKEY", i), rnd(8)...) // 32 bytes
	b := flatbuffers.NewBuilder(256)
	keyID := b.CreateString(fmt.Sprintf("enc-kmf-%02d", i))
	kb := b.CreateByteVector(plain)
	KMFfb.KMFStart(b)
	KMFfb.KMFAddKEY_ID(b, keyID)
	KMFfb.KMFAddROLE(b, 4)      // DecryptKey
	KMFfb.KMFAddALGORITHM(b, 5) // Aes256Gcm
	KMFfb.KMFAddENCODING(b, 1)  // RawBytes
	KMFfb.KMFAddKEY_BYTES(b, kb)
	KMFfb.KMFAddVERSION(b, uint32(100+i))
	KMFfb.KMFAddEXPIRES_AT(b, 1893456000000)
	KMFfb.FinishKMFBuffer(b, KMFfb.KMFEnd(b))
	buf := append([]byte(nil), b.FinishedBytes()...)
	rec := &encRec{Type: "KMF.fbs", Class: "kmf-vector", RecIdx: uint32(1000 + i), Program: fb3ProgramKMF, KeyName: "kmf"}
	if err := fb3Crypt(buf, keys.KMFKey, rec.RecIdx, fb3ProgramKMF); err != nil {
		return nil, err
	}
	ct := append([]byte(nil), KMFfb.GetRootAsKMF(buf, 0).KEY_BYTESBytes()...)
	if bytes.Equal(ct, plain) {
		return nil, errors.New("KMF: KEY_BYTES unchanged by encryption")
	}
	rec.Bytes, rec.CID = buf, storage.ComputeCID(buf)
	rec.Fields = []encField{{Name: "KEY_BYTES", Kind: "vector", Plain: plain, Cipher: ct}}
	return rec, nil
}

// lgrENC is an ecies header as LGR's nested $ENC table.
func lgrENC(b *flatbuffers.Builder, h ecies.Header, rootType string) flatbuffers.UOffsetT {
	eph := b.CreateByteVector(h.EphemeralPub)
	nonce := b.CreateByteVector(h.NonceStart)
	var rid flatbuffers.UOffsetT
	if len(h.RecipientKeyID) > 0 {
		rid = b.CreateByteVector(h.RecipientKeyID)
	}
	ctx := b.CreateString(h.Context)
	var rt flatbuffers.UOffsetT
	if rootType != "" {
		rt = b.CreateString(rootType)
	}
	LGRfb.ENCStart(b)
	LGRfb.ENCAddVERSION(b, 1)
	LGRfb.ENCAddKEY_EXCHANGE(b, LGRfb.KeyExchange(h.KeyExchange))
	LGRfb.ENCAddEPHEMERAL_PUBLIC_KEY(b, eph)
	LGRfb.ENCAddNONCE_START(b, nonce)
	if rid != 0 {
		LGRfb.ENCAddRECIPIENT_KEY_ID(b, rid)
	}
	LGRfb.ENCAddCONTEXT(b, ctx)
	if rt != 0 {
		LGRfb.ENCAddROOT_TYPE(b, rt)
	}
	return LGRfb.ENCEnd(b)
}

const (
	lgrPayloadFieldID = 17 // LGR.WRAPPED_CONTENT_KEY_PAYLOAD
	lgrSealContext    = "enc-proof/lgr-payload/v1"
)

func buildLGR(i int, class string, header func(b *flatbuffers.Builder) flatbuffers.UOffsetT, payload []byte) []byte {
	b := flatbuffers.NewBuilder(1024)
	req := b.CreateString(fmt.Sprintf("enc-lgr-%s-%02d", class, i))
	mod := b.CreateString("encproofmodule")
	status := b.CreateString("granted")
	dom := b.CreateString("enc-proof.invalid")
	pl := b.CreateByteVector(payload)
	hdr := header(b)
	LGRfb.LGRStart(b)
	LGRfb.LGRAddMESSAGE_TYPE(b, 1) // Granted
	LGRfb.LGRAddREQUEST_ID(b, req)
	LGRfb.LGRAddMODULE_ID(b, mod)
	LGRfb.LGRAddGRANTED_DOMAIN(b, dom)
	LGRfb.LGRAddGRANTED_TIMEOUT_MS(b, 3600000)
	LGRfb.LGRAddEXPIRES_AT(b, 1893456000000)
	LGRfb.LGRAddGRANT_STATUS(b, status)
	LGRfb.LGRAddWRAPPED_CONTENT_KEY_HEADER(b, hdr)
	LGRfb.LGRAddWRAPPED_CONTENT_KEY_PAYLOAD(b, pl)
	LGRfb.FinishLGRBuffer(b, LGRfb.LGREnd(b))
	return append([]byte(nil), b.FinishedBytes()...)
}

// buildLGRSealField: the payload is an ecies.SealField field (field id 17)
// with its header in the record's $ENC table.
func buildLGRSealField(keys encKeys, i int) (*encRec, error) {
	plain := append(sentinel("LGRSEAL", i), rnd(16)...)
	h, ct, err := ecies.SealField(keys.RecipPub, plain, lgrPayloadFieldID, ecies.WrapOptions{KeyExchange: ecies.X25519, Context: lgrSealContext,
		RecipientKeyID: []byte("enc-proof-recipient")})
	if err != nil {
		return nil, err
	}
	buf := buildLGR(i, "sealfield", func(b *flatbuffers.Builder) flatbuffers.UOffsetT { return lgrENC(b, h, "") }, ct)
	return &encRec{Type: "LGR.fbs", Class: "lgr-sealfield", Bytes: buf, CID: storage.ComputeCID(buf), KeyName: "recipient",
		Fields: []encField{{Name: "WRAPPED_CONTENT_KEY_PAYLOAD", Kind: "ecies", Plain: plain, Cipher: ct, FieldID: lgrPayloadFieldID, Context: lgrSealContext}}}, nil
}

// buildLGRWrap: the grant shape (ecies.Wrap): $ENC header naming ROOT_TYPE
// KMF, the payload a KMF whose KEY_BYTES carries the wrapped content key.
func buildLGRWrap(keys encKeys, i int) (*encRec, error) {
	contentKey := append(sentinel("LGRWRAP", i), rnd(12)...)[:32]
	encBytes, kmfBytes, err := ecies.Wrap(keys.RecipPub, contentKey, ecies.WrapOptions{KeyExchange: ecies.X25519, Context: ecies.DefaultGrantContext})
	if err != nil {
		return nil, err
	}
	_ = encBytes
	// Re-read the standalone $ENC into a Header for the nested table.
	hdr, err := headerOfENC(encBytes)
	if err != nil {
		return nil, err
	}
	buf := buildLGR(i, "wrap", func(b *flatbuffers.Builder) flatbuffers.UOffsetT { return lgrENC(b, hdr, "KMF") }, kmfBytes)
	wrapped := append([]byte(nil), KMFfb.GetRootAsKMF(kmfBytes, 0).KEY_BYTESBytes()...)
	return &encRec{Type: "LGR.fbs", Class: "lgr-wrap", Bytes: buf, CID: storage.ComputeCID(buf), KeyName: "recipient",
		Fields: []encField{{Name: "WRAPPED_CONTENT_KEY_PAYLOAD.KMF.KEY_BYTES", Kind: "ecies", Plain: contentKey, Cipher: wrapped, FieldID: 4, Context: ecies.DefaultGrantContext}}}, nil
}

func headerOfENC(encBytes []byte) (ecies.Header, error) {
	if len(encBytes) < 8 || string(encBytes[4:8]) != "$ENC" {
		return ecies.Header{}, errors.New("not an $ENC buffer")
	}
	t := flatbuffers.Table{Bytes: encBytes, Pos: flatbuffers.GetUOffsetT(encBytes)}
	vec := func(slot flatbuffers.VOffsetT) []byte {
		if o := flatbuffers.UOffsetT(t.Offset(slot)); o != 0 {
			return append([]byte(nil), t.ByteVector(o+t.Pos)...)
		}
		return nil
	}
	var kx ecies.KeyExchange
	if o := flatbuffers.UOffsetT(t.Offset(6)); o != 0 {
		kx = ecies.KeyExchange(t.GetInt8(o + t.Pos))
	}
	return ecies.Header{KeyExchange: kx, EphemeralPub: vec(12), NonceStart: vec(14), RecipientKeyID: vec(16), Context: string(vec(18))}, nil
}

const encEpoch0 = 1789905600 // 2026-09-20T12:00:00Z

// ommPlain builds an OMM finished WITHOUT a size prefix (FinishOMMBuffer), so
// its 8-byte fields are aligned to the record's first byte, as the fixture's
// production OMM records are. (sds.NewOMMBuilder finishes size-prefixed; a
// record cut out of it has its doubles 4 bytes off, which format 4's full
// text refuses: TestEncProbeAlign.)
func ommPlain(name, objID string, norad uint32, mm float64, epoch string, epochTS float64) []byte {
	b := flatbuffers.NewBuilder(512)
	nm := b.CreateString(name)
	id := b.CreateString(objID)
	center := b.CreateString("EARTH")
	ep := b.CreateString(epoch)
	created := b.CreateString("2026-10-01T00:00:00Z")
	OMMfb.OMMStart(b)
	OMMfb.OMMAddCREATION_DATE(b, created)
	OMMfb.OMMAddOBJECT_NAME(b, nm)
	OMMfb.OMMAddOBJECT_ID(b, id)
	OMMfb.OMMAddCENTER_NAME(b, center)
	OMMfb.OMMAddEPOCH(b, ep)
	OMMfb.OMMAddMEAN_MOTION(b, mm)
	OMMfb.OMMAddECCENTRICITY(b, 0.0007)
	OMMfb.OMMAddINCLINATION(b, 51.6)
	OMMfb.OMMAddRA_OF_ASC_NODE(b, 120.5)
	OMMfb.OMMAddARG_OF_PERICENTER(b, 80.25)
	OMMfb.OMMAddMEAN_ANOMALY(b, 279.75)
	OMMfb.OMMAddNORAD_CAT_ID(b, norad)
	OMMfb.OMMAddBSTAR(b, 0.00012)
	OMMfb.OMMAddUSER_DEFINED_EPOCH_TIMESTAMP(b, epochTS)
	OMMfb.FinishOMMBuffer(b, OMMfb.OMMEnd(b))
	return append([]byte(nil), b.FinishedBytes()...)
}

// ommPlainPrefixed is the same record through SDN's size-prefixed builder,
// cut out of its prefix (crashRecords' shape): its doubles sit 4 bytes off.
func ommPlainPrefixed(name, objID string, norad uint32, mm float64, epoch string, epochTS float64) []byte {
	b := sds.NewOMMBuilder().
		WithNoradCatID(norad).
		WithObjectName(name).
		WithObjectID(objID).
		WithEpoch(epoch).
		WithEpochTimestamp(epochTS).
		WithMeanMotion(mm).
		WithEccentricity(0.0007).
		WithInclination(51.6).
		WithCreationDate("2026-10-01T00:00:00Z").
		Build()
	return append([]byte(nil), b[4:]...)
}

func epochTS(i int) float64 { return float64(encEpoch0 + int64(i)*60) }

func epochText(i int) string {
	return time.Unix(encEpoch0+int64(i)*60, 0).UTC().Format("2006-01-02T15:04:05.000000")
}

func u32le(v uint32) []byte { return binary.LittleEndian.AppendUint32(nil, v) }
func f64le(v float64) []byte {
	return binary.LittleEndian.AppendUint64(nil, math.Float64bits(v))
}

// buildOMMScalar: NORAD_CAT_ID (uint32) and MEAN_MOTION (double) encrypted;
// OBJECT_NAME stays plaintext ("ENCPROOF SCALAR i": the full-text control).
func buildOMMScalar(keys encKeys, i int) (*encRec, error) {
	norad := uint32(0x5EC20000 + i*7 + 1)
	mm := 15.48919103 + float64(i)/1024
	buf := ommPlain(fmt.Sprintf("ENCPROOF SCALAR %d", i), fmt.Sprintf("2026-%03dZ", 900+i), norad, mm, epochText(i), epochTS(i))
	rec := &encRec{Type: "OMM.fbs", Class: "omm-scalar", RecIdx: uint32(2000 + i), Program: fb3ProgramOMMScalar, KeyName: "field"}
	if err := fb3Crypt(buf, keys.FieldKey, rec.RecIdx, rec.Program); err != nil {
		return nil, err
	}
	o := OMMfb.GetRootAsOMM(buf, 0)
	rec.Bytes, rec.CID = buf, storage.ComputeCID(buf)
	rec.Fields = []encField{
		{Name: "NORAD_CAT_ID", Kind: "u32", Plain: u32le(norad), Cipher: u32le(o.NORAD_CAT_ID())},
		{Name: "MEAN_MOTION", Kind: "f64", Plain: f64le(mm), Cipher: f64le(o.MEAN_MOTION())},
	}
	return rec, nil
}

// buildOMMString: OBJECT_ID (the object key's second part, COL 1) and
// OBJECT_NAME (full text) encrypted: non-UTF-8 ciphertext in string fields.
func buildOMMString(keys encKeys, i int) (*encRec, error) {
	objID := sentinel("OBJID", i)
	name := sentinel("OMMNAME", i)
	norad := uint32(77100 + i)
	buf := ommPlain(string(name), string(objID), norad, 14.2+float64(i)/512, epochText(10+i), epochTS(10+i))
	rec := &encRec{Type: "OMM.fbs", Class: "omm-string", RecIdx: uint32(3000 + i), Program: fb3ProgramOMMString, KeyName: "field"}
	if err := fb3Crypt(buf, keys.FieldKey, rec.RecIdx, rec.Program); err != nil {
		return nil, err
	}
	o := OMMfb.GetRootAsOMM(buf, 0)
	rec.Bytes, rec.CID = buf, storage.ComputeCID(buf)
	rec.Fields = []encField{
		{Name: "OBJECT_ID", Kind: "string", Plain: objID, Cipher: append([]byte(nil), o.OBJECT_ID()...)},
		{Name: "OBJECT_NAME", Kind: "string", Plain: name, Cipher: append([]byte(nil), o.OBJECT_NAME()...)},
	}
	return rec, nil
}

// buildOMMEpoch: EPOCH (the epoch rule's string) encrypted.
func buildOMMEpoch(keys encKeys, i int) (*encRec, error) {
	ep := epochText(20 + i)
	buf := ommPlain(fmt.Sprintf("ENCPROOF EPOCH %d", i), fmt.Sprintf("2026-%03dE", 950+i), uint32(77200+i), 13.1, ep, epochTS(20+i))
	rec := &encRec{Type: "OMM.fbs", Class: "omm-epoch", RecIdx: uint32(4000 + i), Program: fb3ProgramOMMEpoch, KeyName: "field"}
	if err := fb3Crypt(buf, keys.FieldKey, rec.RecIdx, rec.Program); err != nil {
		return nil, err
	}
	o := OMMfb.GetRootAsOMM(buf, 0)
	rec.Bytes, rec.CID = buf, storage.ComputeCID(buf)
	rec.Fields = []encField{{Name: "EPOCH", Kind: "string", Plain: []byte(ep), Cipher: append([]byte(nil), o.EPOCH()...)}}
	return rec, nil
}

func mpePlain(entity string, epoch float64) []byte {
	b := flatbuffers.NewBuilder(256)
	id := b.CreateString(entity)
	MPEfb.MPEStart(b)
	MPEfb.MPEAddENTITY_ID(b, id)
	MPEfb.MPEAddEPOCH(b, epoch)
	MPEfb.MPEAddMEAN_MOTION(b, 15.1)
	MPEfb.MPEAddECCENTRICITY(b, 0.001)
	MPEfb.MPEAddINCLINATION(b, 97.4)
	MPEfb.MPEAddRA_OF_ASC_NODE(b, 10)
	MPEfb.MPEAddARG_OF_PERICENTER(b, 20)
	MPEfb.MPEAddMEAN_ANOMALY(b, 30)
	MPEfb.MPEAddBSTAR(b, 0.0001)
	MPEfb.FinishMPEBuffer(b, MPEfb.MPEEnd(b))
	return append([]byte(nil), b.FinishedBytes()...)
}

// buildMPEString: ENTITY_ID (MPE's object key, COL 1) encrypted.
func buildMPEString(keys encKeys, i int) (*encRec, error) {
	ent := sentinel("MPEENT", i)
	buf := mpePlain(string(ent), float64(encEpoch0+int64(30+i)*60)+0.25)
	rec := &encRec{Type: "MPE.fbs", Class: "mpe-string", RecIdx: uint32(5000 + i), Program: fb3ProgramMPEString, KeyName: "field"}
	if err := fb3Crypt(buf, keys.FieldKey, rec.RecIdx, rec.Program); err != nil {
		return nil, err
	}
	m := MPEfb.GetRootAsMPE(buf, 0)
	rec.Bytes, rec.CID = buf, storage.ComputeCID(buf)
	rec.Fields = []encField{{Name: "ENTITY_ID", Kind: "string", Plain: ent, Cipher: append([]byte(nil), m.ENTITY_ID()...)}}
	return rec, nil
}

// encClasses builds the main scenario's classes (n records each; even
// records are delivered tagged, in one StoreBatchWithSourceTags per class,
// odd ones untagged, one Store each).
func encClasses(keys encKeys) ([]encClass, error) {
	type maker struct {
		name, typ string
		n         int
		fn        func(encKeys, int) (*encRec, error)
	}
	makers := []maker{
		{"kmf-vector", "KMF.fbs", 6, buildKMFRec},
		{"lgr-sealfield", "LGR.fbs", 4, buildLGRSealField},
		{"lgr-wrap", "LGR.fbs", 4, buildLGRWrap},
		{"omm-scalar", "OMM.fbs", 4, buildOMMScalar},
		{"omm-string", "OMM.fbs", 4, buildOMMString},
		{"omm-epoch", "OMM.fbs", 2, buildOMMEpoch},
		{"mpe-string", "MPE.fbs", 4, buildMPEString},
	}
	var out []encClass
	for _, m := range makers {
		c := encClass{Name: m.name, Type: m.typ}
		for i := 0; i < m.n; i++ {
			r, err := m.fn(keys, i)
			if err != nil {
				return nil, fmt.Errorf("%s %d: %w", m.name, i, err)
			}
			r.Tagged = i%2 == 0
			c.Recs = append(c.Recs, r)
		}
		out = append(out, c)
	}
	return out, nil
}

// ---- decrypt checks (the throwaway keys) -----------------------------------

// decryptCheck opens rec's encrypted fields in data (the bytes a read
// returned) with the throwaway keys and compares them with the plaintexts.
func decryptCheck(keys encKeys, rec *encRec, data []byte) string {
	if !bytes.Equal(data, rec.Bytes) {
		return "bytes differ from the written record"
	}
	buf := append([]byte(nil), data...)
	switch rec.KeyName {
	case "kmf", "field":
		key := keys.KMFKey
		if rec.KeyName == "field" {
			key = keys.FieldKey
		}
		if err := fb3Crypt(buf, key, rec.RecIdx, rec.Program); err != nil {
			return "decrypt: " + err.Error()
		}
		for _, f := range rec.Fields {
			var got []byte
			switch rec.Type + "." + f.Name {
			case "KMF.fbs.KEY_BYTES":
				got = KMFfb.GetRootAsKMF(buf, 0).KEY_BYTESBytes()
			case "OMM.fbs.NORAD_CAT_ID":
				got = u32le(OMMfb.GetRootAsOMM(buf, 0).NORAD_CAT_ID())
			case "OMM.fbs.MEAN_MOTION":
				got = f64le(OMMfb.GetRootAsOMM(buf, 0).MEAN_MOTION())
			case "OMM.fbs.OBJECT_ID":
				got = OMMfb.GetRootAsOMM(buf, 0).OBJECT_ID()
			case "OMM.fbs.OBJECT_NAME":
				got = OMMfb.GetRootAsOMM(buf, 0).OBJECT_NAME()
			case "OMM.fbs.EPOCH":
				got = OMMfb.GetRootAsOMM(buf, 0).EPOCH()
			case "MPE.fbs.ENTITY_ID":
				got = MPEfb.GetRootAsMPE(buf, 0).ENTITY_ID()
			case "MPE.fbs.EPOCH":
				got = f64le(MPEfb.GetRootAsMPE(buf, 0).EPOCH())
			default:
				return "no accessor for " + f.Name
			}
			if !bytes.Equal(got, f.Plain) {
				return fmt.Sprintf("%s decrypts to %x, want %x", f.Name, got, f.Plain)
			}
		}
		return "ok"
	case "recipient":
		l := LGRfb.GetRootAsLGR(buf, 0)
		e := l.WRAPPED_CONTENT_KEY_HEADER(nil)
		if e == nil {
			return "no $ENC header"
		}
		h := ecies.Header{KeyExchange: ecies.KeyExchange(e.KEY_EXCHANGE()), EphemeralPub: e.EPHEMERAL_PUBLIC_KEYBytes(), NonceStart: e.NONCE_STARTBytes(),
			RecipientKeyID: e.RECIPIENT_KEY_IDBytes(), Context: string(e.CONTEXT())}
		payload := l.WrappedContentKeyPayloadBytes()
		f := rec.Fields[0]
		ct := payload
		if rec.Class == "lgr-wrap" {
			if string(e.ROOT_TYPE()) != "KMF" || !KMFfb.KMFBufferHasIdentifier(payload) {
				return "wrap payload is not a KMF named by ROOT_TYPE"
			}
			ct = KMFfb.GetRootAsKMF(payload, 0).KEY_BYTESBytes()
		}
		got, err := ecies.OpenField(keys.RecipPriv, h, ct, f.FieldID, f.Context)
		if err != nil {
			return "open: " + err.Error()
		}
		if !bytes.Equal(got, f.Plain) {
			return fmt.Sprintf("payload opens to %x, want %x", got, f.Plain)
		}
		return "ok"
	case "none":
		return "ok"
	}
	return "no key for " + rec.KeyName
}

// ---- reads -----------------------------------------------------------------

type encCall struct {
	Name string `json:"name"`
	Rows []Row  `json:"rows"`
}

// encScen canonicalizes the store clock: a time at or after t0 reads
// "now@j", j the last write that began at or before it (every write begins in
// a later second than the previous one ended in).
type encScen struct {
	t0     int64
	writes []int64
	last   int64
}

func (sc *encScen) next() {
	for time.Now().Unix() <= sc.last {
		time.Sleep(20 * time.Millisecond)
	}
	sc.writes = append(sc.writes, time.Now().Unix())
}

func (sc *encScen) done() { sc.last = time.Now().Unix() }

func (sc *encScen) canon(row Row) Row {
	out := make(Row, len(row))
	for i, f := range row {
		v := f.V
		n := strings.ToLower(f.N)
		switch {
		case strings.Contains(n, "rowid"):
			if x, err := strconv.ParseInt(strings.Trim(v, `"`), 10, 64); err == nil && x > 0 {
				v = "new"
			}
		case timeField(n):
			if x, ok := unixValue(v); ok && x >= sc.t0 {
				j := -1
				for k, w := range sc.writes {
					if w <= x {
						j = k
					}
				}
				v = "now@" + strconv.Itoa(j)
			}
		}
		out[i] = Field{f.N, v}
	}
	return out
}

// encErrRow is an error as a row: its kind (compared) and its text
// ("~err_text", logged, never compared: the formats word errors apart).
func encErrRow(err error) Row { return Row{{"err", errKind(err)}, {"~err_text", err.Error()}} }

// recRow is a record row: RecordRow canonicalized, with sealed stored bytes
// read as "sealed" (their envelope is random per store) and, for a record
// this driver wrote, whether the bytes equal the written ones.
func (e *encRun) recRow(r *storage.Record) Row {
	row := e.sc.canon(RecordRow(r))
	if r == nil {
		return row
	}
	same := "n/a"
	if w := e.byCID[r.CID]; w != nil {
		same = strconv.FormatBool(bytes.Equal(r.Data, w.Bytes))
		if !bytes.Equal(r.Data, w.Bytes) && encfield.IsSealed(r.Data) {
			same = "sealed"
		}
	}
	for i := range row {
		if row[i].N == "data" && encfield.IsSealed(r.Data) {
			row[i].V = "sealed"
		}
	}
	return append(row, Field{"same_bytes", same})
}

// encRun is one scenario's reads on one arm (or its disk checks).
type encRun struct {
	logf    Logf
	keys    encKeys
	classes []encClass
	byCID   map[string]*encRec
	sc      *encScen
	out     string
	arm     string
	probs   *[]string
	only    []string // the types a scenario reads (default: the main scenario's four)
}

func (e *encRun) fail(f string, a ...any) {
	msg := fmt.Sprintf("%s: ", e.arm) + fmt.Sprintf(f, a...)
	*e.probs = append(*e.probs, msg)
	if e.logf != nil {
		e.logf("encfields: PROBLEM %s", msg)
	}
}

func (e *encRun) types() []string {
	if len(e.only) > 0 {
		return e.only
	}
	return []string{"KMF.fbs", "LGR.fbs", "OMM.fbs", "MPE.fbs"}
}

func (e *encRun) recsOf(typ string) []*encRec {
	var out []*encRec
	for _, c := range e.classes {
		if c.Type == typ {
			out = append(out, c.Recs...)
		}
	}
	return out
}

func (e *encRun) classesOf(typ string) []encClass {
	var out []encClass
	for _, c := range e.classes {
		if c.Type == typ {
			out = append(out, c)
		}
	}
	return out
}

// write applies the scenario's writes: per class, its tagged records in one
// StoreBatchWithSourceTags, then its untagged ones one Store each.
func (e *encRun) write(s *storage.FlatSQLStore) {
	for _, c := range e.classes {
		var tagged, untagged []*encRec
		for _, r := range c.Recs {
			if r.Tagged {
				tagged = append(tagged, r)
			} else {
				untagged = append(untagged, r)
			}
		}
		if len(tagged) > 0 {
			recs := make([][]byte, len(tagged))
			for i, r := range tagged {
				recs[i] = r.Bytes
			}
			e.sc.next()
			n, err := s.StoreBatchWithSourceTags(c.Type, recs, encPeer, encSig, storage.SourceTags{ProviderID: encProvider, SourceName: c.source(), BatchID: c.batch()})
			e.sc.done()
			if err != nil || n != len(recs) {
				e.fail("write %s tagged: stored %d of %d: %v", c.Name, n, len(recs), err)
			}
		}
		for _, r := range untagged {
			e.sc.next()
			id, err := s.Store(c.Type, r.Bytes, encPeer, encSig)
			e.sc.done()
			if err != nil || id != r.CID {
				e.fail("write %s untagged: cid %q (want %s): %v", c.Name, id, r.CID, err)
			}
		}
	}
}

func digestRows(bs [][]byte) []Row {
	rows := make([]Row, 0, len(bs))
	for _, b := range bs {
		k := "plain"
		if encfield.IsSealed(b) {
			k = "sealed"
		}
		rows = append(rows, ValueRow("len", strconv.Itoa(len(b)), "frame", digestOrSealed(b), "kind", k))
	}
	return sortRows(rows)
}

func digestOrSealed(b []byte) string {
	if encfield.IsSealed(b) {
		return "sealed"
	}
	return digest(b)
}

// answers reads everything the scenario wrote, through every surface that
// applies, as canonical rows.
func (e *encRun) answers(s *storage.FlatSQLStore, label string) []encCall {
	var calls []encCall
	add := func(name string, rows []Row) { calls = append(calls, encCall{Name: name, Rows: rows}) }
	recs := func(name string, list []*storage.Record, err error) {
		if err != nil {
			add(name, []Row{encErrRow(err)})
			return
		}
		rows := make([]Row, 0, len(list))
		for _, r := range list {
			rows = append(rows, e.recRow(r))
			if w := e.byCID[r.CID]; w != nil && !encfield.IsSealed(r.Data) && !bytes.Equal(r.Data, w.Bytes) {
				e.fail("%s %s: %s returns other bytes than written", label, name, r.CID)
			}
		}
		add(name, rows)
	}
	for _, typ := range e.types() {
		// GET by CID: bytes and the throwaway-key decrypt.
		var rows []Row
		for _, w := range e.recsOf(typ) {
			r, err := s.GetRecord(typ, w.CID)
			if err != nil {
				rows = append(rows, append(Row{{"cid", w.CID}}, encErrRow(err)...))
				e.fail("%s GET %s %s: %v", label, typ, w.CID, err)
				continue
			}
			dec := decryptCheck(e.keys, w, r.Data)
			if dec != "ok" {
				e.fail("%s GET %s %s: %s", label, typ, w.CID, dec)
			}
			rows = append(rows, e.sc.canon(append(getRow(r), Field{"same_bytes", strconv.FormatBool(bytes.Equal(r.Data, w.Bytes))}, Field{"decrypt", dec})))
		}
		add("GET "+typ, rows)
		// TAGS.
		rows = nil
		for _, w := range e.recsOf(typ) {
			tg, err := s.GetSourceTags(typ, w.CID)
			if err != nil {
				rows = append(rows, append(Row{{"cid", w.CID}}, encErrRow(err)...))
				continue
			}
			rows = append(rows, TagsRow(w.CID, tg))
		}
		add("TAGS "+typ, rows)
		// SCAN / data pages.
		l, err := s.QueryRawRecords(storage.RawRecordQuery{SchemaName: typ, UseRowIDCursor: true, Limit: 1000})
		recs("SCAN cursor "+typ, l, err)
		l, err = s.QueryRawRecords(storage.RawRecordQuery{SchemaName: typ, Limit: 1000})
		recs("SCAN newest "+typ, l, err)
		l, err = s.QueryRawRecordRefs(storage.RawRecordQuery{SchemaName: typ, UseRowIDCursor: true, Limit: 1000})
		recs("SCAN refs (stored bytes) "+typ, l, err)
		// The sealed stored bytes open with the store's throwaway key to the written record.
		if err == nil {
			for _, r := range l {
				if !encfield.IsSealed(r.Data) {
					continue
				}
				w := e.byCID[r.CID]
				opened, was, oerr := encfield.Open(strings.TrimSuffix(typ, ".fbs"), r.Data, e.keys.StorePriv, storeFieldEncryptionContext)
				switch {
				case oerr != nil || !was:
					e.fail("%s refs %s %s: the sealed bytes do not open with the store key: %v", label, typ, r.CID, oerr)
				case w == nil || !bytes.Equal(opened, w.Bytes):
					e.fail("%s refs %s %s: the sealed bytes open to other bytes than written", label, typ, r.CID)
				}
			}
		}
		for _, c := range e.classesOf(typ) {
			l, err = s.QuerySourceTaggedRecords(storage.SourceTagQuery{SchemaName: typ, ProviderID: encProvider, SourceName: c.source(), Limit: 1000})
			recs("LANE "+typ+" "+c.source(), l, err)
			n, err := s.CountRawRecords(storage.RawRecordQuery{SchemaName: typ, ProviderID: encProvider, SourceName: c.source()})
			if err != nil {
				add("COUNT lane "+typ+" "+c.source(), []Row{encErrRow(err)})
			} else {
				add("COUNT lane "+typ+" "+c.source(), []Row{ValueRow("lane_n", i64(n))})
			}
		}
		l, err = s.QueryRecentRecords(typ, 1000)
		recs("RECENT "+typ, l, err)
		p, err := s.FullTablePageWithCursor(storage.FullTablePageQuery{SchemaName: typ, Limit: 1000})
		recs("TABLE PAGE "+typ, p.Records, err)
		all, err := s.QueryAllBounded(typ, 1000, 64<<20)
		if err != nil {
			add("ALL BOUNDED "+typ, []Row{encErrRow(err)})
		} else {
			add("ALL BOUNDED "+typ, digestRows(all))
		}
		n, err := s.Count(typ)
		if err != nil {
			add("COUNT "+typ, []Row{encErrRow(err)})
		} else {
			add("COUNT "+typ, []Row{ValueRow("n", i64(n))})
		}
		q := storage.RawRecordQuery{SchemaName: typ}
		cnt, h, err := s.RawRecordSnapshot(q)
		if err != nil {
			add("HEAD "+typ, []Row{encErrRow(err)})
		} else {
			add("HEAD "+typ, []Row{e.sc.canon(covHead(q, cnt, &h))})
		}
		l, err = s.QueryIndexedRecords(storage.IndexedRecordQuery{SchemaName: typ, Limit: 1000, AllowLargeResultSet: true})
		recs("INDEXED "+typ, l, err)
		ip, total, err := s.RecordIndexPage(storage.RecordIndexPageQuery{SchemaName: typ, Limit: 1000})
		if err != nil {
			add("INDEX PAGE "+typ, []Row{encErrRow(err)})
		} else {
			rows = []Row{ValueRow("total", i64(total))}
			for _, r := range ip {
				rows = append(rows, ValueRow("cid", r.CID, "norad", i64p(r.NoradCatID), "epoch", i64p(r.EpochUnix)))
			}
			add("INDEX PAGE "+typ, rows)
		}
	}
	// Indexed reads that filter on an encrypted field (OMM's NORAD and
	// OBJECT_ID, MPE's ENTITY_ID): the plaintext finds nothing, the
	// ciphertext (what the record holds) finds its record.
	for _, c := range e.classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				var qs []storage.IndexedRecordQuery
				var names []string
				switch c.Type + "." + f.Name {
				case "OMM.fbs.NORAD_CAT_ID":
					pv, cv := binary.LittleEndian.Uint32(f.Plain), binary.LittleEndian.Uint32(f.Cipher)
					qs = append(qs, storage.IndexedRecordQuery{SchemaName: c.Type, NoradCatID: u32(pv), Limit: 100},
						storage.IndexedRecordQuery{SchemaName: c.Type, NoradCatID: u32(cv), Limit: 100})
					names = append(names, "plaintext", "ciphertext")
				case "OMM.fbs.OBJECT_ID", "MPE.fbs.ENTITY_ID":
					qs = append(qs, storage.IndexedRecordQuery{SchemaName: c.Type, EntityID: string(f.Plain), Limit: 100},
						storage.IndexedRecordQuery{SchemaName: c.Type, EntityID: string(f.Cipher), Limit: 100})
					names = append(names, "plaintext", "ciphertext")
				}
				for k, iq := range qs {
					l, err := s.QueryIndexedRecords(iq)
					recs(fmt.Sprintf("INDEXED %s %s=%s of %s", c.Type, f.Name, names[k], w.CID), l, err)
				}
			}
		}
	}
	calls = append(calls, e.epochAnswers(s)...)
	calls = append(calls, e.sqlAnswers(s)...)
	calls = append(calls, e.exportAnswers(s, label)...)
	calls = append(calls, e.ftsAnswers(s)...)
	for _, fn := range []string{"DataSummary", "SourceBatchProgress", "ProducerSourceProgress", "SourceRecordCounts", "SchemaDateRanges", "LiveRecordBytes"} {
		v, err := summaryFetch(s, fn, "")
		if err != nil {
			add("SUMMARY "+fn, []Row{encErrRow(err)})
			continue
		}
		rows, err := summaryRows(v)
		if err != nil {
			add("SUMMARY "+fn, []Row{encErrRow(err)})
			continue
		}
		for i := range rows {
			rows[i] = e.sc.canon(rows[i])
		}
		add("SUMMARY "+fn, sortRows(rows))
	}
	return calls
}

func (e *encRun) epochAnswers(s *storage.FlatSQLStore) []encCall {
	var calls []encCall
	add := func(name string, rows []Row) { calls = append(calls, encCall{Name: name, Rows: rows}) }
	at := time.Unix(encEpoch0+30*60+30, 0).UTC()
	from, to := time.Unix(encEpoch0-3600, 0).UTC(), time.Unix(encEpoch0+7200, 0).UTC()
	var qs []storage.EpochRecordQuery
	for _, typ := range []string{"OMM.fbs", "MPE.fbs"} {
		for _, prof := range []string{storage.EpochProfileNearest, storage.EpochProfileAsOf, storage.EpochProfileForward} {
			qs = append(qs, storage.EpochRecordQuery{SchemaName: typ, Profile: prof, At: at, Limit: 100},
				storage.EpochRecordQuery{SchemaName: typ, Profile: prof, At: at, Limit: 100, IncludeSource: true})
			for _, c := range e.classesOf(typ) {
				qs = append(qs, storage.EpochRecordQuery{SchemaName: typ, Profile: prof, At: at, ProviderID: encProvider, SourceName: c.source(), Limit: 100})
			}
		}
		qs = append(qs, storage.EpochRecordQuery{SchemaName: typ, Profile: storage.EpochProfileDay, Day: "2026-09-20", Limit: 100},
			storage.EpochRecordQuery{SchemaName: typ, Profile: storage.EpochProfileWindow, From: &from, To: &to, Limit: 100},
			storage.EpochRecordQuery{SchemaName: typ, Profile: storage.EpochProfileCoverage})
	}
	// Entity filters on encrypted fields: plaintext and ciphertext.
	for _, c := range e.classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				switch c.Type + "." + f.Name {
				case "OMM.fbs.NORAD_CAT_ID":
					qs = append(qs, storage.EpochRecordQuery{SchemaName: c.Type, Profile: storage.EpochProfileNearest, At: at, NoradCatID: u32(binary.LittleEndian.Uint32(f.Plain)), Limit: 10},
						storage.EpochRecordQuery{SchemaName: c.Type, Profile: storage.EpochProfileNearest, At: at, NoradCatID: u32(binary.LittleEndian.Uint32(f.Cipher)), Limit: 10})
				case "MPE.fbs.ENTITY_ID":
					qs = append(qs, storage.EpochRecordQuery{SchemaName: c.Type, Profile: storage.EpochProfileAsOf, At: at, EntityID: string(f.Plain), Limit: 10},
						storage.EpochRecordQuery{SchemaName: c.Type, Profile: storage.EpochProfileAsOf, At: at, EntityID: string(f.Cipher), Limit: 10})
				}
			}
		}
	}
	for _, p := range qs {
		name := fmt.Sprintf("EPOCH %s %s at=%d", p.SchemaName, p.Profile, p.At.Unix())
		if p.SourceName != "" {
			name += " source=" + p.SourceName
		}
		if p.IncludeSource {
			name += " include_source"
		}
		if p.NoradCatID != nil {
			name += fmt.Sprintf(" norad=%d", *p.NoradCatID)
		}
		if p.EntityID != "" {
			name += " entity=" + hex.EncodeToString([]byte(p.EntityID))
		}
		if p.Day != "" {
			name += " day=" + p.Day
		}
		if p.Profile == storage.EpochProfileCoverage {
			bs, err := s.QueryEpochCoverage(p)
			if err != nil {
				add(name, []Row{encErrRow(err)})
				continue
			}
			var rows []Row
			for _, b := range bs {
				rows = append(rows, ValueRow("day", b.Day, "n", i64(b.Count), "oldest", unixOf(b.OldestEpoch), "newest", unixOf(b.NewestEpoch)))
			}
			add(name, rows)
			continue
		}
		n, err := s.CountEpochRecords(p)
		if err != nil {
			add(name, []Row{encErrRow(err)})
			continue
		}
		ms, err := s.QueryEpochRecords(p)
		if err != nil {
			add(name, []Row{encErrRow(err)})
			continue
		}
		a, _ := matchesAnswer(name, ms, n)
		rows := make([]Row, 0, len(a.Rows))
		for _, r := range a.Rows {
			c := e.sc.canon(r)
			// The entity key may hold ciphertext: compare its bytes as hex.
			for i := range c {
				if c[i].N == "entity" && !utf8.ValidString(c[i].V) {
					c[i].V = "hex:" + hex.EncodeToString([]byte(c[i].V))
				}
			}
			rows = append(rows, c)
		}
		add(name, rows)
		for _, m := range ms {
			if m.Record == nil {
				continue
			}
			if w := e.byCID[m.Record.CID]; w != nil && !bytes.Equal(m.Record.Data, w.Bytes) {
				e.fail("%s: %s returns other bytes than written", name, m.Record.CID)
			}
		}
	}
	// The epoch streams (the SQL surface's EPOCH relation).
	for _, typ := range []string{"OMM.fbs", "MPE.fbs"} {
		sources := []string{"local"}
		for _, c := range e.classesOf(typ) {
			sources = append(sources, c.source())
		}
		for _, src := range sources {
			for _, prof := range []string{"nearest", "as_of", "forward"} {
				name := fmt.Sprintf("EPOCH STREAM %s@%s %s", typ, src, prof)
				st, err := s.QueryEpochRawStream(typ, src, prof, float64(at.Unix())+0.5, 0)
				if err != nil {
					add(name, []Row{encErrRow(err)})
					continue
				}
				fr, err := FrameRows(st.Bytes)
				if err != nil {
					add(name, []Row{encErrRow(err)})
					continue
				}
				add(name, unorderedDigest(fr))
			}
		}
	}
	return calls
}

func (e *encRun) sqlAnswers(s *storage.FlatSQLStore) []encCall {
	var calls []encCall
	add := func(name string, rows []Row) { calls = append(calls, encCall{Name: name, Rows: rows}) }
	jsonSQL := func(stmt string) {
		payload, _, _, err := s.QuerySandboxedJSON(stmt, sandboxCaps)
		if err != nil {
			add("SQL "+stmt, []Row{encErrRow(err)})
			return
		}
		valid := utf8.Valid(payload)
		rows, err := JSONRows(payload)
		if err != nil {
			add("SQL "+stmt, []Row{encErrRow(err), {{"utf8", strconv.FormatBool(valid)}}})
			return
		}
		add("SQL "+stmt, append([]Row{{{"utf8", strconv.FormatBool(valid)}}}, sortRows(rows)...))
	}
	streamSQL := func(stmt string) {
		st, err := s.QuerySandboxedStream(stmt, sandboxCaps)
		if err != nil {
			add("SQL STREAM "+stmt, []Row{encErrRow(err)})
			return
		}
		fr, err := FrameRows(st.Bytes)
		if err != nil {
			add("SQL STREAM "+stmt, []Row{encErrRow(err)})
			return
		}
		add("SQL STREAM "+stmt, unorderedDigest(fr))
		// Every frame the SQL surface streams is a record this driver wrote,
		// byte for byte (a sealed one opens with the store key to it).
		b := st.Bytes
		for len(b) >= 4 {
			n := int(binary.LittleEndian.Uint32(b))
			if len(b) < 4+n {
				break
			}
			fr := b[4 : 4+n]
			b = b[4+n:]
			if n == 0 {
				continue
			}
			if encfield.IsSealed(fr) {
				e.fail("SQL STREAM %s: streams a sealed frame", stmt)
				continue
			}
			if w := e.byCID[storage.ComputeCID(fr)]; w == nil || !bytes.Equal(w.Bytes, fr) {
				e.fail("SQL STREAM %s: streams bytes this driver did not write (cid %s)", stmt, storage.ComputeCID(fr))
			}
		}
	}
	selSQL := func(prefix, stmt string) {
		r, err := s.SandboxedSelect(context.Background(), stmt, storage.SandboxSelectCaps{MaxRows: 1000, MaxBytes: 16 << 20, Timeout: time.Minute})
		if err != nil {
			add(prefix+stmt, []Row{encErrRow(err)})
			return
		}
		rows := []Row{{{"columns", strings.Join(r.Columns, ",")}, {"truncated", strconv.FormatBool(r.Truncated)}}}
		var body []Row
		for _, cells := range r.Rows {
			row := Row{}
			for i, v := range cells {
				if !utf8.ValidString(v) {
					v = "hex:" + hex.EncodeToString([]byte(v))
				}
				row = append(row, Field{r.Columns[i], v})
			}
			body = append(body, row)
		}
		add(prefix+stmt, append(rows, sortRows(body)...))
	}
	for _, typ := range e.types() {
		code := strings.TrimSuffix(typ, ".fbs")
		jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "%s"`, code))
		jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "%s@local"`, code))
		for _, c := range e.classesOf(typ) {
			jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "%s@%s"`, code, c.source()))
		}
		jsonSQL(fmt.Sprintf(`SELECT * FROM "%s"`, code))
		streamSQL(fmt.Sprintf(`SELECT _data FROM "%s"`, code))
		// SandboxedSelect's SELECT * (C-47: format 1's fast path renders
		// _source, _data, bool and uint32 its own way) on the type, in lower
		// case, and on each feed's relation and local (encFastPathShadow).
		selSQL("SELECT ", fmt.Sprintf(`SELECT * FROM "%s"`, code))
		selSQL("SELECT ", fmt.Sprintf(`select  *  from %s ;`, strings.ToLower(code)))
		selSQL("SELECT ", fmt.Sprintf(`SELECT * FROM "%s@local"`, code))
		for _, c := range e.classesOf(typ) {
			selSQL("SELECT ", fmt.Sprintf(`SELECT * FROM "%s@%s"`, code, c.source()))
		}
	}
	selSQL("SELECT ", `SELECT hex(OBJECT_ID) AS id, hex(OBJECT_NAME) AS name, MEAN_MOTION, hex(EPOCH) AS epoch FROM "OMM"`)
	selSQL("SELECT ", `SELECT NORAD_CAT_ID FROM "OMM"`)
	selSQL("SELECT ", `SELECT hex(ENTITY_ID) AS id, EPOCH FROM "MPE"`)
	selSQL("SELECT ", `SELECT REQUEST_ID, length(_data) AS n FROM "LGR"`)
	selSQL("SELECT ", `SELECT COUNT(*) AS n FROM "KMF"`)
	jsonSQL(`SELECT hex(OBJECT_ID) AS id, hex(OBJECT_NAME) AS name, NORAD_CAT_ID, MEAN_MOTION, hex(EPOCH) AS epoch FROM "OMM"`)
	jsonSQL(`SELECT OBJECT_ID, OBJECT_NAME, EPOCH FROM "OMM"`)
	jsonSQL(`SELECT hex(ENTITY_ID) AS id, EPOCH FROM "MPE"`)
	for _, c := range e.classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				if c.Type+"."+f.Name == "OMM.fbs.NORAD_CAT_ID" {
					jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "OMM" WHERE NORAD_CAT_ID = %d`, binary.LittleEndian.Uint32(f.Plain)))
					jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "OMM" WHERE NORAD_CAT_ID = %d`, binary.LittleEndian.Uint32(f.Cipher)))
					jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "OMM" WHERE NORAD_CAT_ID = %d`, int32(binary.LittleEndian.Uint32(f.Cipher))))
				}
				if c.Type+"."+f.Name == "OMM.fbs.OBJECT_ID" {
					jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "OMM" WHERE OBJECT_ID = '%s'`, string(f.Plain)))
					jsonSQL(fmt.Sprintf(`SELECT COUNT(*) AS n FROM "OMM" WHERE hex(OBJECT_ID) = '%X'`, f.Cipher))
				}
			}
		}
	}
	return calls
}

// exportAnswers: ExportDatasetWindow of each feed and of each type.
func (e *encRun) exportAnswers(s *storage.FlatSQLStore, label string) []encCall {
	var calls []encCall
	add := func(name string, rows []Row) { calls = append(calls, encCall{Name: name, Rows: rows}) }
	var qs []storage.IndexedRecordQuery
	for _, c := range e.classes {
		qs = append(qs, storage.IndexedRecordQuery{SchemaName: c.Type, ProviderID: encProvider, SourceName: c.source(), BatchID: c.batch(), Limit: 1000})
	}
	for _, typ := range e.types() {
		qs = append(qs, storage.IndexedRecordQuery{SchemaName: typ, Limit: 1000})
	}
	for i, q := range qs {
		name := fmt.Sprintf("EXPORT %s source=%s", q.SchemaName, q.SourceName)
		dir := filepath.Join(e.out, "exports", label, strconv.Itoa(i))
		_ = os.RemoveAll(dir)
		ex, err := s.ExportDatasetWindow(dir, q)
		if err != nil {
			add(name, []Row{encErrRow(err)})
			continue
		}
		rows := []Row{ValueRow("records", strconv.Itoa(ex.RecordCount), "query", ex.QuerySHA256, "result", ex.ResultSHA256, "shard", ex.ShardSHA256,
			"shard_cid", ex.ShardCID, "index", ex.IndexSHA256, "shard_bytes", i64(ex.ShardBytes))}
		raw, err := os.ReadFile(ex.IndexPath)
		if err != nil {
			add(name, append(rows, encErrRow(err)))
			continue
		}
		rows = append(rows, ValueRow("index_utf8", strconv.FormatBool(utf8.Valid(raw)), "index_json_valid", strconv.FormatBool(json.Valid(raw))))
		var idx storage.DatasetExportIndex
		if err := json.Unmarshal(raw, &idx); err != nil {
			add(name, append(rows, encErrRow(err)))
			continue
		}
		shard, err := os.ReadFile(ex.ShardPath)
		if err != nil {
			add(name, append(rows, encErrRow(err)))
			continue
		}
		for _, r := range idx.Records {
			// The shard is [u32 LE size][record] frames; Offset names the
			// size, Length the record (ExportDatasetRecords).
			var frame []byte
			if r.Offset >= 0 && r.Length >= 0 && r.Offset+4+r.Length <= int64(len(shard)) {
				frame = shard[r.Offset+4 : r.Offset+4+r.Length]
			}
			same := "n/a"
			if w := e.byCID[r.CID]; w != nil {
				same = strconv.FormatBool(bytes.Equal(frame, w.Bytes))
				if same != "true" {
					e.fail("%s %s: the shard holds other bytes than written for %s", label, name, r.CID)
				}
			}
			norad := ""
			if r.NoradCatID != nil {
				norad = strconv.FormatUint(uint64(*r.NoradCatID), 10)
			}
			rows = append(rows, ValueRow("cid", r.CID, "offset", i64(r.Offset), "length", i64(r.Length), "norad", norad,
				"entity_hex", hex.EncodeToString([]byte(r.EntityID)), "epoch", i64p(r.EpochUnix), "same_bytes", same,
				"provider", r.SourceTags.ProviderID, "source", r.SourceTags.SourceName, "batch", r.SourceTags.BatchID))
		}
		add(name, rows)
	}
	return calls
}

// ftsAnswers: full-text search on records with encrypted string fields.
// The plaintext of an encrypted field must find nothing; an unencrypted
// token finds its records.
func (e *encRun) ftsAnswers(s *storage.FlatSQLStore) []encCall {
	var calls []encCall
	add := func(name string, rows []Row) { calls = append(calls, encCall{Name: name, Rows: rows}) }
	_, _, werr := s.WarmFullTextIndexes()
	// Every type searched below, records or none: format 1 builds an index
	// on first demand and answers "building" until it is ready, an empty
	// type's too (C-46 (2): then no rows, as format 4 answers at once, its
	// state "cold"); a type with records waits for "ready" on both formats.
	searched := map[string]bool{"OMM.fbs": true, "LGR.fbs": true, "KMF.fbs": true}
	for _, typ := range e.types() {
		searched[typ] = true
	}
	for typ := range searched {
		// A type without full text (KMF: "unavailable" on both formats)
		// has no index to wait for.
		if err := s.CheckFullTextSearch(typ, "warm"); err != nil && !strings.Contains(strings.ToLower(err.Error()), "building") {
			delete(searched, typ)
		}
	}
	deadline := time.Now().Add(10 * time.Minute)
	for typ := range searched {
		empty := len(e.recsOf(typ)) == 0
		for time.Now().Before(deadline) {
			st := s.FullTextIndexState(typ)
			if st == "ready" || st == "failed" || st == "disabled" || st == "unsupported" || (empty && st == "cold") {
				break
			}
			time.Sleep(time.Second)
		}
	}
	rows := []Row{}
	if werr != nil {
		rows = append(rows, encErrRow(werr))
	}
	for _, typ := range e.types() {
		rows = append(rows, ValueRow("type", typ, "state", s.FullTextIndexState(typ)))
	}
	add("FTS states", rows)
	search := func(typ, q string) {
		name := fmt.Sprintf("FTS %s %q", typ, q)
		if err := s.CheckFullTextSearch(typ, q); err != nil {
			add(name+" check", []Row{encErrRow(err)})
		}
		l, err := s.QueryRawRecords(storage.RawRecordQuery{SchemaName: typ, Search: q, UseRowIDCursor: true, Limit: 100})
		if err != nil {
			add(name, []Row{encErrRow(err)})
			return
		}
		rows := make([]Row, 0, len(l))
		for _, r := range l {
			rows = append(rows, e.recRow(r))
		}
		add(name, rows)
	}
	// Full text follows the records in the background on both formats
	// ("ready" is the state of the last pass): wait until the positive
	// controls answer every record that carries the token (or a minute), and
	// report how long that took.
	settle := func(typ, q string, want int) {
		st := time.Now()
		got := 0
		for time.Since(st) < time.Minute {
			l, err := s.QueryRawRecords(storage.RawRecordQuery{SchemaName: typ, Search: q, UseRowIDCursor: true, Limit: 100})
			if err == nil {
				got = len(l)
			}
			if got >= want {
				break
			}
			_ = s.CheckFullTextSearch(typ, q)
			time.Sleep(500 * time.Millisecond)
		}
		add(fmt.Sprintf("FTS settle %s %q", typ, q), []Row{{{"want", strconv.Itoa(want)}, {"got", strconv.Itoa(got)}, {"~seconds", fmt.Sprintf("%.1f", time.Since(st).Seconds())}}})
	}
	nOMM := 0
	for _, c := range e.classesOf("OMM.fbs") {
		if c.Name == "omm-scalar" || c.Name == "omm-epoch" {
			nOMM += len(c.Recs)
		}
	}
	settle("OMM.fbs", "ENCPROOF", nOMM)
	settle("LGR.fbs", "encproofmodule", len(e.recsOf("LGR.fbs")))
	search("OMM.fbs", "ENCPROOF")
	search("LGR.fbs", "encproofmodule")
	search("KMF.fbs", "enc")
	for _, c := range e.classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				if f.Kind == "string" || (f.Kind == "ecies" && c.Type == "LGR.fbs") || (f.Kind == "vector") {
					tok := string(f.Plain)
					if f.Name == "EPOCH" {
						tok = "2026"
					}
					if i := bytes.IndexByte(f.Plain, 'x'); f.Kind != "string" && i > 0 {
						tok = string(f.Plain[:i+1+12])
					}
					search(c.Type, tok)
				}
			}
		}
	}
	return calls
}

// ---- disk checks (no FlatSQL code: plain file reads) ------------------------

// walkStreams walks every P/<TYPE>/*.fsdata of a format-4 store as
// [u32 LE size][bytes] frames and classifies each frame.
func (e *encRun) walkStreams(store string) ([]Row, []string) {
	var rows []Row
	var probs []string
	root := filepath.Join(store, "fsql4", "P")
	types, _ := os.ReadDir(root)
	for _, td := range types {
		files, _ := os.ReadDir(filepath.Join(root, td.Name()))
		for _, f := range files {
			if !strings.HasSuffix(f.Name(), ".fsdata") {
				continue
			}
			path := filepath.Join(root, td.Name(), f.Name())
			data, err := os.ReadFile(path)
			if err != nil {
				probs = append(probs, err.Error())
				continue
			}
			var frames, flat, sealedN, opened, written, cipherOK int
			at := 0
			for at < len(data) {
				if len(data)-at < 4 {
					probs = append(probs, fmt.Sprintf("%s: torn size prefix at %d", path, at))
					break
				}
				n := int(binary.LittleEndian.Uint32(data[at:]))
				if len(data)-at-4 < n {
					probs = append(probs, fmt.Sprintf("%s: frame at %d runs past EOF", path, at))
					break
				}
				fr := data[at+4 : at+4+n]
				frames++
				switch {
				case encfield.IsSealed(fr) || encfield.IsSealedForRecipients(fr):
					sealedN++
					plain, was, err := encfield.Open(td.Name(), fr, e.keys.StorePriv, storeFieldEncryptionContext)
					if err != nil || !was {
						probs = append(probs, fmt.Sprintf("%s: sealed frame at %d does not open with the store key: %v", path, at, err))
						break
					}
					opened++
					if w := e.byCID[storage.ComputeCID(plain)]; w != nil && bytes.Equal(plain, w.Bytes) {
						written++
						// The envelope's record keeps the client's ciphertext
						// under the store's layer: neither the client
						// ciphertext nor the plaintext is in the frame.
						for _, ef := range w.Fields {
							if bytes.Contains(fr, ef.Cipher) || bytes.Contains(fr, ef.Plain) {
								probs = append(probs, fmt.Sprintf("%s: sealed frame at %d holds %s in the clear", path, at, ef.Name))
							}
						}
						cipherOK++
					} else {
						probs = append(probs, fmt.Sprintf("%s: sealed frame at %d opens to a record this driver did not write", path, at))
					}
				default:
					flat++
					w := e.byCID[storage.ComputeCID(fr)]
					if w == nil {
						probs = append(probs, fmt.Sprintf("%s: frame at %d is not a record this driver wrote (cid %s)", path, at, storage.ComputeCID(fr)))
						break
					}
					written++
					if len(fr) < 8 || string(fr[4:8]) != "$"+strings.TrimSuffix(w.Type, ".fbs") {
						probs = append(probs, fmt.Sprintf("%s: frame at %d has file identifier %q", path, at, fr[4:8]))
					}
					good := true
					for _, ef := range w.Fields {
						if !bytes.Contains(fr, ef.Cipher) || (len(ef.Plain) >= 4 && bytes.Contains(fr, ef.Plain)) {
							good = false
							probs = append(probs, fmt.Sprintf("%s: frame at %d: %s is not its ciphertext", path, at, ef.Name))
						}
					}
					if good {
						cipherOK++
					}
				}
				at += 4 + n
			}
			rows = append(rows, ValueRow("file", strings.TrimPrefix(path, store+"/"), "bytes", strconv.Itoa(len(data)), "frames", strconv.Itoa(frames),
				"flatbuffer_frames", strconv.Itoa(flat), "sealed_frames", strconv.Itoa(sealedN), "sealed_opened_with_store_key", strconv.Itoa(opened),
				"frames_of_written_records", strconv.Itoa(written), "encrypted_fields_ciphertext", strconv.Itoa(cipherOK), "ends_at_eof", strconv.FormatBool(at == len(data))))
		}
	}
	return rows, probs
}

// needle is one recognizable encoding of a plaintext (or, for a field SDN
// seals at rest, of the client ciphertext SDN received).
type needle struct {
	What string
	B    []byte
}

func encodings(what string, b []byte) []needle {
	out := []needle{{what + " raw", b}, {what + " hex", []byte(hex.EncodeToString(b))}, {what + " HEX", []byte(strings.ToUpper(hex.EncodeToString(b)))},
		{what + " base64", []byte(strings.TrimRight(base64.StdEncoding.EncodeToString(b), "="))},
		{what + " base64url", []byte(strings.TrimRight(base64.URLEncoding.EncodeToString(b), "="))}}
	return out
}

// needles are every plaintext's encodings, the scalar ones as their decimal
// text too, and the client ciphertext of every field SDN seals at rest (KMF).
func (e *encRun) needles() []needle {
	var out []needle
	for _, c := range e.classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				id := fmt.Sprintf("%s %s plaintext", w.CID[:16], f.Name)
				out = append(out, encodings(id, f.Plain)...)
				switch f.Kind {
				case "u32":
					v := binary.LittleEndian.Uint32(f.Plain)
					out = append(out, needle{id + " BE", binary.BigEndian.AppendUint32(nil, v)}, needle{id + " decimal", []byte(strconv.FormatUint(uint64(v), 10))})
				case "f64":
					v := math.Float64frombits(binary.LittleEndian.Uint64(f.Plain))
					out = append(out, needle{id + " BE", binary.BigEndian.AppendUint64(nil, math.Float64bits(v))},
						needle{id + " %.17g", []byte(strconv.FormatFloat(v, 'g', 17, 64))}, needle{id + " %g", []byte(strconv.FormatFloat(v, 'g', -1, 64))})
				}
				if w.Type == "KMF.fbs" {
					out = append(out, encodings(fmt.Sprintf("%s %s client-ciphertext (sealed at rest)", w.CID[:16], f.Name), f.Cipher)...)
				}
			}
		}
	}
	return out
}

// grepStore searches every file under dir for every needle.
func grepStore(dir string, needles []needle) (files int, scanned int64, hits []string) {
	_ = filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		b, err := os.ReadFile(p)
		if err != nil {
			hits = append(hits, "read "+p+": "+err.Error())
			return nil
		}
		files++
		scanned += int64(len(b))
		for _, n := range needles {
			if len(n.B) >= 4 && bytes.Contains(b, n.B) {
				hits = append(hits, fmt.Sprintf("%s in %s", n.What, strings.TrimPrefix(p, dir+"/")))
			}
		}
		return nil
	})
	return files, scanned, hits
}

// fileKinds counts a store's files by kind (suffix).
func fileKinds(dir string) map[string]int {
	out := map[string]int{}
	_ = filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		n := filepath.Base(p)
		k := filepath.Ext(n)
		for _, suf := range []string{"-wal", "-shm", ".fsdata", ".db", ".fts", ".idx", ".spec"} {
			if strings.HasSuffix(n, suf) {
				k = suf
			}
		}
		out[k]++
		return nil
	})
	return out
}

// ---- comparison ------------------------------------------------------------

// encRulings are the contract's accepted differences the comparison applies,
// each by name:
//   - C-9: a relation's meta columns _rowid and _offset are each format's own
//     (format 4: _rowid = seq, _offset = 0): dropped from SELECT * rows;
//   - C-41 N3: format 1's cursor pages list tagged records before untagged
//     ones, format 4 pages by seq: cursor pages (SCAN cursor and refs, a
//     search by cursor) compare as sets;
//   - C-39 E7: a lane page is ordered by the record timestamp alone, so one
//     batch's records tie: lane pages compare as sets;
//   - R18 (r18Accepted): format 1's epoch stream ranks by
//     USER_DEFINED_EPOCH_TIMESTAMP, format 4 by the EPOCH rule, so a record
//     whose EPOCH the client encrypted (no epoch on format 4) is in format
//     1's stream only: exactly those records' frames may be format 1's alone;
//   - C-48 (a) (encFastPathShadow): format 1's SandboxedSelect fast path
//     answers `SELECT * FROM "<TYPE>@<source>"` from the type's whole record
//     list (its shared store's), every row named <TYPE>@<source>; format 4
//     answers the source's records: every format-4 row must be one of
//     format 1's, and the run reports the rows format 1 adds;
//   - C-48 (b) (encF1NUL): format 1 reads text out of its engine as a C
//     string (flatsql_result_cell_string), so a string holding a NUL byte
//     (a client's ciphertext may) ends at that byte in its SandboxedSelect
//     cells and its point-profile EPOCH entity keys; format 4 keeps the
//     whole string. Values on those surfaces are compared cut at their first
//     NUL on both arms, and the run reports the calls that needed it.
var encSetCalls = []string{"SCAN cursor ", "SCAN refs ", "LANE ", "FTS "}

// encF1NUL cuts at the first NUL the values format 1 may read as C strings
// (C-48 (b)): every text cell of a SandboxedSelect ("SELECT " calls) and an
// EPOCH read's entity key. Values arrive as text or "hex:" + hex (not
// UTF-8). It returns the rows and how many values it cut.
func encF1NUL(name string, b []Row) ([]Row, int) {
	sel, epoch := strings.HasPrefix(name, "SELECT "), strings.HasPrefix(name, "EPOCH ")
	if !sel && !epoch {
		return b, 0
	}
	n := 0
	out := make([]Row, len(b))
	for i, r := range b {
		out[i] = append(Row(nil), r...)
		for j, f := range out[i] {
			if (epoch && f.N != "entity") || (sel && (f.N == "columns" || f.N == "truncated")) {
				continue
			}
			raw := []byte(f.V)
			if h, ok := strings.CutPrefix(f.V, "hex:"); ok {
				if d, err := hex.DecodeString(h); err == nil {
					raw = d
				}
			}
			cut, _, found := bytes.Cut(raw, []byte{0})
			if !found {
				continue
			}
			n++
			if v := string(cut); utf8.ValidString(v) {
				out[i][j].V = v
			} else {
				out[i][j].V = "hex:" + hex.EncodeToString(cut)
			}
		}
	}
	if sel && n > 0 && len(out) > 1 {
		out = append(out[:1:1], sortRows(out[1:])...) // selSQL sorts the body rows
	}
	return out, n
}

// encFastPathShadow is C-48 (a) above: ok when name is a
// SandboxedSelect `SELECT * FROM "<TYPE>@<source>"`, the headers (columns,
// truncated) are equal and every row of b (format 4) is one of a's (format
// 1's); extra is how many rows format 1 adds.
func encFastPathShadow(name string, a, b []Row) (extra int, ok bool) {
	if !strings.HasPrefix(name, "SELECT ") || !encSelectStar(name) || !strings.Contains(name, "@") || len(a) == 0 || len(b) == 0 ||
		strictText(a[0]) != strictText(b[0]) {
		return 0, false
	}
	held := map[string]int{}
	for _, r := range a[1:] {
		held[strictText(r)]++
	}
	for _, r := range b[1:] {
		if held[strictText(r)] == 0 {
			return 0, false
		}
		held[strictText(r)]--
	}
	return len(a) - len(b), true
}

// encSelectStar reports a call whose statement is a SELECT * (C-9's rows).
func encSelectStar(name string) bool {
	return strings.Contains(strings.ToLower(strings.Join(strings.Fields(name), " ")), "select * from")
}

func encNormalize(name string, rows []Row) []Row {
	out := make([]Row, 0, len(rows))
	for _, r := range rows {
		n := Row{}
		for _, f := range r {
			if f.N == "~err_text" || f.N == "~seconds" {
				continue
			}
			if encSelectStar(name) && (f.N == "_offset" || f.N == "_rowid") {
				continue
			}
			n = append(n, f)
		}
		out = append(out, n)
	}
	for _, p := range encSetCalls {
		if strings.HasPrefix(name, p) {
			return sortRows(out)
		}
	}
	return out
}

// encR18 is the R18 ruling on an OMM epoch stream: format 1's rows that
// format 4 lacks and that are frames of records whose EPOCH the client
// encrypted are dropped (returned as the accepted rows).
func encR18(name string, a, b []Row, encEpoch map[string]bool) ([]Row, int) {
	if !strings.HasPrefix(name, "EPOCH STREAM OMM.fbs@") {
		return a, 0
	}
	inB := map[string]bool{}
	for _, r := range b {
		inB[r.Get("h")] = true
	}
	var out []Row
	n := 0
	for _, r := range a {
		if h := r.Get("h"); encEpoch[h] && !inB[h] {
			n++
			continue
		}
		out = append(out, r)
	}
	return out, n
}

// encCompared is compareCalls' answer: the differences outside encRulings,
// the rows R18 accepted, and the rows format 1's fast path adds to a feed
// relation's SELECT * (C-48 (a)) and the values format 1 cut at a NUL
// (C-48 (b)), per call.
type encCompared struct {
	Diffs  []string       `json:"diffs"`
	R18    int            `json:"r18_rows"`
	Shadow map[string]int `json:"fastpath_shadow_rows,omitempty"`
	NUL    map[string]int `json:"f1_nul_values,omitempty"`
}

// compareCalls compares b's answers with a's (format 1's) under encRulings.
func compareCalls(what string, a, b []encCall, encEpoch map[string]bool) encCompared {
	out := encCompared{Shadow: map[string]int{}, NUL: map[string]int{}}
	bm := map[string][]Row{}
	for _, c := range b {
		bm[c.Name] = c.Rows
	}
	for _, c := range a {
		rb, ok := bm[c.Name]
		if !ok {
			out.Diffs = append(out.Diffs, fmt.Sprintf("%s: %s missing on the second arm", what, c.Name))
			continue
		}
		na, nb := encNormalize(c.Name, c.Rows), encNormalize(c.Name, rb)
		if encRowsText(na) != encRowsText(nb) {
			ca, _ := encF1NUL(c.Name, na)
			if cb, cut := encF1NUL(c.Name, nb); cut > 0 {
				out.NUL[c.Name] = cut
				na, nb = ca, cb
			}
		}
		na, n := encR18(c.Name, na, nb, encEpoch)
		out.R18 += n
		if extra, ok := encFastPathShadow(c.Name, na, nb); ok && extra > 0 {
			out.Shadow[c.Name] = extra
			continue
		}
		out.Diffs = append(out.Diffs, diffRows(what+": "+c.Name, na, nb)...)
	}
	return out
}

// encRowsText is rows as one comparable string.
func encRowsText(rows []Row) string {
	var b strings.Builder
	for _, r := range rows {
		b.WriteString(strictText(r))
		b.WriteByte('\n')
	}
	return b.String()
}

// encEpochDigests are the epoch-stream row digests of the records whose
// EPOCH the client encrypted (R18's rows).
func encEpochDigests(classes []encClass) map[string]bool {
	out := map[string]bool{}
	for _, c := range classes {
		for _, w := range c.Recs {
			for _, f := range w.Fields {
				if w.Type == "OMM.fbs" && f.Name == "EPOCH" {
					out[digestRow(frameRow(w.Bytes)).Get("h")] = true
				}
			}
		}
	}
	return out
}

func encWriteJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", " ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// ---- the stock-reader check -------------------------------------------------

// EnvSDSPy names the SDS Python readers (spacedatastandards.org lib/py) the
// stock-reader check imports.
const EnvSDSPy = "P4PROOF_SDS_PY"

// encReaderTool is enc-reader-check.py beside this file (P4PROOF_ENC_READER
// overrides it).
func encReaderTool() string {
	if p := os.Getenv("P4PROOF_ENC_READER"); p != "" {
		return p
	}
	_, here, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(here), "enc-reader-check.py")
}

// encReaderCheck runs the stock-reader check on format-4 stores: stock
// flatbuffers, the SDS Python readers and the generated decryption, no
// FlatSQL or SDN code (enc-reader-check.py). It returns the tool's summary.
func encReaderCheck(ctx context.Context, outDir string, stores ...string) (map[string]any, error) {
	py := os.Getenv(EnvSDSPy)
	if py == "" {
		return nil, fmt.Errorf("the stock-reader check needs %s (spacedatanetwork-stack repos/main-packages/spacedatastandards.org/lib/py)", EnvSDSPy)
	}
	report := filepath.Join(outDir, "reader-check.json")
	args := append([]string{encReaderTool(), "--sds-py", py, "--manifest", filepath.Join(outDir, "manifest.json"),
		"--keys", filepath.Join(outDir, "keys.json"), "--json", report}, stores...)
	out, err := exec.CommandContext(ctx, "python3", args...).CombinedOutput()
	_ = os.WriteFile(filepath.Join(outDir, "reader-check.log"), out, 0o644)
	var rep struct {
		Summary map[string]any `json:"summary"`
	}
	if b, rerr := os.ReadFile(report); rerr == nil {
		_ = json.Unmarshal(b, &rep)
	}
	if err != nil {
		return rep.Summary, fmt.Errorf("enc-reader-check.py: %v (%s)", err, filepath.Join(outDir, "reader-check.log"))
	}
	if pass, _ := rep.Summary["all_pass"].(bool); !pass {
		return rep.Summary, errors.New("enc-reader-check.py: not all_pass")
	}
	return rep.Summary, nil
}

// ---- the scenarios ----------------------------------------------------------

// encScenario is one set of writes run on fresh format-1 and format-4
// stores and compared.
type encScenario struct {
	name    string
	classes []encClass
	only    []string                                           // the types read (default: the main scenario's four)
	extra   func(e *encRun, s *storage.FlatSQLStore) []encCall // reads beyond answers
	migrate bool                                               // store-migrate --to 4 of the format-1 store
	reader  bool                                               // the stock-reader check
}

// runEncScenario runs sc under root and reports into rep; it returns the
// problems (every difference outside encRulings is one).
func runEncScenario(ctx context.Context, c Config, root string, keys encKeys, sc encScenario, logf Logf, rep map[string]any) []string {
	var probs []string
	outDir := filepath.Join(c.Out, "encfields", sc.name)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return []string{err.Error()}
	}
	byCID := map[string]*encRec{}
	var manifest []*encRec
	for _, cl := range sc.classes {
		for _, r := range cl.Recs {
			if byCID[r.CID] != nil {
				return []string{"duplicate CID " + r.CID}
			}
			byCID[r.CID] = r
			manifest = append(manifest, r)
		}
	}
	for name, v := range map[string]any{"keys.json": keys, "manifest.json": manifest} {
		if err := encWriteJSON(filepath.Join(outDir, name), v); err != nil {
			return []string{err.Error()}
		}
	}
	encEpoch := encEpochDigests(sc.classes)
	stores := map[string]string{ArmF1: filepath.Join(root, sc.name, "f1"), ArmS: filepath.Join(root, sc.name, "s")}
	answers := map[string][]encCall{}
	var sc0 *encScen
	for _, arm := range []string{ArmF1, ArmS} {
		dir := stores[arm]
		if err := provisionStoreKey(dir, keys); err != nil {
			return append(probs, err.Error())
		}
		scen := &encScen{t0: time.Now().Unix() - 1}
		if sc0 == nil {
			sc0 = scen
		}
		e := &encRun{logf: logf, keys: keys, classes: sc.classes, byCID: byCID, sc: scen, out: outDir, arm: arm, probs: &probs, only: sc.only}
		s, _, err := OpenArm(arm, dir)
		if err != nil {
			return append(probs, fmt.Sprintf("open %s: %v", arm, err))
		}
		e.write(s)
		if arm == ArmF1 {
			if _, err := s.HydrateEngineHotWindow(); err != nil {
				e.fail("format 1 hot window: %v", err)
			}
		}
		a := e.answers(s, arm)
		if sc.extra != nil {
			a = append(a, sc.extra(e, s)...)
		}
		// The plaintext search while the store is open (WAL files live).
		files, scanned, hits := grepStore(dir, e.needles())
		rep["grep_open_"+arm] = map[string]any{"files": files, "bytes": scanned, "hits": hits, "kinds": fileKinds(dir)}
		for _, h := range hits {
			e.fail("plaintext in the open store: %s", h)
		}
		if err := s.Close(); err != nil {
			e.fail("close: %v", err)
		}
		if b, err := os.ReadFile(filepath.Join(dir, "field-encryption-identity.json")); err != nil || !bytes.Contains(b, []byte(hex.EncodeToString(keys.StorePub))) {
			e.fail("the store's field-encryption identity is not the provisioned throwaway key: %v", err)
		}
		answers[arm] = a
		_ = encWriteJSON(filepath.Join(outDir, "answers-"+arm+".json"), a)
	}
	cmp := compareCalls("format 1 vs format 4", answers[ArmF1], answers[ArmS], encEpoch)
	rep["calls"], rep["f1_s"] = len(answers[ArmF1]), cmp
	probs = append(probs, cmp.Diffs...)

	// Disk: format 4's streams, the plaintext search over every file.
	disk := &encRun{logf: logf, keys: keys, classes: sc.classes, byCID: byCID, sc: sc0, out: outDir, arm: "disk", probs: &probs, only: sc.only}
	streams, sp := disk.walkStreams(stores[ArmS])
	rep["streams_s"] = streams
	for _, p := range sp {
		disk.fail("streams: %s", p)
	}
	ns := disk.needles()
	rep["needles"] = len(ns)
	for _, arm := range []string{ArmF1, ArmS} {
		files, scanned, hits := grepStore(stores[arm], ns)
		rep["grep_"+arm] = map[string]any{"files": files, "bytes": scanned, "hits": hits, "kinds": fileKinds(stores[arm])}
		for _, h := range hits {
			disk.fail("plaintext in the closed %s store: %s", arm, h)
		}
	}
	for _, v := range VerifyFormat4Store(stores[ArmS]) {
		disk.fail("verify: %s", v)
	}
	readerStores := []string{stores[ArmS]}

	// store-migrate --to 4 of the format-1 store: format 1's answers.
	if sc.migrate {
		mig := filepath.Join(root, sc.name, "migrated")
		switch {
		case c.SDNBin == "":
			disk.fail("store-migrate: %s not set", EnvSDNBin)
		case CloneStore(stores[ArmF1], mig) != nil:
			disk.fail("store-migrate: clone the format-1 store")
		default:
			cr, _, err := migrateRun(ctx, c.SDNBin, mig, c.logPath("encfields-migrate"), 0)
			rep["migrate_seconds"] = cr.Wall.Seconds()
			if err != nil {
				disk.fail("store-migrate: %v", err)
				break
			}
			for _, p := range checkMigrated(mig) {
				disk.fail("migrated: %s", p)
			}
			em := &encRun{logf: logf, keys: keys, classes: sc.classes, byCID: byCID, sc: sc0, out: outDir, arm: "migrated", probs: &probs, only: sc.only}
			s, _, err := OpenArm(ArmS, mig)
			if err != nil {
				disk.fail("open the migrated store: %v", err)
				break
			}
			am := em.answers(s, "migrated")
			if sc.extra != nil {
				am = append(am, sc.extra(em, s)...)
			}
			if err := s.Close(); err != nil {
				em.fail("close: %v", err)
			}
			_ = encWriteJSON(filepath.Join(outDir, "answers-migrated.json"), am)
			cm := compareCalls("format 1 vs migrated", answers[ArmF1], am, encEpoch)
			rep["f1_migrated"] = cm
			probs = append(probs, cm.Diffs...)
			ms, mp := em.walkStreams(mig)
			rep["streams_migrated"] = ms
			for _, p := range mp {
				em.fail("streams: %s", p)
			}
			files, scanned, hits := grepStore(mig, ns)
			rep["grep_migrated"] = map[string]any{"files": files, "bytes": scanned, "hits": hits, "kinds": fileKinds(mig)}
			for _, h := range hits {
				em.fail("plaintext in the migrated store: %s", h)
			}
			readerStores = append(readerStores, mig)
		}
	}
	if sc.reader {
		sum, err := encReaderCheck(ctx, outDir, readerStores...)
		rep["reader_check"] = sum
		if err != nil {
			disk.fail("%v", err)
		}
	}
	logf("encfields %s: %d calls, %d differences outside the rulings, %d R18 rows, C-48 (a): %d feed-relation SELECT * calls where format 1's fast path adds rows, C-48 (b): %d calls with values format 1 cut at a NUL; %d problems",
		sc.name, len(answers[ArmF1]), len(cmp.Diffs), cmp.R18, len(cmp.Shadow), len(cmp.NUL), len(probs))
	return probs
}

// encAlignScenario is the full-text regression of C-46 (3) (I1): plaintext
// OMM records cut out of SDN's size-prefixed builder (their doubles 4 bytes
// off the record's first byte) beside the same records finished bare; every
// search finds every record carrying its token, as format 1 does.
func encAlignScenario() encScenario {
	mk := func(class string, pref bool) encClass {
		c := encClass{Name: class, Type: "OMM.fbs"}
		for i := 0; i < 4; i++ {
			name := fmt.Sprintf("ALIGNPROBE %s %d", strings.ToUpper(strings.ReplaceAll(class, "-", "")), i)
			var buf []byte
			if pref {
				buf = ommPlainPrefixed(name, fmt.Sprintf("2026-%03dP", 100+i), uint32(88100+i), 15.1, epochText(i), epochTS(i))
			} else {
				buf = ommPlain(name, fmt.Sprintf("2026-%03dA", 200+i), uint32(88200+i), 15.1, epochText(i), epochTS(i))
			}
			c.Recs = append(c.Recs, &encRec{Type: "OMM.fbs", Class: class, Tagged: i%2 == 0, Bytes: buf, CID: storage.ComputeCID(buf), KeyName: "none"})
		}
		return c
	}
	extra := func(e *encRun, s *storage.FlatSQLStore) []encCall {
		var calls []encCall
		for _, q := range []string{"ALIGNPROBE", "OMMPREFIXCUT", "OMMALIGNED"} {
			want := 4
			if q == "ALIGNPROBE" {
				want = 8
			}
			st := time.Now()
			var l []*storage.Record
			var err error
			for time.Since(st) < 45*time.Second {
				_ = s.CheckFullTextSearch("OMM.fbs", q)
				l, err = s.QueryRawRecords(storage.RawRecordQuery{SchemaName: "OMM.fbs", Search: q, UseRowIDCursor: true, Limit: 100})
				if err == nil && len(l) >= want {
					break
				}
				time.Sleep(time.Second)
			}
			rows := []Row{ValueRow("hits", strconv.Itoa(len(l)))}
			if err != nil {
				rows = append(rows, encErrRow(err))
			}
			for _, r := range l {
				class := ""
				if w := e.byCID[r.CID]; w != nil {
					class = w.Class
				}
				rows = append(rows, ValueRow("cid", r.CID, "class", class))
			}
			calls = append(calls, encCall{Name: "FTS PROBE " + q, Rows: sortRows(rows)})
		}
		return calls
	}
	return encScenario{name: "align", classes: []encClass{mk("omm-prefixcut", true), mk("omm-aligned", false)}, only: []string{"OMM.fbs"}, extra: extra}
}

// DriveEncryptedFields runs the encrypted-field proof (this file's doc) on
// fresh stores and writes a run "encfields" (answers, keys, manifests and
// the stock-reader report under <out>/encfields). P4PROOF_ENC_ONLY=align runs
// the full-text regression alone.
func DriveEncryptedFields(ctx context.Context, c Config, logf Logf) (*Run, error) {
	r := &Run{Kind: "encfields", Arm: ArmS, Format: "4", Label: "fresh", Started: time.Now().UTC().Format(time.RFC3339),
		Machine: ThisMachine(), LoadStart: Load(), Extra: map[string]any{}}
	if err := PrewarmAOT(); err != nil {
		return r, fmt.Errorf("harness: %w", err)
	}
	root := c.workPath("encfields")
	_ = os.RemoveAll(root)
	defer discardStore(root)
	keys := newEncKeys()
	var scenarios []encScenario
	if os.Getenv("P4PROOF_ENC_ONLY") != "align" {
		classes, err := encClasses(keys)
		if err != nil {
			return r, err
		}
		scenarios = append(scenarios, encScenario{name: "fields", classes: classes, migrate: true, reader: true})
	}
	scenarios = append(scenarios, encAlignScenario())
	var probs []string
	for _, sc := range scenarios {
		rep := map[string]any{"records": 0, "load_start": Load()}
		for _, cl := range sc.classes {
			rep["records"] = rep["records"].(int) + len(cl.Recs)
		}
		for _, p := range runEncScenario(ctx, c, root, keys, sc, logf, rep) {
			probs = append(probs, sc.name+": "+p)
		}
		rep["load_end"] = Load()
		r.Extra[sc.name] = rep
	}
	r.Extra["problems"] = append([]string{}, probs...)
	r.LoadEnd = Load()
	if c.Out != "" {
		if _, err := WriteRun(c.Out, r); err != nil {
			return r, err
		}
	}
	if len(probs) > 0 {
		return r, errors.New(strings.Join(probs, "\n"))
	}
	return r, nil
}
