<script>
  /**
   * Node-location globe. Canvas-2D orthographic projection — no map tiles, no
   * external libraries: coastlines are the inline Natural Earth 110m rings
   * (src/land.json, generated by tools/make-land.mjs) and node positions are
   * the feed's mmdb-resolved LAT/LON fields. CSP-clean by construction.
   *
   * Interaction: drag to rotate, auto-spin when idle, hover highlights the
   * nearest node dot (tooltip), click opens the node (onSelect).
   * Styled only with theme.js tokens.
   */
  import { onMount } from 'svelte';
  import { theme } from 'spaceaware-student-sdn/src/lib/theme.js';
  import { normalizeTrust, hasTrustAssertion } from './trust.js';
  import { shortId } from './format.js';
  import LAND from './land.json';

  /** @type {{ nodes: any[], selectedId?: string, onSelect?: (node: any) => void }} */
  let { nodes = [], selectedId = '', onSelect = () => {} } = $props();

  let canvas;
  let wrap;
  let raf = 0;
  let lonRot = -60; // start over the Atlantic
  let latRot = 22;
  let dragging = false;
  let dragBase = null;
  let hover = null; // {node, x, y}
  let lastPointer = null;

  const DEG = Math.PI / 180;

  const placed = $derived(nodes.filter((n) => n.lat !== 0 || n.lon !== 0));

  function dotColor(n) {
    if (normalizeTrust(n.trustLevel) === 'never') return theme.red;
    if (n.online) return theme.green;
    return hasTrustAssertion(n.trustLevel) ? theme.amber : theme.textMuted;
  }

  /** Orthographic projection; returns null on the far side. */
  function project(lat, lon, cx, cy, r) {
    const φ = lat * DEG;
    const λ = (lon + lonRot) * DEG;
    const φ0 = latRot * DEG;
    const cosc = Math.sin(φ0) * Math.sin(φ) + Math.cos(φ0) * Math.cos(φ) * Math.cos(λ);
    if (cosc < 0) return null;
    return {
      x: cx + r * Math.cos(φ) * Math.sin(λ),
      y: cy - r * (Math.cos(φ0) * Math.sin(φ) - Math.sin(φ0) * Math.cos(φ) * Math.cos(λ)),
      z: cosc,
    };
  }

  function strokeRing(ctx, ring, cx, cy, r) {
    let pen = false;
    ctx.beginPath();
    for (const [lon, lat] of ring) {
      const p = project(lat, lon, cx, cy, r);
      if (!p) {
        pen = false;
        continue;
      }
      if (pen) ctx.lineTo(p.x, p.y);
      else ctx.moveTo(p.x, p.y);
      pen = true;
    }
    ctx.stroke();
  }

  /** lat/lon → unit vector for great-circle interpolation. */
  function toVec(lat, lon) {
    const φ = lat * DEG;
    const λ = lon * DEG;
    return [Math.cos(φ) * Math.cos(λ), Math.cos(φ) * Math.sin(λ), Math.sin(φ)];
  }

  /**
   * Great-circle arc between two nodes, lifted off the surface for the
   * classic network-arc look; a small dot travels the arc while the far
   * peer is online.
   */
  function drawArc(ctx, a, b, cx, cy, r, tMs) {
    const va = toVec(a.lat, a.lon);
    const vb = toVec(b.lat, b.lon);
    const dot = Math.max(-1, Math.min(1, va[0] * vb[0] + va[1] * vb[1] + va[2] * vb[2]));
    const ω = Math.acos(dot);
    if (ω < 1e-4) return;
    const sinω = Math.sin(ω);
    const STEPS = 40;
    const pts = [];
    for (let i = 0; i <= STEPS; i += 1) {
      const t = i / STEPS;
      const ka = Math.sin((1 - t) * ω) / sinω;
      const kb = Math.sin(t * ω) / sinω;
      const x = ka * va[0] + kb * vb[0];
      const y = ka * va[1] + kb * vb[1];
      const z = ka * va[2] + kb * vb[2];
      const lat = Math.asin(z / Math.hypot(x, y, z)) / DEG;
      const lon = Math.atan2(y, x) / DEG;
      const lift = 1 + 0.1 * Math.sin(Math.PI * t) * Math.min(1, ω / 0.8);
      pts.push(project(lat, lon, cx, cy, r * lift));
    }
    ctx.strokeStyle = b.online ? 'rgba(53,201,216,0.55)' : 'rgba(110,170,190,0.25)';
    ctx.lineWidth = 1.1;
    let pen = false;
    ctx.beginPath();
    for (const p of pts) {
      if (!p) {
        pen = false;
        continue;
      }
      if (pen) ctx.lineTo(p.x, p.y);
      else ctx.moveTo(p.x, p.y);
      pen = true;
    }
    ctx.stroke();
    ctx.lineWidth = 1;
    if (b.online) {
      const t = (tMs / 2400 + (a.peerId + b.peerId).length * 0.13) % 1;
      const p = pts[Math.round(t * STEPS)];
      if (p) {
        ctx.beginPath();
        ctx.arc(p.x, p.y, 1.8, 0, Math.PI * 2);
        ctx.fillStyle = theme.cyan;
        ctx.fill();
      }
    }
  }

  function draw(tMs) {
    const ctx = canvas?.getContext('2d');
    if (!ctx) return;
    const dpr = globalThis.devicePixelRatio || 1;
    const w = wrap.clientWidth;
    const h = wrap.clientHeight;
    if (canvas.width !== w * dpr || canvas.height !== h * dpr) {
      canvas.width = w * dpr;
      canvas.height = h * dpr;
    }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, w, h);

    const cx = w / 2;
    const cy = h / 2;
    const r = Math.min(w, h) / 2 - 18;
    if (r <= 20) return;

    if (!dragging && !hover) lonRot = (lonRot + 0.03) % 360;

    // Sphere disc + limb — flat fill (owner: no off-center "specular" shading).
    ctx.fillStyle = 'rgba(8,16,22,0.88)';
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = theme.hairline;
    ctx.lineWidth = 1;
    ctx.stroke();

    // Graticule every 30°.
    ctx.strokeStyle = 'rgba(110,170,190,0.10)';
    for (let lat = -60; lat <= 60; lat += 30) {
      const ring = [];
      for (let lon = -180; lon <= 180; lon += 4) ring.push([lon, lat]);
      strokeRing(ctx, ring, cx, cy, r);
    }
    for (let lon = -180; lon < 180; lon += 30) {
      const ring = [];
      for (let lat = -88; lat <= 88; lat += 4) ring.push([lon, lat]);
      strokeRing(ctx, ring, cx, cy, r);
    }

    // Coastlines.
    ctx.strokeStyle = 'rgba(159,212,245,0.42)';
    ctx.lineWidth = 1;
    for (const ring of LAND) strokeRing(ctx, ring, cx, cy, r);

    // Peer links: lifted great-circle arcs from self to every placed peer,
    // with a pulse dot travelling the arc while the peer is online.
    const hub = placed.find((n) => n.isSelf && (n.lat !== 0 || n.lon !== 0));
    if (hub) {
      for (const n of placed) {
        if (n === hub) continue;
        drawArc(ctx, hub, n, cx, cy, r, tMs);
      }
    }

    // Node dots (far-side culled by project()).
    hover = null;
    const pulse = 0.5 + 0.5 * Math.sin(tMs / 500);
    for (const n of placed) {
      const p = project(n.lat, n.lon, cx, cy, r);
      if (!p) continue;
      const color = dotColor(n);
      const isSel = n.peerId === selectedId && (!n.isSelf || selectedId);
      if (n.online) {
        ctx.beginPath();
        ctx.arc(p.x, p.y, 3.4 + pulse * 4, 0, Math.PI * 2);
        ctx.strokeStyle = color;
        ctx.globalAlpha = 0.35 * (1 - pulse);
        ctx.stroke();
        ctx.globalAlpha = 1;
      }
      ctx.beginPath();
      ctx.arc(p.x, p.y, 3.4, 0, Math.PI * 2);
      ctx.fillStyle = color;
      ctx.fill();
      if (n.isSelf || isSel) {
        ctx.beginPath();
        ctx.arc(p.x, p.y, 6, 0, Math.PI * 2);
        ctx.strokeStyle = n.isSelf ? theme.cyan : theme.textBright;
        ctx.lineWidth = 1.2;
        ctx.stroke();
        ctx.lineWidth = 1;
      }
      if (lastPointer) {
        const dx = lastPointer.x - p.x;
        const dy = lastPointer.y - p.y;
        if (dx * dx + dy * dy < 100 && (!hover || p.z > hover.z)) hover = { node: n, x: p.x, y: p.y, z: p.z };
      }
    }

    // Hover tooltip.
    if (hover) {
      const n = hover.node;
      const label = `${n.dn || n.org || shortId(n.peerId)}${n.geoLabel ? ' · ' + n.geoLabel : ''}`;
      ctx.font = '14px "IBM Plex Mono", ui-monospace, monospace';
      const tw = ctx.measureText(label).width;
      const tx = Math.min(Math.max(hover.x + 12, 6), w - tw - 16);
      const ty = Math.max(hover.y - 14, 20);
      ctx.fillStyle = 'rgba(6,13,18,0.92)';
      ctx.fillRect(tx - 6, ty - 14, tw + 12, 22);
      ctx.strokeStyle = theme.hairline;
      ctx.strokeRect(tx - 6, ty - 14, tw + 12, 22);
      ctx.fillStyle = theme.textBright;
      ctx.fillText(label, tx, ty + 2);
    }
    canvas.style.cursor = hover ? 'pointer' : dragging ? 'grabbing' : 'grab';

    raf = requestAnimationFrame(draw);
  }

  function pointerPos(e) {
    const rect = canvas.getBoundingClientRect();
    return { x: e.clientX - rect.left, y: e.clientY - rect.top };
  }

  function onPointerDown(e) {
    dragging = true;
    dragBase = { ...pointerPos(e), lonRot, latRot };
    canvas.setPointerCapture(e.pointerId);
  }

  function onPointerMove(e) {
    lastPointer = pointerPos(e);
    if (!dragging || !dragBase) return;
    const r = Math.min(wrap.clientWidth, wrap.clientHeight) / 2 - 18;
    const degPerPx = 90 / r;
    lonRot = dragBase.lonRot + (lastPointer.x - dragBase.x) * degPerPx;
    latRot = Math.max(-80, Math.min(80, dragBase.latRot + (lastPointer.y - dragBase.y) * degPerPx));
  }

  function onPointerUp(e) {
    const moved =
      dragBase && (Math.abs(pointerPos(e).x - dragBase.x) > 3 || Math.abs(pointerPos(e).y - dragBase.y) > 3);
    dragging = false;
    dragBase = null;
    if (!moved && hover) onSelect(hover.node);
  }

  onMount(() => {
    raf = requestAnimationFrame(draw);
    return () => cancelAnimationFrame(raf);
  });
</script>

<div class="wrap" bind:this={wrap}>
  <canvas
    bind:this={canvas}
    onpointerdown={onPointerDown}
    onpointermove={onPointerMove}
    onpointerup={onPointerUp}
    onpointerleave={() => (lastPointer = null)}
  ></canvas>
  <div class="legend" style="color:{theme.textFaint};">
    <span><i style="background:{theme.green};"></i>ONLINE</span>
    <span><i style="background:{theme.amber};"></i>OFFLINE·TRUSTED</span>
    <span><i style="background:{theme.textMuted};"></i>OFFLINE</span>
    <span><i class="ring" style="border-color:{theme.cyan};"></i>SELF</span>
  </div>
</div>

<style>
  .wrap {
    position: relative;
    width: 100%;
    height: 100%;
    /* A hard min-height made the globe TALLER than a short panel and it spilled
       out the bottom. The canvas already scales to the container in both
       dimensions (radius = min(w,h)/2 - 18), so the wrap just has to be
       allowed to shrink — and clip, so nothing can escape at any height. */
    min-height: 0;
    overflow: hidden;
  }
  canvas {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    touch-action: none;
  }
  .legend {
    position: absolute;
    left: 10px;
    bottom: 8px;
    display: flex;
    gap: 12px;
    font-size: 11px;
    letter-spacing: 0.14em;
    pointer-events: none;
  }
  .legend span {
    display: inline-flex;
    align-items: center;
    gap: 5px;
  }
  .legend i {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    display: inline-block;
  }
  .legend i.ring {
    background: transparent;
    border: 1.2px solid;
  }
</style>
