#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Use the host's existing anonymous-read policy, not a second schema list.
export function publicRecordSchemas() {
  const source = readFileSync(new URL('../../sdn-server/internal/sds/public_read.go', import.meta.url), 'utf8');
  const body = source.match(/var publicReadSchemas = map\[string\]string\{([\s\S]*?)\n\}/)?.[1];
  if (!body) throw new Error('Cannot read the node public-schema policy');
  const schemas = [...body.matchAll(/^\s*"([A-Z]{3})\.fbs":/gm)].map((match) => match[1].toLowerCase());
  if (!schemas.length) throw new Error('The node public-schema policy is empty');
  return schemas;
}

function integer(value, name, min, max) {
  if (!Number.isSafeInteger(value) || value < min || value > max) {
    throw new Error(`${name} must be an integer from ${min} to ${max}`);
  }
  return value;
}

export function renderNginx({ schemas = ['omm'], upstream = 'http://127.0.0.1:7173',
  listen = '127.0.0.1:8088', cacheMiB = 128, ttlSeconds = 15 } = {}) {
  const publicSchemas = new Set(publicRecordSchemas());
  if (!Array.isArray(schemas) || !schemas.length || schemas.some((code) => !publicSchemas.has(code))) {
    throw new Error('Select lowercase schema codes from the node public-schema policy');
  }
  // The renderer never accepts directives, credentials, remote origins or TLS
  // bypasses. Terminate external TLS at the existing edge; keep this hop local.
  const origin = /^http:\/\/(127\.0\.0\.1|\[::1\]):([0-9]{1,5})$/.exec(upstream);
  if (!origin) throw new Error('upstream must be an explicit loopback HTTP address');
  integer(Number(origin[2]), 'upstream port', 1, 65535);
  const address = /^(127\.0\.0\.1|\[::1\]|0\.0\.0\.0):([0-9]{1,5})$/.exec(listen);
  if (!address) throw new Error('listen must be a loopback address or explicit 0.0.0.0 with a port');
  integer(Number(address[2]), 'listen port', 1, 65535);
  integer(cacheMiB, 'cacheMiB', 1, 1024);
  integer(ttlSeconds, 'ttlSeconds', 1, 60);
  const routes = [...new Set(schemas)].sort().map((code) => `/api/v1/data/${code}/bulk`);
  const locations = routes.map((route) => `    location = ${route} {
      if ($request_method = OPTIONS) { return 204; }
      proxy_pass ${upstream};
      proxy_cache records;
    }`).join('\n');

  return `# Generated by deployment/public-origin/render-nginx.mjs.
# A dedicated public record origin, not an operator/API gateway.
worker_processes 1;
pid /tmp/nginx.pid;
error_log stderr warn;
events { worker_connections 256; }
http {
  server_tokens off;
  client_body_temp_path /tmp/client-body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  log_format records 'status=$status cache=$upstream_cache_status bytes=$body_bytes_sent';
  access_log /dev/stdout records;
  proxy_cache_path /tmp/record-cache levels=1:2 keys_zone=records:4m max_size=${cacheMiB}m inactive=10m use_temp_path=off;
  map $request_uri $record_route {
    default 0;
${routes.map((route) => `    ~^${route}(\\?|$) 1;`).join('\n')}
    ~^/api/v1/ready(\\?|$) 2;
  }
  map $upstream_status $bad_status { default 1; 200 0; }
  map $upstream_http_content_type $bad_type {
    default 1;
    "~^application/vnd\\.sdn\\.flatbuffers\\.stream($|;)" 0;
  }
  map $upstream_http_etag $missing_etag { default 0; "" 1; }
  map $http_cache_control $client_bypass { default 1; "" 0; }
  # Do not give a CDN a cacheable error, cookie-bearing reply or non-record body.
  map "$status:$bad_type:$missing_etag:$record_route:$client_bypass:$http_pragma:$upstream_http_set_cookie" $public_response {
    default 0;
    "200:0:0:1:0::" 1;
    "304:0:0:1:0::" 1;
  }
  map "$public_response:$upstream_http_cache_control" $record_cache_control {
    default no-store;
    "1:" "public, max-age=0, s-maxage=${ttlSeconds}, must-revalidate";
    ~^1:(.+)$ $1;
  }
  server {
    listen ${listen};
    server_name _;
    client_max_body_size 1k;
    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 30s;
    if ($record_route = 0) { return 404; }
    if ($request_method !~ ^(GET|HEAD|OPTIONS)$) { return 405; }
    if ($http_authorization != "") { return 403; }
    if ($http_cookie != "") { return 403; }
    if ($http_range != "") { return 416; }
    if ($http_transfer_encoding != "") { return 400; }
    if ($content_length !~ ^(0|)$) { return 400; }
    add_header Cache-Control $record_cache_control always;
    add_header X-SDN-Cache $upstream_cache_status always;
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Accept, If-None-Match, If-Modified-Since, Cache-Control, Pragma" always;
    add_header Access-Control-Expose-Headers "ETag, Age, Cache-Control, X-SDN-Record-Count, X-SDN-Cache" always;
    add_header Vary Accept always;
    add_header X-Content-Type-Options nosniff always;
    proxy_hide_header Cache-Control;
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Credentials;
    proxy_hide_header Access-Control-Expose-Headers;
    proxy_hide_header Access-Control-Allow-Methods;
    proxy_hide_header Access-Control-Allow-Headers;
    # Preserve the origin Date on cache hits so another shared cache computes
    # the response's existing age instead of starting a fresh TTL at this hop.
    proxy_pass_header Date;
    # Only these request headers cross the boundary. Host and forwarded headers
    # supplied by a client cannot select another origin or impersonate a client.
    proxy_pass_request_headers off;
    proxy_pass_request_body off;
    proxy_set_header Host localhost;
    proxy_set_header Connection "";
    proxy_set_header Content-Length "";
    proxy_set_header Accept $http_accept;
    proxy_set_header Cache-Control $http_cache_control;
    proxy_set_header Pragma $http_pragma;
    proxy_set_header If-Match $http_if_match;
    proxy_set_header If-Unmodified-Since $http_if_unmodified_since;
    proxy_http_version 1.1;
    proxy_connect_timeout 5s;
    proxy_read_timeout 30s;
    proxy_send_timeout 10s;
    proxy_buffers 8 16k;
    proxy_max_temp_file_size 16m;
    proxy_cache_key "records-v1|${upstream}|$request_uri|$http_accept";
    proxy_cache_valid 200 ${ttlSeconds}s;
    proxy_cache_lock on;
    proxy_cache_lock_age 30s;
    proxy_cache_lock_timeout 30s;
    proxy_cache_revalidate on;
    proxy_cache_use_stale off;
    proxy_cache_bypass $client_bypass $http_pragma $http_if_match $http_if_unmodified_since;
    proxy_no_cache $client_bypass $http_pragma $http_if_match $http_if_unmodified_since $bad_status $bad_type $missing_etag $upstream_http_set_cookie;
    # Never ignore upstream Cache-Control, Vary, Set-Cookie or X-Accel-Expires.
${locations}
    location = /api/v1/ready {
      if ($request_method = OPTIONS) { return 204; }
      proxy_pass ${upstream};
      proxy_cache off;
    }
    location / { return 404; }
  }
}
`;
}

function main(args) {
  const options = {};
  const names = { '--schemas': 'schemas', '--upstream': 'upstream', '--listen': 'listen',
    '--cache-mib': 'cacheMiB', '--ttl-seconds': 'ttlSeconds' };
  for (let i = 0; i < args.length; i += 2) {
    const name = names[args[i]];
    if (!name || args[i + 1] === undefined || Object.hasOwn(options, name)) {
      throw new Error('Usage: render-nginx.mjs [--schemas omm,cat] [--upstream http://127.0.0.1:7173] [--listen 127.0.0.1:8088] [--cache-mib 128] [--ttl-seconds 15]');
    }
    const value = args[i + 1];
    options[name] = name === 'schemas' ? value.split(',')
      : ['cacheMiB', 'ttlSeconds'].includes(name) ? Number(value) : value;
  }
  process.stdout.write(renderNginx(options));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(process.argv.slice(2)); }
  catch (error) { process.stderr.write(`${error.message}\n`); process.exitCode = 1; }
}
